-- Seed data for Mega Evolution > Ascended Heroes, 295 cards.
-- Run this once in the Supabase SQL editor after schema.sql AND
-- set_visibility.sql (this seed sets the new set to hidden by default).
-- Stock defaults to 0 for every variant -- cards stay greyed out on the
-- storefront (and the whole set stays hidden) until you set real stock
-- numbers and flip visibility on in /admin. Prices are rough starting
-- defaults by rarity tier (SEK) -- edit any of them later.

with s as (
  insert into sets (category_slug, category_name, slug, name, is_visible)
  values ('mega-evolution', 'Mega Evolution', 'ascended-heroes', 'Ascended Heroes', false)
  returning id
),
inserted_cards as (
  insert into cards (set_id, number, name, rarity)
  select s.id, v.number, v.name, v.rarity
  from s, (values
  (1, 'Erika''s Oddish', 'common'),
  (2, 'Erika''s Gloom', 'common'),
  (3, 'Erika''s Vileplume ex', 'common'),
  (4, 'Erika''s Bellsprout', 'common'),
  (5, 'Erika''s Weepinbell', 'common'),
  (6, 'Erika''s Victreebel', 'common'),
  (7, 'Erika''s Tangela', 'common'),
  (8, 'Chikorita', 'common'),
  (9, 'Bayleef', 'common'),
  (10, 'Mega Meganium ex', 'common'),
  (11, 'Wurmple', 'common'),
  (12, 'Silcoon', 'common'),
  (13, 'Beautifly', 'common'),
  (14, 'Cascoon', 'common'),
  (15, 'Dustox', 'common'),
  (16, 'Budew', 'common'),
  (17, 'Grubbin', 'common'),
  (18, 'Team Rocket''s Tarountula', 'common'),
  (19, 'Team Rocket''s Spidops', 'common'),
  (20, 'Charmander', 'common'),
  (21, 'Charmeleon', 'common'),
  (22, 'Mega Charizard Y ex', 'common'),
  (23, 'Ethan''s Slugma', 'common'),
  (24, 'Ethan''s Magcargo', 'common'),
  (25, 'Entei', 'common'),
  (26, 'Ethan''s Ho-Oh ex', 'common'),
  (27, 'Numel', 'common'),
  (28, 'Camerupt', 'common'),
  (29, 'Tepig', 'common'),
  (30, 'Pignite', 'common'),
  (31, 'Mega Emboar ex', 'common'),
  (32, 'N''s Darumaka', 'common'),
  (33, 'N''s Darmanitan', 'common'),
  (34, 'Salandit', 'common'),
  (35, 'Salazzle', 'common'),
  (36, 'Scorbunny', 'common'),
  (37, 'Raboot', 'common'),
  (38, 'Cinderace ex', 'common'),
  (39, 'Psyduck', 'common'),
  (40, 'Golduck', 'common'),
  (41, 'Totodile', 'common'),
  (42, 'Croconaw', 'common'),
  (43, 'Mega Feraligatr ex', 'common'),
  (44, 'Sneasel', 'common'),
  (45, 'Weavile', 'common'),
  (46, 'Snorunt', 'common'),
  (47, 'Mega Froslass ex', 'common'),
  (48, 'Regice ex', 'common'),
  (49, 'N''s Vanillite', 'common'),
  (50, 'N''s Vanillish', 'common'),
  (51, 'N''s Vanilluxe', 'common'),
  (52, 'Snom', 'common'),
  (53, 'Frosmoth', 'common'),
  (54, 'Glastrier', 'common'),
  (55, 'Pikachu', 'common'),
  (56, 'Raichu', 'common'),
  (57, 'Pikachu ex', 'common'),
  (58, 'Voltorb ex', 'common'),
  (59, 'Tynamo', 'common'),
  (60, 'Eelektrik', 'common'),
  (61, 'Mega Eelektross ex', 'common'),
  (62, 'Stunfisk', 'common'),
  (63, 'Helioptile', 'common'),
  (64, 'Heliolisk', 'common'),
  (65, 'Charjabug', 'common'),
  (66, 'Vikavolt', 'common'),
  (67, 'Tapu Koko', 'common'),
  (68, 'Hop''s Pincurchin ex', 'common'),
  (69, 'Iono''s Tadbulb', 'common'),
  (70, 'Iono''s Bellibolt ex', 'common'),
  (71, 'Iono''s Wattrel', 'common'),
  (72, 'Iono''s Kilowattrel', 'common'),
  (73, 'Miraidon ex', 'common'),
  (74, 'Clefairy', 'common'),
  (75, 'Clefable', 'common'),
  (76, 'Lillie''s Clefairy ex', 'common'),
  (77, 'Team Rocket''s Exeggcute', 'common'),
  (78, 'Team Rocket''s Exeggutor', 'common'),
  (79, 'Team Rocket''s Mewtwo ex', 'common'),
  (80, 'Togepi', 'common'),
  (81, 'Togetic', 'common'),
  (82, 'Togekiss', 'common'),
  (83, 'Marill', 'common'),
  (84, 'Azumarill ex', 'common'),
  (85, 'Misdreavus', 'common'),
  (86, 'Mismagius', 'common'),
  (87, 'Ralts', 'common'),
  (88, 'Kirlia', 'common'),
  (89, 'Mega Gardevoir ex', 'common'),
  (90, 'Shuppet', 'common'),
  (91, 'Banette', 'common'),
  (92, 'Rotom', 'common'),
  (93, 'Swirlix', 'common'),
  (94, 'Slurpuff', 'common'),
  (95, 'Hop''s Phantump', 'common'),
  (96, 'Hop''s Trevenant', 'common'),
  (97, 'Team Rocket''s Mimikyu', 'common'),
  (98, 'Spectrier', 'common'),
  (99, 'Munkidori', 'common'),
  (100, 'Team Rocket''s Diglett', 'common'),
  (101, 'Team Rocket''s Dugtrio', 'common'),
  (102, 'Hitmontop', 'common'),
  (103, 'Meditite', 'common'),
  (104, 'Medicham', 'common'),
  (105, 'Lunatone', 'common'),
  (106, 'Solrock', 'common'),
  (107, 'Regirock ex', 'common'),
  (108, 'Groudon', 'common'),
  (109, 'Cynthia''s Gible', 'common'),
  (110, 'Cynthia''s Gabite', 'common'),
  (111, 'Cynthia''s Garchomp ex', 'common'),
  (112, 'Riolu', 'common'),
  (113, 'Mega Lucario ex', 'common'),
  (114, 'Stunfisk ex', 'common'),
  (115, 'Pancham', 'common'),
  (116, 'Mega Hawlucha ex', 'common'),
  (117, 'Carbink', 'common'),
  (118, 'Rolycoly', 'common'),
  (119, 'Carkol', 'common'),
  (120, 'Coalossal', 'common'),
  (121, 'Koraidon ex', 'common'),
  (122, 'Okidogi', 'common'),
  (123, 'Gastly', 'common'),
  (124, 'Haunter', 'common'),
  (125, 'Mega Gengar ex', 'common'),
  (126, 'Team Rocket''s Murkrow', 'common'),
  (127, 'Team Rocket''s Honchkrow', 'common'),
  (128, 'Poochyena', 'common'),
  (129, 'Mightyena', 'common'),
  (130, 'Galarian Zigzagoon', 'common'),
  (131, 'Galarian Linoone', 'common'),
  (132, 'Galarian Obstagoon', 'common'),
  (133, 'Cynthia''s Spiritomb', 'common'),
  (134, 'Scraggy', 'common'),
  (135, 'Mega Scrafty ex', 'common'),
  (136, 'N''s Zorua', 'common'),
  (137, 'N''s Zoroark ex', 'common'),
  (138, 'Vullaby', 'common'),
  (139, 'Mandibuzz ex', 'common'),
  (140, 'Pangoro', 'common'),
  (141, 'Hoopa', 'common'),
  (142, 'Fezandipiti ex', 'common'),
  (143, 'Pecharunt', 'common'),
  (144, 'Mawile', 'common'),
  (145, 'Registeel ex', 'common'),
  (146, 'Pawniard', 'common'),
  (147, 'Bisharp', 'common'),
  (148, 'Kingambit', 'common'),
  (149, 'Togedemaru ex', 'common'),
  (150, 'Dratini', 'common'),
  (151, 'Dragonair', 'common'),
  (152, 'Mega Dragonite ex', 'common'),
  (153, 'Rayquaza', 'common'),
  (154, 'N''s Reshiram', 'common'),
  (155, 'N''s Zekrom', 'common'),
  (156, 'Noibat', 'common'),
  (157, 'Noivern', 'common'),
  (158, 'Dreepy', 'common'),
  (159, 'Drakloak', 'common'),
  (160, 'Dragapult ex', 'common'),
  (161, 'Team Rocket''s Meowth', 'common'),
  (162, 'Team Rocket''s Kangaskhan ex', 'common'),
  (163, 'Larry''s Dunsparce', 'common'),
  (164, 'Larry''s Dudunsparce ex', 'common'),
  (165, 'Skitty', 'common'),
  (166, 'Delcatty', 'common'),
  (167, 'Zangoose ex', 'common'),
  (168, 'Larry''s Starly', 'common'),
  (169, 'Larry''s Staravia', 'common'),
  (170, 'Larry''s Staraptor', 'common'),
  (171, 'Fan Rotom', 'common'),
  (172, 'Mega Audino ex', 'common'),
  (173, 'Larry''s Rufflet', 'common'),
  (174, 'Larry''s Braviary', 'common'),
  (175, 'Larry''s Komala', 'common'),
  (176, 'Drampa', 'common'),
  (177, 'Hop''s Cramorant', 'common'),
  (178, 'Terapagos', 'common'),
  (179, 'Terapagos ex', 'common'),
  (180, 'Acerola''s Mischief', 'common'),
  (181, 'Air Balloon', 'common'),
  (182, 'Anthea & Concordia', 'common'),
  (183, 'Boss''s Orders', 'common'),
  (184, 'Buddy-Buddy Poffin', 'common'),
  (185, 'Canari', 'common'),
  (186, 'Counter Gain', 'common'),
  (187, 'Fighting Gong', 'common'),
  (188, 'Forest of Vitality', 'common'),
  (189, 'Glass Trumpet', 'common'),
  (190, 'Iris''s Fighting Spirit', 'common'),
  (191, 'Light Ball', 'common'),
  (192, 'Lillie''s Determination', 'common'),
  (193, 'Mega Signal', 'common'),
  (194, 'Mystery Garden', 'common'),
  (195, 'N''s PP Up', 'common'),
  (196, 'Night Stretcher', 'common'),
  (197, 'Nighttime Mine', 'common'),
  (198, 'Poke Pad', 'common'),
  (199, 'Premium Power Pro', 'common'),
  (200, 'Surfer', 'common'),
  (201, 'Team Rocket''s Archer', 'common'),
  (202, 'Team Rocket''s Ariana', 'common'),
  (203, 'Team Rocket''s Factory', 'common'),
  (204, 'Team Rocket''s Giovanni', 'common'),
  (205, 'Team Rocket''s Great Ball', 'common'),
  (206, 'Team Rocket''s Hypnotizer', 'common'),
  (207, 'Team Rocket''s Petrel', 'common'),
  (208, 'Team Rocket''s Proton', 'common'),
  (209, 'Team Rocket''s Transceiver', 'common'),
  (210, 'Team Rocket''s Watchtower', 'common'),
  (211, 'Thick Scale', 'common'),
  (212, 'Tool Scrapper', 'common'),
  (213, 'Ultra Ball', 'common'),
  (214, 'Urbain', 'common'),
  (215, 'Waitress', 'common'),
  (216, 'Prism Energy', 'common'),
  (217, 'Team Rocket''s Energy', 'common'),
  (218, 'Erika''s Tangela', 'illustration_rare'),
  (219, 'Beautifly', 'illustration_rare'),
  (220, 'Dustox', 'illustration_rare'),
  (221, 'Budew', 'illustration_rare'),
  (222, 'Ethan''s Magcargo', 'illustration_rare'),
  (223, 'Numel', 'illustration_rare'),
  (224, 'Salazzle', 'illustration_rare'),
  (225, 'Scorbunny', 'illustration_rare'),
  (226, 'Psyduck', 'illustration_rare'),
  (227, 'Snorunt', 'illustration_rare'),
  (228, 'Weavile', 'illustration_rare'),
  (229, 'Heliolisk', 'illustration_rare'),
  (230, 'Vikavolt', 'illustration_rare'),
  (231, 'Iono''s Wattrel', 'illustration_rare'),
  (232, 'Marill', 'illustration_rare'),
  (233, 'Misdreavus', 'illustration_rare'),
  (234, 'Banette', 'illustration_rare'),
  (235, 'Togekiss', 'illustration_rare'),
  (236, 'Slurpuff', 'illustration_rare'),
  (237, 'Hop''s Trevenant', 'illustration_rare'),
  (238, 'Team Rocket''s Mimikyu', 'illustration_rare'),
  (239, 'Team Rocket''s Dugtrio', 'illustration_rare'),
  (240, 'Hitmontop', 'illustration_rare'),
  (241, 'Medicham', 'illustration_rare'),
  (242, 'Carbink', 'illustration_rare'),
  (243, 'Mightyena', 'illustration_rare'),
  (244, 'Cynthia''s Spiritomb', 'illustration_rare'),
  (245, 'Galarian Obstagoon', 'illustration_rare'),
  (246, 'Mawile', 'illustration_rare'),
  (247, 'Dreepy', 'illustration_rare'),
  (248, 'Drakloak', 'illustration_rare'),
  (249, 'Larry''s Staraptor', 'illustration_rare'),
  (250, 'Fan Rotom', 'illustration_rare'),
  (251, 'Sprigatito ex', 'ultra_rare'),
  (252, 'Stunfisk ex', 'ultra_rare'),
  (253, 'Mega Audino ex', 'ultra_rare'),
  (254, 'Anthea & Concordia', 'ultra_rare'),
  (255, 'Black Belt''s Training', 'ultra_rare'),
  (256, 'Boss''s Orders', 'ultra_rare'),
  (257, 'Canari', 'ultra_rare'),
  (258, 'Cheren', 'ultra_rare'),
  (259, 'Counter Gain', 'ultra_rare'),
  (260, 'Glass Trumpet', 'ultra_rare'),
  (261, 'Jamming Tower', 'ultra_rare'),
  (262, 'N''s PP Up', 'ultra_rare'),
  (263, 'Team Rocket''s Transceiver', 'ultra_rare'),
  (264, 'Ultra Ball', 'ultra_rare'),
  (265, 'Mega Froslass ex', 'ultra_rare'),
  (266, 'Mega Eelektross ex', 'ultra_rare'),
  (267, 'Mega Diancie ex', 'ultra_rare'),
  (268, 'Mega Hawlucha ex', 'ultra_rare'),
  (269, 'Mega Gengar ex', 'ultra_rare'),
  (270, 'Mega Scrafty ex', 'ultra_rare'),
  (271, 'Mega Dragonite ex', 'ultra_rare'),
  (272, 'Mega Meganium ex', 'special_illustration_rare'),
  (273, 'Mega Emboar ex', 'special_illustration_rare'),
  (274, 'Mega Feraligatr ex', 'special_illustration_rare'),
  (275, 'Mega Froslass ex', 'special_illustration_rare'),
  (276, 'Pikachu ex', 'special_illustration_rare'),
  (277, 'Pikachu ex', 'special_illustration_rare'),
  (278, 'Mega Eelektross ex', 'special_illustration_rare'),
  (279, 'Iono''s Bellibolt ex', 'special_illustration_rare'),
  (280, 'Lillie''s Clefairy ex', 'special_illustration_rare'),
  (281, 'Team Rocket''s Mewtwo ex', 'special_illustration_rare'),
  (282, 'Mega Diancie ex', 'special_illustration_rare'),
  (283, 'Mega Hawlucha ex', 'special_illustration_rare'),
  (284, 'Mega Gengar ex', 'special_illustration_rare'),
  (285, 'Mega Scrafty ex', 'special_illustration_rare'),
  (286, 'N''s Zoroark ex', 'special_illustration_rare'),
  (287, 'Marnie''s Grimmsnarl ex', 'special_illustration_rare'),
  (288, 'Fezandipiti ex', 'special_illustration_rare'),
  (289, 'Steven''s Metagross ex', 'special_illustration_rare'),
  (290, 'Mega Dragonite ex', 'special_illustration_rare'),
  (291, 'Canari', 'special_illustration_rare'),
  (292, 'Iris''s Fighting Spirit', 'special_illustration_rare'),
  (293, 'Surfer', 'special_illustration_rare'),
  (294, 'Mega Charizard Y ex', 'mega_hyper_rare'),
  (295, 'Mega Dragonite ex', 'mega_hyper_rare')
  ) as v(number, name, rarity)
  returning id, rarity
)
insert into card_variants (card_id, variant, price_sek, stock)
select ic.id, x.variant,
  case
      when ic.rarity = 'common' and x.variant = 'holo' then 4
      when ic.rarity = 'common' then 2
      when ic.rarity = 'illustration_rare' then 15
      when ic.rarity = 'ultra_rare' then 20
      when ic.rarity = 'special_illustration_rare' then 0
      when ic.rarity = 'mega_hyper_rare' then 0
    else 0
  end as price_sek,
  0 as stock
from inserted_cards ic
cross join (values ('normal'), ('holo')) as x(variant);
