-- Seed data for Topps Premier League 2025/26 > Grundset, 280 cards.
-- First installment of the "fler säsonger bakåt"-import (2025/26 +
-- 2024/25 PL, 2026/27 + 2025/26 UCC) — this file is PL 2025/26 only.
--
-- IMPORTANT — accuracy caveat: unlike the Pokémon-katalogen (som byggdes
-- från ett färdigt maskinläsbart dataset), det finns inget sånt dataset
-- för Topps fotbollskort. Den här listan är hopsatt genom att läsa av
-- Topps egen officiella checklista (ripped.topps.com) lag för lag via
-- webbsökning, INTE hämtat maskinläsbart. Korrigerat en uppenbar
-- felplacering (målvakten José Sá stod under West Ham men spelar för
-- Wolverhampton Wanderers — flyttad hit). Men annars är listan INTE
-- dubbelkollad rad för rad, så räkna med enstaka fel: en spelare som
-- bytt klubb sedan checklistan skrevs, en missad rad, eller ett kort
-- som borde ha ett annat nummer än det jag satt här (numren nedan är en
-- egen löpande numrering i den ordning laget listas i källan, inte
-- garanterat samma nummer som står på det fysiska kortets baksida).
-- Stämmer av mot korten ni faktiskt har i handen innan ni litar helt på
-- den här listan.
--
-- Run this once in the Supabase SQL editor after schema.sql AND
-- set_visibility.sql AND topps_rarity.sql AND sets_product_line.sql.
-- Stock defaults to 0 -- cards stay greyed out (and the set stays hidden)
-- until you set real stock in /admin. Price defaults to a flat placeholder
-- -- edit per card once you know actual values.
-- Only a 'normal' variant is created (no holo) since Topps football cards
-- don't use that concept.

with s as (
  insert into sets (category_slug, category_name, slug, name, is_visible, product_line)
  values ('topps-premier-league-25-26', 'Topps Premier League 2025/26', 'grundset', 'Grundset', false, 'sportkort')
  returning id
),
inserted_cards as (
  insert into cards (set_id, number, name, rarity)
  select s.id, v.number, v.name, v.rarity
  from s, (values
  (1, 'David Raya (Arsenal)', 'base'),
  (2, 'William Saliba (Arsenal)', 'base'),
  (3, 'Gabriel Magalhães (Arsenal)', 'base'),
  (4, 'Jurriën Timber (Arsenal)', 'base'),
  (5, 'Mikel Merino (Arsenal)', 'base'),
  (6, 'Thomas Partey (Arsenal)', 'base'),
  (7, 'Declan Rice (Arsenal)', 'base'),
  (8, 'Myles Lewis-Skelly (Arsenal)', 'base'),
  (9, 'Martin Ødegaard (Arsenal)', 'base'),
  (10, 'Ethan Nwaneri (Arsenal)', 'base'),
  (11, 'Bukayo Saka (Arsenal)', 'base'),
  (12, 'Gabriel Martinelli (Arsenal)', 'base'),
  (13, 'Leandro Trossard (Arsenal)', 'base'),
  (14, 'Kai Havertz (Arsenal)', 'base'),
  (15, 'Emiliano Martínez (Aston Villa)', 'base'),
  (16, 'Pau Torres (Aston Villa)', 'base'),
  (17, 'Ezri Konsa (Aston Villa)', 'base'),
  (18, 'Matty Cash (Aston Villa)', 'base'),
  (19, 'Lucas Digne (Aston Villa)', 'base'),
  (20, 'Boubacar Kamara (Aston Villa)', 'base'),
  (21, 'Amadou Onana (Aston Villa)', 'base'),
  (22, 'John McGinn (Aston Villa)', 'base'),
  (23, 'Youri Tielemans (Aston Villa)', 'base'),
  (24, 'Jacob Ramsey (Aston Villa)', 'base'),
  (25, 'Morgan Rogers (Aston Villa)', 'base'),
  (26, 'Louie Barry (Aston Villa RC)', 'base'),
  (27, 'Donyell Malen (Aston Villa)', 'base'),
  (28, 'Ollie Watkins (Aston Villa)', 'base'),
  (29, 'Kepa Arrizabalaga (AFC Bournemouth)', 'base'),
  (30, 'Illia Zabarnyi (AFC Bournemouth)', 'base'),
  (31, 'Dean Huijsen (AFC Bournemouth)', 'base'),
  (32, 'Julio Soler (AFC Bournemouth RC)', 'base'),
  (33, 'Milos Kerkez (AFC Bournemouth)', 'base'),
  (34, 'Tyler Adams (AFC Bournemouth)', 'base'),
  (35, 'Lewis Cook (AFC Bournemouth)', 'base'),
  (36, 'Ryan Christie (AFC Bournemouth)', 'base'),
  (37, 'Luis Sinisterra (AFC Bournemouth)', 'base'),
  (38, 'Antoine Semenyo (AFC Bournemouth)', 'base'),
  (39, 'Justin Kluivert (AFC Bournemouth)', 'base'),
  (40, 'Eli Junior Kroupi (AFC Bournemouth)', 'base'),
  (41, 'Dango Ouattara (AFC Bournemouth)', 'base'),
  (42, 'Evanilson (AFC Bournemouth)', 'base'),
  (43, 'Mark Flekken (Brentford)', 'base'),
  (44, 'Nathan Collins (Brentford)', 'base'),
  (45, 'Sepp van den Berg (Brentford)', 'base'),
  (46, 'Michael Kayode (Brentford)', 'base'),
  (47, 'Christian Nørgaard (Brentford)', 'base'),
  (48, 'Mathias Jensen (Brentford)', 'base'),
  (49, 'Vitaly Janelt (Brentford)', 'base'),
  (50, 'Mikkel Damsgaard (Brentford)', 'base'),
  (51, 'Fábio Carvalho (Brentford)', 'base'),
  (52, 'Kevin Schade (Brentford)', 'base'),
  (53, 'Keane Lewis-Potter (Brentford)', 'base'),
  (54, 'Gustavo Nunes (Brentford RC)', 'base'),
  (55, 'Bryan Mbeumo (Brentford)', 'base'),
  (56, 'Yoane Wissa (Brentford)', 'base'),
  (57, 'Bart Verbruggen (Brighton)', 'base'),
  (58, 'Jan Paul van Hecke (Brighton)', 'base'),
  (59, 'Pervis Estupiñán (Brighton)', 'base'),
  (60, 'Lewis Dunk (Brighton)', 'base'),
  (61, 'Jack Hinshelwood (Brighton)', 'base'),
  (62, 'Yankuba Minteh (Brighton)', 'base'),
  (63, 'Carlos Baleba (Brighton)', 'base'),
  (64, 'Yoon Do-young (Brighton RC)', 'base'),
  (65, 'Yasin Ayari (Brighton RC)', 'base'),
  (66, 'Kaoru Mitoma (Brighton)', 'base'),
  (67, 'Stefanos Tzimas (Brighton RC)', 'base'),
  (68, 'Danny Welbeck (Brighton)', 'base'),
  (69, 'Georginio Rutter (Brighton)', 'base'),
  (70, 'João Pedro (Brighton)', 'base'),
  (71, 'Robert Sánchez (Chelsea)', 'base'),
  (72, 'Levi Colwill (Chelsea)', 'base'),
  (73, 'Tosin Adarabioyo (Chelsea)', 'base'),
  (74, 'Reece James (Chelsea)', 'base'),
  (75, 'Marc Cucurella (Chelsea)', 'base'),
  (76, 'Harrison Murray-Campbell (Chelsea RC)', 'base'),
  (77, 'Moisés Caicedo (Chelsea)', 'base'),
  (78, 'Enzo Fernández (Chelsea)', 'base'),
  (79, 'Cole Palmer (Chelsea)', 'base'),
  (80, 'Kendry Páez (Chelsea RC)', 'base'),
  (81, 'Pedro Neto (Chelsea)', 'base'),
  (82, 'Noni Madueke (Chelsea)', 'base'),
  (83, 'Nicolas Jackson (Chelsea)', 'base'),
  (84, 'Estêvão (Chelsea RC)', 'base'),
  (85, 'Dean Henderson (Crystal Palace)', 'base'),
  (86, 'Tyrick Mitchell (Crystal Palace)', 'base'),
  (87, 'Chadi Riad (Crystal Palace)', 'base'),
  (88, 'Maxence Lacroix (Crystal Palace)', 'base'),
  (89, 'Marc Guéhi (Crystal Palace)', 'base'),
  (90, 'Chris Richards (Crystal Palace)', 'base'),
  (91, 'Daniel Muñoz (Crystal Palace)', 'base'),
  (92, 'Adam Wharton (Crystal Palace)', 'base'),
  (93, 'Romain Esse (Crystal Palace RC)', 'base'),
  (94, 'Daichi Kamada (Crystal Palace)', 'base'),
  (95, 'Eberechi Eze (Crystal Palace)', 'base'),
  (96, 'Ismaïla Sarr (Crystal Palace)', 'base'),
  (97, 'Eddie Nketiah (Crystal Palace)', 'base'),
  (98, 'Jean-Philippe Mateta (Crystal Palace)', 'base'),
  (99, 'Jordan Pickford (Everton)', 'base'),
  (100, 'James Tarkowski (Everton)', 'base'),
  (101, 'Jarrad Branthwaite (Everton)', 'base'),
  (102, 'Vitalii Mykolenko (Everton)', 'base'),
  (103, 'Jake O''Brien (Everton)', 'base'),
  (104, 'Nathan Patterson (Everton)', 'base'),
  (105, 'Roman Dixon (Everton RC)', 'base'),
  (106, 'Tim Iroegbunam (Everton)', 'base'),
  (107, 'Harrison Armstrong (Everton RC)', 'base'),
  (108, 'James Garner (Everton)', 'base'),
  (109, 'Dwight McNeil (Everton)', 'base'),
  (110, 'Iliman Ndiaye (Everton)', 'base'),
  (111, 'Beto (Everton)', 'base'),
  (112, 'Youssef Chermiti (Everton)', 'base'),
  (113, 'Bernd Leno (Fulham)', 'base'),
  (114, 'Calvin Bassey (Fulham)', 'base'),
  (115, 'Joachim Andersen (Fulham)', 'base'),
  (116, 'Sander Berge (Fulham)', 'base'),
  (117, 'Antonee Robinson (Fulham)', 'base'),
  (118, 'Saša Lukić (Fulham)', 'base'),
  (119, 'Josh King (Fulham RC)', 'base'),
  (120, 'Andreas Pereira (Fulham)', 'base'),
  (121, 'Alex Iwobi (Fulham)', 'base'),
  (122, 'Emile Smith Rowe (Fulham)', 'base'),
  (123, 'Harry Wilson (Fulham)', 'base'),
  (124, 'Adama Traoré (Fulham)', 'base'),
  (125, 'Rodrigo Muniz (Fulham)', 'base'),
  (126, 'Raúl Jiménez (Fulham)', 'base'),
  (127, 'Alisson Becker (Liverpool FC)', 'base'),
  (128, 'Virgil van Dijk (Liverpool FC)', 'base'),
  (129, 'Ibrahima Konaté (Liverpool FC)', 'base'),
  (130, 'Andy Robertson (Liverpool FC)', 'base'),
  (131, 'Conor Bradley (Liverpool FC)', 'base'),
  (132, 'Ryan Gravenberch (Liverpool FC)', 'base'),
  (133, 'Alexis Mac Allister (Liverpool FC)', 'base'),
  (134, 'Dominik Szoboszlai (Liverpool FC)', 'base'),
  (135, 'Rio Ngumoha (Liverpool FC RC)', 'base'),
  (136, 'Luis Díaz (Liverpool FC)', 'base'),
  (137, 'Mohamed Salah (Liverpool FC)', 'base'),
  (138, 'Cody Gakpo (Liverpool FC)', 'base'),
  (139, 'Diogo Jota (Liverpool FC)', 'base'),
  (140, 'Darwin Núñez (Liverpool FC)', 'base'),
  (141, 'Ederson (Manchester City)', 'base'),
  (142, 'Rúben Dias (Manchester City)', 'base'),
  (143, 'Joško Gvardiol (Manchester City)', 'base'),
  (144, 'Vitor Reis (Manchester City RC)', 'base'),
  (145, 'Divine Mukasa (Manchester City RC)', 'base'),
  (146, 'Nico González (Manchester City)', 'base'),
  (147, 'Rodri (Manchester City)', 'base'),
  (148, 'Jérémy Doku (Manchester City)', 'base'),
  (149, 'Phil Foden (Manchester City)', 'base'),
  (150, 'Bernardo Silva (Manchester City)', 'base'),
  (151, 'Sávio (Manchester City)', 'base'),
  (152, 'Reigan Heskey (Manchester City RC)', 'base'),
  (153, 'Omar Marmoush (Manchester City)', 'base'),
  (154, 'Erling Haaland (Manchester City)', 'base'),
  (155, 'André Onana (Manchester United)', 'base'),
  (156, 'Matthijs de Ligt (Manchester United)', 'base'),
  (157, 'Leny Yoro (Manchester United)', 'base'),
  (158, 'Lisandro Martínez (Manchester United)', 'base'),
  (159, 'Diogo Dalot (Manchester United)', 'base'),
  (160, 'Sékou Koné (Manchester United RC)', 'base'),
  (161, 'Kobbie Mainoo (Manchester United)', 'base'),
  (162, 'Manuel Ugarte (Manchester United)', 'base'),
  (163, 'Bruno Fernandes (Manchester United)', 'base'),
  (164, 'Shea Lacey (Manchester United RC)', 'base'),
  (165, 'Alejandro Garnacho (Manchester United)', 'base'),
  (166, 'Amad (Manchester United)', 'base'),
  (167, 'Joshua Zirkzee (Manchester United)', 'base'),
  (168, 'Rasmus Højlund (Manchester United)', 'base'),
  (169, 'Nick Pope (Newcastle United)', 'base'),
  (170, 'Dan Burn (Newcastle United)', 'base'),
  (171, 'Sven Botman (Newcastle United)', 'base'),
  (172, 'Fabian Schär (Newcastle United)', 'base'),
  (173, 'Tino Livramento (Newcastle United)', 'base'),
  (174, 'Lewis Hall (Newcastle United)', 'base'),
  (175, 'Lewis Miley (Newcastle United)', 'base'),
  (176, 'Sandro Tonali (Newcastle United)', 'base'),
  (177, 'Joelinton (Newcastle United)', 'base'),
  (178, 'Bruno Guimarães (Newcastle United)', 'base'),
  (179, 'Jacob Murphy (Newcastle United)', 'base'),
  (180, 'Harvey Barnes (Newcastle United)', 'base'),
  (181, 'Anthony Gordon (Newcastle United)', 'base'),
  (182, 'Alexander Isak (Newcastle United)', 'base'),
  (183, 'Matz Sels (Nottingham Forest)', 'base'),
  (184, 'Nikola Milenković (Nottingham Forest)', 'base'),
  (185, 'Ola Aina (Nottingham Forest)', 'base'),
  (186, 'Murillo (Nottingham Forest)', 'base'),
  (187, 'Neco Williams (Nottingham Forest)', 'base'),
  (188, 'Zach Abbott (Nottingham Forest RC)', 'base'),
  (189, 'Ryan Yates (Nottingham Forest)', 'base'),
  (190, 'Ibrahim Sangaré (Nottingham Forest)', 'base'),
  (191, 'Elliot Anderson (Nottingham Forest)', 'base'),
  (192, 'Morgan Gibbs-White (Nottingham Forest)', 'base'),
  (193, 'Callum Hudson-Odoi (Nottingham Forest)', 'base'),
  (194, 'Anthony Elanga (Nottingham Forest)', 'base'),
  (195, 'Taiwo Awoniyi (Nottingham Forest)', 'base'),
  (196, 'Chris Wood (Nottingham Forest)', 'base'),
  (197, 'Antonín Kinský (Tottenham Hotspur RC)', 'base'),
  (198, 'Pedro Porro (Tottenham Hotspur)', 'base'),
  (199, 'Micky van de Ven (Tottenham Hotspur)', 'base'),
  (200, 'Cristian Romero (Tottenham Hotspur)', 'base'),
  (201, 'Destiny Udogie (Tottenham Hotspur)', 'base'),
  (202, 'Archie Gray (Tottenham Hotspur)', 'base'),
  (203, 'Dejan Kulusevski (Tottenham Hotspur)', 'base'),
  (204, 'Lucas Bergvall (Tottenham Hotspur)', 'base'),
  (205, 'James Maddison (Tottenham Hotspur)', 'base'),
  (206, 'Will Lankshear (Tottenham Hotspur RC)', 'base'),
  (207, 'Son Heung-Min (Tottenham Hotspur)', 'base'),
  (208, 'Brennan Johnson (Tottenham Hotspur)', 'base'),
  (209, 'Mikey Moore (Tottenham Hotspur)', 'base'),
  (210, 'Dominic Solanke (Tottenham Hotspur)', 'base'),
  (211, 'Alphonse Areola (West Ham United)', 'base'),
  (212, 'Jean-Clair Todibo (West Ham United)', 'base'),
  (213, 'Maximilian Kilman (West Ham United)', 'base'),
  (214, 'Aaron Wan-Bissaka (West Ham United)', 'base'),
  (215, 'Emerson Palmieri (West Ham United)', 'base'),
  (216, 'Oliver Scarles (West Ham United)', 'base'),
  (217, 'Tomáš Souček (West Ham United)', 'base'),
  (218, 'Edson Álvarez (West Ham United)', 'base'),
  (219, 'Guido Rodríguez (West Ham United)', 'base'),
  (220, 'Mohammed Kudus (West Ham United)', 'base'),
  (221, 'Niclas Füllkrug (West Ham United)', 'base'),
  (222, 'Crysencio Summerville (West Ham United)', 'base'),
  (223, 'Jarrod Bowen (West Ham United)', 'base'),
  (224, 'Luis Guilherme (West Ham United RC)', 'base'),
  (225, 'José Sá (Wolverhampton Wanderers)', 'base'),
  (226, 'Nélson Semedo (Wolverhampton Wanderers)', 'base'),
  (227, 'Nasser Djiga (Wolverhampton Wanderers RC)', 'base'),
  (228, 'Emmanuel Agbadou (Wolverhampton Wanderers)', 'base'),
  (229, 'Toti Gomes (Wolverhampton Wanderers)', 'base'),
  (230, 'Rayan Aït-Nouri (Wolverhampton Wanderers)', 'base'),
  (231, 'Marshall Munetsi (Wolverhampton Wanderers)', 'base'),
  (232, 'André (Wolverhampton Wanderers)', 'base'),
  (233, 'João Gomes (Wolverhampton Wanderers)', 'base'),
  (234, 'Rodrigo Gomes (Wolverhampton Wanderers)', 'base'),
  (235, 'Gonçalo Guedes (Wolverhampton Wanderers)', 'base'),
  (236, 'Hwang Hee-chan (Wolverhampton Wanderers)', 'base'),
  (237, 'Jørgen Strand Larsen (Wolverhampton Wanderers)', 'base'),
  (238, 'Matheus Cunha (Wolverhampton Wanderers)', 'base'),
  (239, 'James Trafford (Burnley FC)', 'base'),
  (240, 'Maxime Estève (Burnley FC)', 'base'),
  (241, 'Bashir Humphreys (Burnley FC RC)', 'base'),
  (242, 'Connor Roberts (Burnley FC)', 'base'),
  (243, 'Lucas Pires (Burnley FC)', 'base'),
  (244, 'Josh Laurent (Burnley FC RC)', 'base'),
  (245, 'Josh Cullen (Burnley FC)', 'base'),
  (246, 'Josh Brownhill (Burnley FC)', 'base'),
  (247, 'Hannibal (Burnley FC)', 'base'),
  (248, 'Marcus Edwards (Burnley FC)', 'base'),
  (249, 'Lyle Foster (Burnley FC)', 'base'),
  (250, 'Luca Koleosho (Burnley FC)', 'base'),
  (251, 'Jaidon Anthony (Burnley FC)', 'base'),
  (252, 'Jaydon Banel (Burnley FC RC)', 'base'),
  (253, 'Illan Meslier (Leeds United)', 'base'),
  (254, 'Joe Rodon (Leeds United)', 'base'),
  (255, 'Pascal Struijk (Leeds United)', 'base'),
  (256, 'Jayden Bogle (Leeds United)', 'base'),
  (257, 'Ethan Ampadu (Leeds United)', 'base'),
  (258, 'Ao Tanaka (Leeds United)', 'base'),
  (259, 'Brenden Aaronson (Leeds United)', 'base'),
  (260, 'Ilia Gruev (Leeds United)', 'base'),
  (261, 'Harry Gray (Leeds United RC)', 'base'),
  (262, 'Mateo Joseph (Leeds United RC)', 'base'),
  (263, 'Wilfried Gnonto (Leeds United)', 'base'),
  (264, 'Daniel James (Leeds United)', 'base'),
  (265, 'Patrick Bamford (Leeds United)', 'base'),
  (266, 'Joël Piroe (Leeds United RC)', 'base'),
  (267, 'Anthony Patterson (Sunderland RC)', 'base'),
  (268, 'Trai Hume (Sunderland RC)', 'base'),
  (269, 'Dennis Cirkin (Sunderland RC)', 'base'),
  (270, 'Luke O''Nien (Sunderland RC)', 'base'),
  (271, 'Daniel Ballard (Sunderland RC)', 'base'),
  (272, 'Chris Rigg (Sunderland RC)', 'base'),
  (273, 'Dan Neil (Sunderland RC)', 'base'),
  (274, 'Alan Browne (Sunderland RC)', 'base'),
  (275, 'Jobe Bellingham (Sunderland RC)', 'base'),
  (276, 'Enzo Le Fée (Sunderland)', 'base'),
  (277, 'Romaine Mundle (Sunderland RC)', 'base'),
  (278, 'Patrick Roberts (Sunderland)', 'base'),
  (279, 'Eliezer Mayenda (Sunderland RC)', 'base'),
  (280, 'Wilson Isidor (Sunderland RC)', 'base')
  ) as v(number, name, rarity)
  returning id
)
insert into card_variants (card_id, variant, price_sek, stock)
select ic.id, 'normal', 3, 0
from inserted_cards ic;
