-- Seed data for Scarlet & Violet > Destined Rivals (SV10), 244 cards.
-- Run this once in the Supabase SQL editor after schema.sql AND set_visibility.sql.
-- This creates a NEW category "Scarlet & Violet" (separate from Mega Evolution).
-- Stock defaults to 0 -- cards stay greyed out (and the set hidden) until
-- you set real stock in /admin. Prices are rough defaults by rarity tier
-- (SEK) -- edit any of them later.

with s as (
  insert into sets (category_slug, category_name, slug, name, is_visible)
  values ('scarlet-violet', 'Scarlet & Violet', 'destined-rivals', 'Destined Rivals', false)
  returning id
),
inserted_cards as (
  insert into cards (set_id, number, name, rarity)
  select s.id, v.number, v.name, v.rarity
  from s, (values
  (1, 'Ethan''s Pinsir', 'common'),
  (2, 'Yanma', 'common'),
  (3, 'Yanmega ex', 'common'),
  (4, 'Pineco', 'common'),
  (5, 'Shroomish', 'common'),
  (6, 'Breloom', 'common'),
  (7, 'Cynthia''s Roselia', 'common'),
  (8, 'Cynthia''s Roserade', 'common'),
  (9, 'Mow Rotom', 'common'),
  (10, 'Shaymin', 'common'),
  (11, 'Dwebble', 'common'),
  (12, 'Crustle', 'common'),
  (13, 'Fomantis', 'common'),
  (14, 'Lurantis', 'common'),
  (15, 'Team Rocket''s Blipbug', 'common'),
  (16, 'Applin', 'common'),
  (17, 'Dipplin', 'common'),
  (18, 'Hydrapple', 'common'),
  (19, 'Team Rocket''s Tarountula', 'common'),
  (20, 'Team Rocket''s Spidops', 'common'),
  (21, 'Smoliv', 'common'),
  (22, 'Dolliv', 'common'),
  (23, 'Arboliva ex', 'common'),
  (24, 'Rellor', 'common'),
  (25, 'Rabsca ex', 'common'),
  (26, 'Teal Mask Ogerpon', 'common'),
  (27, 'Growlithe', 'common'),
  (28, 'Arcanine', 'common'),
  (29, 'Ponyta', 'common'),
  (30, 'Rapidash', 'common'),
  (31, 'Team Rocket''s Moltres ex', 'common'),
  (32, 'Ethan''s Cyndaquil', 'common'),
  (33, 'Ethan''s Quilava', 'common'),
  (34, 'Ethan''s Typhlosion', 'common'),
  (35, 'Ethan''s Slugma', 'common'),
  (36, 'Ethan''s Magcargo', 'common'),
  (37, 'Team Rocket''s Houndour', 'common'),
  (38, 'Team Rocket''s Houndoom', 'common'),
  (39, 'Ethan''s Ho-Oh ex', 'common'),
  (40, 'Torchic', 'common'),
  (41, 'Combusken', 'common'),
  (42, 'Blaziken', 'common'),
  (43, 'Heat Rotom', 'common'),
  (44, 'Hearthflame Mask Ogerpon', 'common'),
  (45, 'Misty''s Psyduck', 'common'),
  (46, 'Misty''s Staryu', 'common'),
  (47, 'Misty''s Starmie', 'common'),
  (48, 'Misty''s Magikarp', 'common'),
  (49, 'Misty''s Gyarados', 'common'),
  (50, 'Misty''s Lapras', 'common'),
  (51, 'Team Rocket''s Articuno', 'common'),
  (52, 'Cynthia''s Feebas', 'common'),
  (53, 'Cynthia''s Milotic', 'common'),
  (54, 'Clamperl', 'common'),
  (55, 'Huntail', 'common'),
  (56, 'Gorebyss', 'common'),
  (57, 'Buizel', 'common'),
  (58, 'Floatzel', 'common'),
  (59, 'Snover', 'common'),
  (60, 'Abomasnow', 'common'),
  (61, 'Wash Rotom', 'common'),
  (62, 'Arrokuda', 'common'),
  (63, 'Barraskewda', 'common'),
  (64, 'Cetoddle', 'common'),
  (65, 'Cetitan ex', 'common'),
  (66, 'Dondozo ex', 'common'),
  (67, 'Wellspring Mask Ogerpon', 'common'),
  (68, 'Electabuzz', 'common'),
  (69, 'Electivire ex', 'common'),
  (70, 'Team Rocket''s Zapdos', 'common'),
  (71, 'Ethan''s Pichu', 'common'),
  (72, 'Team Rocket''s Mareep', 'common'),
  (73, 'Team Rocket''s Flaaffy', 'common'),
  (74, 'Team Rocket''s Ampharos', 'common'),
  (75, 'Electrike', 'common'),
  (76, 'Manectric', 'common'),
  (77, 'Rotom', 'common'),
  (78, 'Zeraora', 'common'),
  (79, 'Team Rocket''s Drowzee', 'common'),
  (80, 'Team Rocket''s Hypno', 'common'),
  (81, 'Team Rocket''s Mewtwo ex', 'common'),
  (82, 'Team Rocket''s Wobbuffet', 'common'),
  (83, 'Steven''s Baltoy', 'common'),
  (84, 'Steven''s Claydol', 'common'),
  (85, 'Team Rocket''s Chingling', 'common'),
  (86, 'Steven''s Carbink', 'common'),
  (87, 'Team Rocket''s Mimikyu', 'common'),
  (88, 'Team Rocket''s Dottler', 'common'),
  (89, 'Team Rocket''s Orbeetle', 'common'),
  (90, 'Mankey', 'common'),
  (91, 'Primeape', 'common'),
  (92, 'Annihilape', 'common'),
  (93, 'Ethan''s Sudowoodo', 'common'),
  (94, 'Team Rocket''s Larvitar', 'common'),
  (95, 'Team Rocket''s Pupitar', 'common'),
  (96, 'Team Rocket''s Tyranitar', 'common'),
  (97, 'Nosepass', 'common'),
  (98, 'Probopass', 'common'),
  (99, 'Meditite', 'common'),
  (100, 'Medicham', 'common'),
  (101, 'Regirock ex', 'common'),
  (102, 'Cynthia''s Gible', 'common'),
  (103, 'Cynthia''s Gabite', 'common'),
  (104, 'Cynthia''s Garchomp ex', 'common'),
  (105, 'Hippopotas', 'common'),
  (106, 'Hippowdon', 'common'),
  (107, 'Mudbray', 'common'),
  (108, 'Mudsdale', 'common'),
  (109, 'Arven''s Toedscool', 'common'),
  (110, 'Arven''s Toedscruel', 'common'),
  (111, 'Cornerstone Mask Ogerpon', 'common'),
  (112, 'Team Rocket''s Ekans', 'common'),
  (113, 'Team Rocket''s Arbok', 'common'),
  (114, 'Team Rocket''s Nidoran F', 'common'),
  (115, 'Team Rocket''s Nidorina', 'common'),
  (116, 'Team Rocket''s Nidoqueen', 'common'),
  (117, 'Team Rocket''s Nidoran M', 'common'),
  (118, 'Team Rocket''s Nidorino', 'common'),
  (119, 'Team Rocket''s Nidoking ex', 'common'),
  (120, 'Team Rocket''s Zubat', 'common'),
  (121, 'Team Rocket''s Golbat', 'common'),
  (122, 'Team Rocket''s Crobat ex', 'common'),
  (123, 'Team Rocket''s Grimer', 'common'),
  (124, 'Team Rocket''s Muk', 'common'),
  (125, 'Team Rocket''s Koffing', 'common'),
  (126, 'Team Rocket''s Weezing', 'common'),
  (127, 'Team Rocket''s Murkrow', 'common'),
  (128, 'Team Rocket''s Sneasel', 'common'),
  (129, 'Cynthia''s Spiritomb', 'common'),
  (130, 'Marnie''s Purrloin', 'common'),
  (131, 'Marnie''s Liepard', 'common'),
  (132, 'Marnie''s Scraggy', 'common'),
  (133, 'Marnie''s Scrafty', 'common'),
  (134, 'Marnie''s Impidimp', 'common'),
  (135, 'Marnie''s Morgrem', 'common'),
  (136, 'Marnie''s Grimmsnarl ex', 'common'),
  (137, 'Marnie''s Morpeko', 'common'),
  (138, 'Arven''s Maschiff', 'common'),
  (139, 'Arven''s Mabosstiff ex', 'common'),
  (140, 'Forretress', 'common'),
  (141, 'Skarmory', 'common'),
  (142, 'Steven''s Skarmory', 'common'),
  (143, 'Steven''s Beldum', 'common'),
  (144, 'Steven''s Metang', 'common'),
  (145, 'Steven''s Metagross ex', 'common'),
  (146, 'Zamazenta', 'common'),
  (147, 'Team Rocket''s Rattata', 'common'),
  (148, 'Team Rocket''s Raticate', 'common'),
  (149, 'Team Rocket''s Meowth', 'common'),
  (150, 'Team Rocket''s Persian ex', 'common'),
  (151, 'Kangaskhan', 'common'),
  (152, 'Tauros', 'common'),
  (153, 'Team Rocket''s Porygon', 'common'),
  (154, 'Team Rocket''s Porygon2', 'common'),
  (155, 'Team Rocket''s Porygon-Z', 'common'),
  (156, 'Taillow', 'common'),
  (157, 'Swellow', 'common'),
  (158, 'Arven''s Skwovet', 'common'),
  (159, 'Arven''s Greedent', 'common'),
  (160, 'Squawkabilly', 'common'),
  (161, 'Arven''s Sandwich', 'common'),
  (162, 'Cynthia''s Power Weight', 'common'),
  (163, 'Emcee''s Hype', 'common'),
  (164, 'Energy Recycler', 'common'),
  (165, 'Ethan''s Adventure', 'common'),
  (166, 'Granite Cave', 'common'),
  (167, 'Judge', 'common'),
  (168, 'Sacred Ash', 'common'),
  (169, 'Spikemuth Gym', 'common'),
  (170, 'Team Rocket''s Archer', 'common'),
  (171, 'Team Rocket''s Ariana', 'common'),
  (172, 'Team Rocket''s Bother-Bot', 'common'),
  (173, 'Team Rocket''s Factory', 'common'),
  (174, 'Team Rocket''s Giovanni', 'common'),
  (175, 'Team Rocket''s Great Ball', 'common'),
  (176, 'Team Rocket''s Petrel', 'common'),
  (177, 'Team Rocket''s Proton', 'common'),
  (178, 'Team Rocket''s Transceiver', 'common'),
  (179, 'Team Rocket''s Venture Bomb', 'common'),
  (180, 'Team Rocket''s Watchtower', 'common'),
  (181, 'TM Machine', 'common'),
  (182, 'Team Rocket''s Energy', 'common'),
  (183, 'Yanma', 'illustration_rare'),
  (184, 'Cynthia''s Roserade', 'illustration_rare'),
  (185, 'Shaymin', 'illustration_rare'),
  (186, 'Crustle', 'illustration_rare'),
  (187, 'Team Rocket''s Spidops', 'illustration_rare'),
  (188, 'Hydrapple', 'illustration_rare'),
  (189, 'Rapidash', 'illustration_rare'),
  (190, 'Ethan''s Typhlosion', 'illustration_rare'),
  (191, 'Team Rocket''s Houndoom', 'illustration_rare'),
  (192, 'Blaziken', 'illustration_rare'),
  (193, 'Misty''s Psyduck', 'illustration_rare'),
  (194, 'Misty''s Lapras', 'illustration_rare'),
  (195, 'Clamperl', 'illustration_rare'),
  (196, 'Electrike', 'illustration_rare'),
  (197, 'Rotom', 'illustration_rare'),
  (198, 'Team Rocket''s Orbeetle', 'illustration_rare'),
  (199, 'Team Rocket''s Weezing', 'illustration_rare'),
  (200, 'Team Rocket''s Murkrow', 'illustration_rare'),
  (201, 'Zamazenta', 'illustration_rare'),
  (202, 'Team Rocket''s Raticate', 'illustration_rare'),
  (203, 'Team Rocket''s Meowth', 'illustration_rare'),
  (204, 'Kangaskhan', 'illustration_rare'),
  (205, 'Arven''s Greedent', 'illustration_rare'),
  (206, 'Yanmega ex', 'ultra_rare'),
  (207, 'Arboliva ex', 'ultra_rare'),
  (208, 'Team Rocket''s Moltres ex', 'ultra_rare'),
  (209, 'Ethan''s Ho-Oh ex', 'ultra_rare'),
  (210, 'Cetitan ex', 'ultra_rare'),
  (211, 'Dondozo ex', 'ultra_rare'),
  (212, 'Electivire ex', 'ultra_rare'),
  (213, 'Team Rocket''s Mewtwo ex', 'ultra_rare'),
  (214, 'Regirock ex', 'ultra_rare'),
  (215, 'Cynthia''s Garchomp ex', 'ultra_rare'),
  (216, 'Team Rocket''s Nidoking ex', 'ultra_rare'),
  (217, 'Team Rocket''s Crobat ex', 'ultra_rare'),
  (218, 'Arven''s Mabosstiff ex', 'ultra_rare'),
  (219, 'Team Rocket''s Persian ex', 'ultra_rare'),
  (220, 'Emcee''s Hype', 'ultra_rare'),
  (221, 'Ethan''s Adventure', 'ultra_rare'),
  (222, 'Judge', 'ultra_rare'),
  (223, 'Team Rocket''s Archer', 'ultra_rare'),
  (224, 'Team Rocket''s Ariana', 'ultra_rare'),
  (225, 'Team Rocket''s Giovanni', 'ultra_rare'),
  (226, 'Team Rocket''s Petrel', 'ultra_rare'),
  (227, 'Team Rocket''s Proton', 'ultra_rare'),
  (228, 'Yanmega ex', 'special_illustration_rare'),
  (229, 'Team Rocket''s Moltres ex', 'special_illustration_rare'),
  (230, 'Ethan''s Ho-Oh ex', 'special_illustration_rare'),
  (231, 'Team Rocket''s Mewtwo ex', 'special_illustration_rare'),
  (232, 'Cynthia''s Garchomp ex', 'special_illustration_rare'),
  (233, 'Team Rocket''s Nidoking ex', 'special_illustration_rare'),
  (234, 'Team Rocket''s Crobat ex', 'special_illustration_rare'),
  (235, 'Arven''s Mabosstiff ex', 'special_illustration_rare'),
  (236, 'Ethan''s Adventure', 'special_illustration_rare'),
  (237, 'Team Rocket''s Ariana', 'special_illustration_rare'),
  (238, 'Team Rocket''s Giovanni', 'special_illustration_rare'),
  (239, 'Ethan''s Ho-Oh ex', 'mega_hyper_rare'),
  (240, 'Team Rocket''s Mewtwo ex', 'mega_hyper_rare'),
  (241, 'Cynthia''s Garchomp ex', 'mega_hyper_rare'),
  (242, 'Team Rocket''s Crobat ex', 'mega_hyper_rare'),
  (243, 'Jamming Tower', 'ultra_rare'),
  (244, 'Levincia', 'ultra_rare')
  ) as v(number, name, rarity)
  returning id, rarity
)
insert into card_variants (card_id, variant, price_sek, stock)
select ic.id, x.variant,
  case
      when ic.rarity = 'common' and x.variant = 'holo' then 4
      when ic.rarity = 'common' then 2
      when ic.rarity = 'illustration_rare' then 15
      when ic.rarity = 'ultra_rare' then 20
      when ic.rarity = 'special_illustration_rare' then 0
      when ic.rarity = 'mega_hyper_rare' then 0
    else 0
  end as price_sek,
  0 as stock
from inserted_cards ic
cross join (values ('normal'), ('holo')) as x(variant);
