-- Seed data for Mega Evolution > Mega Evolution, 188 cards.
-- Run this once in the Supabase SQL editor after schema.sql AND
-- set_visibility.sql (this seed sets the new set to hidden by default).
-- Stock defaults to 0 for every variant -- cards stay greyed out on the
-- storefront (and the whole set stays hidden) until you set real stock
-- numbers and flip visibility on in /admin. Prices are rough starting
-- defaults by rarity tier (SEK) -- edit any of them later.

with s as (
  insert into sets (category_slug, category_name, slug, name, is_visible)
  values ('mega-evolution', 'Mega Evolution', 'base-set', 'Mega Evolution', false)
  returning id
),
inserted_cards as (
  insert into cards (set_id, number, name, rarity)
  select s.id, v.number, v.name, v.rarity
  from s, (values
  (1, 'Bulbasaur', 'common'),
  (2, 'Ivysaur', 'common'),
  (3, 'Mega Venusaur ex', 'common'),
  (4, 'Exeggcute', 'common'),
  (5, 'Exeggutor', 'common'),
  (6, 'Tangela', 'common'),
  (7, 'Tangrowth', 'common'),
  (8, 'Chikorita', 'common'),
  (9, 'Bayleef', 'common'),
  (10, 'Meganium', 'common'),
  (11, 'Shuckle', 'common'),
  (12, 'Celebi', 'common'),
  (13, 'Seedot', 'common'),
  (14, 'Nuzleaf', 'common'),
  (15, 'Shiftry', 'common'),
  (16, 'Nincada', 'common'),
  (17, 'Ninjask', 'common'),
  (18, 'Dhelmise', 'common'),
  (19, 'Vulpix', 'common'),
  (20, 'Ninetales', 'common'),
  (21, 'Numel', 'common'),
  (22, 'Mega Camerupt ex', 'common'),
  (23, 'Litleo', 'common'),
  (24, 'Pyroar', 'common'),
  (25, 'Volcanion', 'common'),
  (26, 'Scorbunny', 'common'),
  (27, 'Raboot', 'common'),
  (28, 'Cinderace', 'common'),
  (29, 'Sizzlipede', 'common'),
  (30, 'Centiskorch', 'common'),
  (31, 'Chi-Yu', 'common'),
  (32, 'Mantine', 'common'),
  (33, 'Corphish', 'common'),
  (34, 'Kyogre', 'common'),
  (35, 'Snover', 'common'),
  (36, 'Mega Abomasnow ex', 'common'),
  (37, 'Clauncher', 'common'),
  (38, 'Clawitzer', 'common'),
  (39, 'Sobble', 'common'),
  (40, 'Drizzile', 'common'),
  (41, 'Inteleon', 'common'),
  (42, 'Snom', 'common'),
  (43, 'Frosmoth', 'common'),
  (44, 'Eiscue', 'common'),
  (45, 'Magnemite', 'common'),
  (46, 'Magneton', 'common'),
  (47, 'Magnezone', 'common'),
  (48, 'Raikou', 'common'),
  (49, 'Electrike', 'common'),
  (50, 'Mega Manectric ex', 'common'),
  (51, 'Pachirisu', 'common'),
  (52, 'Helioptile', 'common'),
  (53, 'Heliolisk', 'common'),
  (54, 'Abra', 'common'),
  (55, 'Kadabra', 'common'),
  (56, 'Alakazam', 'common'),
  (57, 'Jynx', 'common'),
  (58, 'Ralts', 'common'),
  (59, 'Kirlia', 'common'),
  (60, 'Mega Gardevoir ex', 'common'),
  (61, 'Shedinja', 'common'),
  (62, 'Spoink', 'common'),
  (63, 'Grumpig', 'common'),
  (64, 'Xerneas', 'common'),
  (65, 'Greavard', 'common'),
  (66, 'Houndstone', 'common'),
  (67, 'Gimmighoul', 'common'),
  (68, 'Sandshrew', 'common'),
  (69, 'Sandslash', 'common'),
  (70, 'Onix', 'common'),
  (71, 'Tyrogue', 'common'),
  (72, 'Makuhita', 'common'),
  (73, 'Hariyama', 'common'),
  (74, 'Lunatone', 'common'),
  (75, 'Solrock', 'common'),
  (76, 'Riolu', 'common'),
  (77, 'Mega Lucario ex', 'common'),
  (78, 'Croagunk', 'common'),
  (79, 'Toxicroak', 'common'),
  (80, 'Marshadow', 'common'),
  (81, 'Stonjourner', 'common'),
  (82, 'Nacli', 'common'),
  (83, 'Naclstack', 'common'),
  (84, 'Garganacl', 'common'),
  (85, 'Crawdaunt', 'common'),
  (86, 'Mega Absol ex', 'common'),
  (87, 'Spiritomb', 'common'),
  (88, 'Yveltal', 'common'),
  (89, 'Nickit', 'common'),
  (90, 'Thievul', 'common'),
  (91, 'Shroodle', 'common'),
  (92, 'Grafaiai', 'common'),
  (93, 'Steelix', 'common'),
  (94, 'Mega Mawile ex', 'common'),
  (95, 'Dialga', 'common'),
  (96, 'Tinkatink', 'common'),
  (97, 'Tinkatuff', 'common'),
  (98, 'Tinkaton', 'common'),
  (99, 'Gholdengo', 'common'),
  (100, 'Mega Latias ex', 'common'),
  (101, 'Latios', 'common'),
  (102, 'Spearow', 'common'),
  (103, 'Fearow', 'common'),
  (104, 'Mega Kangaskhan ex', 'common'),
  (105, 'Delibird', 'common'),
  (106, 'Miltank', 'common'),
  (107, 'Buneary', 'common'),
  (108, 'Lopunny', 'common'),
  (109, 'Yungoos', 'common'),
  (110, 'Gumshoos', 'common'),
  (111, 'Stufful', 'common'),
  (112, 'Bewear', 'common'),
  (113, 'Acerola''s Mischief', 'common'),
  (114, 'Boss''s Orders', 'common'),
  (115, 'Energy Switch', 'common'),
  (116, 'Fighting Gong', 'common'),
  (117, 'Forest of Vitality', 'common'),
  (118, 'Iron Defender', 'common'),
  (119, 'Lillie''s Determination', 'common'),
  (120, 'Lt. Surge''s Bargain', 'common'),
  (121, 'Mega Signal', 'common'),
  (122, 'Mystery Garden', 'common'),
  (123, 'Pokemon Center Lady', 'common'),
  (124, 'Premium Power Pro', 'common'),
  (125, 'Rare Candy', 'common'),
  (126, 'Repel', 'common'),
  (127, 'Risky Ruins', 'common'),
  (128, 'Strange Timepiece', 'common'),
  (129, 'Surfing Beach', 'common'),
  (130, 'Switch', 'common'),
  (131, 'Ultra Ball', 'common'),
  (132, 'Wally''s Compassion', 'common'),
  (133, 'Bulbasaur', 'illustration_rare'),
  (134, 'Ivysaur', 'illustration_rare'),
  (135, 'Exeggutor', 'illustration_rare'),
  (136, 'Shuckle', 'illustration_rare'),
  (137, 'Ninjask', 'illustration_rare'),
  (138, 'Vulpix', 'illustration_rare'),
  (139, 'Litleo', 'illustration_rare'),
  (140, 'Snover', 'illustration_rare'),
  (141, 'Clawitzer', 'illustration_rare'),
  (142, 'Inteleon', 'illustration_rare'),
  (143, 'Helioptile', 'illustration_rare'),
  (144, 'Shedinja', 'illustration_rare'),
  (145, 'Houndstone', 'illustration_rare'),
  (146, 'Marshadow', 'illustration_rare'),
  (147, 'Garganacl', 'illustration_rare'),
  (148, 'Spiritomb', 'illustration_rare'),
  (149, 'Shroodle', 'illustration_rare'),
  (150, 'Steelix', 'illustration_rare'),
  (151, 'Spearow', 'illustration_rare'),
  (152, 'Delibird', 'illustration_rare'),
  (153, 'Gumshoos', 'illustration_rare'),
  (154, 'Stufful', 'illustration_rare'),
  (155, 'Mega Venusaur ex', 'ultra_rare'),
  (156, 'Mega Camerupt ex', 'ultra_rare'),
  (157, 'Mega Abomasnow ex', 'ultra_rare'),
  (158, 'Mega Manectric ex', 'ultra_rare'),
  (159, 'Mega Gardevoir ex', 'ultra_rare'),
  (160, 'Mega Lucario ex', 'ultra_rare'),
  (161, 'Mega Absol ex', 'ultra_rare'),
  (162, 'Mega Mawile ex', 'ultra_rare'),
  (163, 'Mega Latias ex', 'ultra_rare'),
  (164, 'Mega Kangaskhan ex', 'ultra_rare'),
  (165, 'Acerola''s Mischief', 'ultra_rare'),
  (166, 'Air Balloon', 'ultra_rare'),
  (167, 'Buddy-Buddy Poffin', 'ultra_rare'),
  (168, 'Fighting Gong', 'ultra_rare'),
  (169, 'Lillie''s Determination', 'ultra_rare'),
  (170, 'Lt. Surge''s Bargain', 'ultra_rare'),
  (171, 'Mega Signal', 'ultra_rare'),
  (172, 'Mystery Garden', 'ultra_rare'),
  (173, 'Night Stretcher', 'ultra_rare'),
  (174, 'Premium Power Pro', 'ultra_rare'),
  (175, 'Rare Candy', 'ultra_rare'),
  (176, 'Wally''s Compassion', 'ultra_rare'),
  (177, 'Mega Venusaur ex', 'special_illustration_rare'),
  (178, 'Mega Gardevoir ex', 'special_illustration_rare'),
  (179, 'Mega Lucario ex', 'special_illustration_rare'),
  (180, 'Mega Absol ex', 'special_illustration_rare'),
  (181, 'Mega Latias ex', 'special_illustration_rare'),
  (182, 'Mega Kangaskhan ex', 'special_illustration_rare'),
  (183, 'Acerola''s Mischief', 'special_illustration_rare'),
  (184, 'Lillie''s Determination', 'special_illustration_rare'),
  (185, 'Lt. Surge''s Bargain', 'special_illustration_rare'),
  (186, 'Wally''s Compassion', 'special_illustration_rare'),
  (187, 'Mega Gardevoir ex', 'mega_hyper_rare'),
  (188, 'Mega Lucario ex', 'mega_hyper_rare')
  ) as v(number, name, rarity)
  returning id, rarity
)
insert into card_variants (card_id, variant, price_sek, stock)
select ic.id, x.variant,
  case
      when ic.rarity = 'common' and x.variant = 'holo' then 4
      when ic.rarity = 'common' then 2
      when ic.rarity = 'illustration_rare' then 15
      when ic.rarity = 'ultra_rare' then 20
      when ic.rarity = 'special_illustration_rare' then 0
      when ic.rarity = 'mega_hyper_rare' then 0
    else 0
  end as price_sek,
  0 as stock
from inserted_cards ic
cross join (values ('normal'), ('holo')) as x(variant);
