-- Katalogimport: Diamond & Pearl (8 set)
-- Endast katalogdata (lager 0, pris 0) för portfölj/önskelista-funktionen.

-- Set: Diamond & Pearl (dp1) -- 2007/05/01
insert into sets (category_slug, category_name, slug, name, is_visible)
  values ('diamond-pearl', 'Diamond & Pearl', 'diamond-pearl', 'Diamond & Pearl', false)
  on conflict (slug) do nothing;

with s as (select id from sets where slug = 'diamond-pearl'),
inserted_cards as (
  insert into cards (set_id, number, name, rarity, image_url, pokemon_type)
  select s.id, v.number, v.name, v.rarity, v.image_url, v.pokemon_type
  from s, (values
    (1, 'Dialga', 'rare', 'https://images.pokemontcg.io/dp1/1_hires.png', 'metal'),
    (2, 'Dusknoir', 'rare', 'https://images.pokemontcg.io/dp1/2_hires.png', 'psychic'),
    (3, 'Electivire', 'rare', 'https://images.pokemontcg.io/dp1/3_hires.png', 'lightning'),
    (4, 'Empoleon', 'rare', 'https://images.pokemontcg.io/dp1/4_hires.png', 'water'),
    (5, 'Infernape', 'rare', 'https://images.pokemontcg.io/dp1/5_hires.png', 'fire'),
    (6, 'Lucario', 'rare', 'https://images.pokemontcg.io/dp1/6_hires.png', 'fighting'),
    (7, 'Luxray', 'rare', 'https://images.pokemontcg.io/dp1/7_hires.png', 'lightning'),
    (8, 'Magnezone', 'rare', 'https://images.pokemontcg.io/dp1/8_hires.png', 'metal'),
    (9, 'Manaphy', 'rare', 'https://images.pokemontcg.io/dp1/9_hires.png', 'water'),
    (10, 'Mismagius', 'rare', 'https://images.pokemontcg.io/dp1/10_hires.png', 'psychic'),
    (11, 'Palkia', 'rare', 'https://images.pokemontcg.io/dp1/11_hires.png', 'water'),
    (12, 'Rhyperior', 'rare', 'https://images.pokemontcg.io/dp1/12_hires.png', 'fighting'),
    (13, 'Roserade', 'rare', 'https://images.pokemontcg.io/dp1/13_hires.png', 'grass'),
    (14, 'Shiftry', 'rare', 'https://images.pokemontcg.io/dp1/14_hires.png', 'darkness'),
    (15, 'Skuntank', 'rare', 'https://images.pokemontcg.io/dp1/15_hires.png', 'darkness'),
    (16, 'Staraptor', 'rare', 'https://images.pokemontcg.io/dp1/16_hires.png', 'colorless'),
    (17, 'Torterra', 'rare', 'https://images.pokemontcg.io/dp1/17_hires.png', 'grass'),
    (18, 'Azumarill', 'rare', 'https://images.pokemontcg.io/dp1/18_hires.png', 'water'),
    (19, 'Beautifly', 'rare', 'https://images.pokemontcg.io/dp1/19_hires.png', 'grass'),
    (20, 'Bibarel', 'rare', 'https://images.pokemontcg.io/dp1/20_hires.png', 'colorless'),
    (21, 'Carnivine', 'rare', 'https://images.pokemontcg.io/dp1/21_hires.png', 'grass'),
    (22, 'Clefable', 'rare', 'https://images.pokemontcg.io/dp1/22_hires.png', 'colorless'),
    (23, 'Drapion', 'rare', 'https://images.pokemontcg.io/dp1/23_hires.png', 'psychic'),
    (24, 'Drifblim', 'rare', 'https://images.pokemontcg.io/dp1/24_hires.png', 'psychic'),
    (25, 'Dustox', 'rare', 'https://images.pokemontcg.io/dp1/25_hires.png', 'grass'),
    (26, 'Floatzel', 'rare', 'https://images.pokemontcg.io/dp1/26_hires.png', 'water'),
    (27, 'Gengar', 'rare', 'https://images.pokemontcg.io/dp1/27_hires.png', 'psychic'),
    (28, 'Heracross', 'rare', 'https://images.pokemontcg.io/dp1/28_hires.png', 'grass'),
    (29, 'Hippowdon', 'rare', 'https://images.pokemontcg.io/dp1/29_hires.png', 'fighting'),
    (30, 'Lopunny', 'rare', 'https://images.pokemontcg.io/dp1/30_hires.png', 'colorless'),
    (31, 'Machamp', 'rare', 'https://images.pokemontcg.io/dp1/31_hires.png', 'fighting'),
    (32, 'Medicham', 'rare', 'https://images.pokemontcg.io/dp1/32_hires.png', 'fighting'),
    (33, 'Munchlax', 'rare', 'https://images.pokemontcg.io/dp1/33_hires.png', 'colorless'),
    (34, 'Noctowl', 'rare', 'https://images.pokemontcg.io/dp1/34_hires.png', 'colorless'),
    (35, 'Pachirisu', 'rare', 'https://images.pokemontcg.io/dp1/35_hires.png', 'lightning'),
    (36, 'Purugly', 'rare', 'https://images.pokemontcg.io/dp1/36_hires.png', 'colorless'),
    (37, 'Snorlax', 'rare', 'https://images.pokemontcg.io/dp1/37_hires.png', 'colorless'),
    (38, 'Steelix', 'rare', 'https://images.pokemontcg.io/dp1/38_hires.png', 'metal'),
    (39, 'Vespiquen', 'rare', 'https://images.pokemontcg.io/dp1/39_hires.png', 'grass'),
    (40, 'Weavile', 'rare', 'https://images.pokemontcg.io/dp1/40_hires.png', 'darkness'),
    (41, 'Wobbuffet', 'rare', 'https://images.pokemontcg.io/dp1/41_hires.png', 'psychic'),
    (42, 'Wynaut', 'rare', 'https://images.pokemontcg.io/dp1/42_hires.png', 'psychic'),
    (43, 'Budew', 'common', 'https://images.pokemontcg.io/dp1/43_hires.png', 'grass'),
    (44, 'Cascoon', 'common', 'https://images.pokemontcg.io/dp1/44_hires.png', 'grass'),
    (45, 'Cherrim', 'common', 'https://images.pokemontcg.io/dp1/45_hires.png', 'grass'),
    (46, 'Drifloon', 'common', 'https://images.pokemontcg.io/dp1/46_hires.png', 'psychic'),
    (47, 'Dusclops', 'common', 'https://images.pokemontcg.io/dp1/47_hires.png', 'psychic'),
    (48, 'Elekid', 'common', 'https://images.pokemontcg.io/dp1/48_hires.png', 'lightning'),
    (49, 'Grotle', 'common', 'https://images.pokemontcg.io/dp1/49_hires.png', 'grass'),
    (50, 'Haunter', 'common', 'https://images.pokemontcg.io/dp1/50_hires.png', 'psychic'),
    (51, 'Hippopotas', 'common', 'https://images.pokemontcg.io/dp1/51_hires.png', 'fighting'),
    (52, 'Luxio', 'common', 'https://images.pokemontcg.io/dp1/52_hires.png', 'lightning'),
    (53, 'Machoke', 'common', 'https://images.pokemontcg.io/dp1/53_hires.png', 'fighting'),
    (54, 'Magneton', 'common', 'https://images.pokemontcg.io/dp1/54_hires.png', 'metal'),
    (55, 'Mantyke', 'common', 'https://images.pokemontcg.io/dp1/55_hires.png', 'water'),
    (56, 'Monferno', 'common', 'https://images.pokemontcg.io/dp1/56_hires.png', 'fire'),
    (57, 'Nuzleaf', 'common', 'https://images.pokemontcg.io/dp1/57_hires.png', 'darkness'),
    (58, 'Prinplup', 'common', 'https://images.pokemontcg.io/dp1/58_hires.png', 'water'),
    (59, 'Rapidash', 'common', 'https://images.pokemontcg.io/dp1/59_hires.png', 'fire'),
    (60, 'Rhydon', 'common', 'https://images.pokemontcg.io/dp1/60_hires.png', 'fighting'),
    (61, 'Riolu', 'common', 'https://images.pokemontcg.io/dp1/61_hires.png', 'fighting'),
    (62, 'Seaking', 'common', 'https://images.pokemontcg.io/dp1/62_hires.png', 'water'),
    (63, 'Silcoon', 'common', 'https://images.pokemontcg.io/dp1/63_hires.png', 'grass'),
    (64, 'Staravia', 'common', 'https://images.pokemontcg.io/dp1/64_hires.png', 'colorless'),
    (65, 'Unown [A]', 'common', 'https://images.pokemontcg.io/dp1/65_hires.png', 'psychic'),
    (66, 'Unown [B]', 'common', 'https://images.pokemontcg.io/dp1/66_hires.png', 'psychic'),
    (67, 'Unown [C]', 'common', 'https://images.pokemontcg.io/dp1/67_hires.png', 'psychic'),
    (68, 'Unown [D]', 'common', 'https://images.pokemontcg.io/dp1/68_hires.png', 'psychic'),
    (69, 'Azurill', 'common', 'https://images.pokemontcg.io/dp1/69_hires.png', 'colorless'),
    (70, 'Bidoof', 'common', 'https://images.pokemontcg.io/dp1/70_hires.png', 'colorless'),
    (71, 'Bonsly', 'common', 'https://images.pokemontcg.io/dp1/71_hires.png', 'fighting'),
    (72, 'Buizel', 'common', 'https://images.pokemontcg.io/dp1/72_hires.png', 'water'),
    (73, 'Buneary', 'common', 'https://images.pokemontcg.io/dp1/73_hires.png', 'colorless'),
    (74, 'Chatot', 'common', 'https://images.pokemontcg.io/dp1/74_hires.png', 'colorless'),
    (75, 'Cherubi', 'common', 'https://images.pokemontcg.io/dp1/75_hires.png', 'grass'),
    (76, 'Chimchar', 'common', 'https://images.pokemontcg.io/dp1/76_hires.png', 'fire'),
    (77, 'Clefairy', 'common', 'https://images.pokemontcg.io/dp1/77_hires.png', 'colorless'),
    (78, 'Cleffa', 'common', 'https://images.pokemontcg.io/dp1/78_hires.png', 'colorless'),
    (79, 'Combee', 'common', 'https://images.pokemontcg.io/dp1/79_hires.png', 'grass'),
    (80, 'Duskull', 'common', 'https://images.pokemontcg.io/dp1/80_hires.png', 'psychic'),
    (81, 'Electabuzz', 'common', 'https://images.pokemontcg.io/dp1/81_hires.png', 'lightning'),
    (82, 'Gastly', 'common', 'https://images.pokemontcg.io/dp1/82_hires.png', 'psychic'),
    (83, 'Glameow', 'common', 'https://images.pokemontcg.io/dp1/83_hires.png', 'colorless'),
    (84, 'Goldeen', 'common', 'https://images.pokemontcg.io/dp1/84_hires.png', 'water'),
    (85, 'Hoothoot', 'common', 'https://images.pokemontcg.io/dp1/85_hires.png', 'colorless'),
    (86, 'Machop', 'common', 'https://images.pokemontcg.io/dp1/86_hires.png', 'fighting'),
    (87, 'Magnemite', 'common', 'https://images.pokemontcg.io/dp1/87_hires.png', 'metal'),
    (88, 'Marill', 'common', 'https://images.pokemontcg.io/dp1/88_hires.png', 'water'),
    (89, 'Meditite', 'common', 'https://images.pokemontcg.io/dp1/89_hires.png', 'fighting'),
    (90, 'Mime Jr.', 'common', 'https://images.pokemontcg.io/dp1/90_hires.png', 'psychic'),
    (91, 'Misdreavus', 'common', 'https://images.pokemontcg.io/dp1/91_hires.png', 'psychic'),
    (92, 'Onix', 'common', 'https://images.pokemontcg.io/dp1/92_hires.png', 'fighting'),
    (93, 'Piplup', 'common', 'https://images.pokemontcg.io/dp1/93_hires.png', 'water'),
    (94, 'Ponyta', 'common', 'https://images.pokemontcg.io/dp1/94_hires.png', 'fire'),
    (95, 'Rhyhorn', 'common', 'https://images.pokemontcg.io/dp1/95_hires.png', 'fighting'),
    (96, 'Roselia', 'common', 'https://images.pokemontcg.io/dp1/96_hires.png', 'grass'),
    (97, 'Seedot', 'common', 'https://images.pokemontcg.io/dp1/97_hires.png', 'grass'),
    (98, 'Shinx', 'common', 'https://images.pokemontcg.io/dp1/98_hires.png', 'lightning'),
    (99, 'Skorupi', 'common', 'https://images.pokemontcg.io/dp1/99_hires.png', 'psychic'),
    (100, 'Sneasel', 'common', 'https://images.pokemontcg.io/dp1/100_hires.png', 'darkness'),
    (101, 'Starly', 'common', 'https://images.pokemontcg.io/dp1/101_hires.png', 'colorless'),
    (102, 'Stunky', 'common', 'https://images.pokemontcg.io/dp1/102_hires.png', 'darkness'),
    (103, 'Turtwig', 'common', 'https://images.pokemontcg.io/dp1/103_hires.png', 'grass'),
    (104, 'Wurmple', 'common', 'https://images.pokemontcg.io/dp1/104_hires.png', 'grass'),
    (105, 'Double Full Heal', 'common', 'https://images.pokemontcg.io/dp1/105_hires.png', NULL),
    (106, 'Energy Restore', 'common', 'https://images.pokemontcg.io/dp1/106_hires.png', NULL),
    (107, 'Energy Switch', 'common', 'https://images.pokemontcg.io/dp1/107_hires.png', NULL),
    (108, 'Night Pokémon Center', 'common', 'https://images.pokemontcg.io/dp1/108_hires.png', NULL),
    (109, 'PlusPower', 'common', 'https://images.pokemontcg.io/dp1/109_hires.png', NULL),
    (110, 'Poké Ball', 'common', 'https://images.pokemontcg.io/dp1/110_hires.png', NULL),
    (111, 'Pokédex HANDY910is', 'common', 'https://images.pokemontcg.io/dp1/111_hires.png', NULL),
    (112, 'Professor Rowan', 'common', 'https://images.pokemontcg.io/dp1/112_hires.png', NULL),
    (113, 'Rival', 'common', 'https://images.pokemontcg.io/dp1/113_hires.png', NULL),
    (114, 'Speed Stadium', 'common', 'https://images.pokemontcg.io/dp1/114_hires.png', NULL),
    (115, 'Super Scoop Up', 'common', 'https://images.pokemontcg.io/dp1/115_hires.png', NULL),
    (116, 'Warp Point', 'common', 'https://images.pokemontcg.io/dp1/116_hires.png', NULL),
    (117, 'Energy Search', 'common', 'https://images.pokemontcg.io/dp1/117_hires.png', NULL),
    (118, 'Potion', 'common', 'https://images.pokemontcg.io/dp1/118_hires.png', NULL),
    (119, 'Switch', 'common', 'https://images.pokemontcg.io/dp1/119_hires.png', NULL),
    (120, 'Empoleon LV.X', 'ultra_rare', 'https://images.pokemontcg.io/dp1/120_hires.png', 'water'),
    (121, 'Infernape LV.X', 'ultra_rare', 'https://images.pokemontcg.io/dp1/121_hires.png', 'fire'),
    (122, 'Torterra LV.X', 'ultra_rare', 'https://images.pokemontcg.io/dp1/122_hires.png', 'grass'),
    (123, 'Grass Energy', 'common', 'https://images.pokemontcg.io/dp1/123_hires.png', NULL),
    (124, 'Fire Energy', 'common', 'https://images.pokemontcg.io/dp1/124_hires.png', NULL),
    (125, 'Water Energy', 'common', 'https://images.pokemontcg.io/dp1/125_hires.png', NULL),
    (126, 'Lightning Energy', 'common', 'https://images.pokemontcg.io/dp1/126_hires.png', NULL),
    (127, 'Psychic Energy', 'common', 'https://images.pokemontcg.io/dp1/127_hires.png', NULL),
    (128, 'Fighting Energy', 'common', 'https://images.pokemontcg.io/dp1/128_hires.png', NULL),
    (129, 'Darkness Energy', 'common', 'https://images.pokemontcg.io/dp1/129_hires.png', NULL),
    (130, 'Metal Energy', 'common', 'https://images.pokemontcg.io/dp1/130_hires.png', NULL)
  ) as v(number, name, rarity, image_url, pokemon_type)
  on conflict (set_id, number) do nothing
  returning id, rarity
)
insert into card_variants (card_id, variant, price_sek, stock)
select ic.id, x.variant, 0, 0
from inserted_cards ic
cross join lateral (
  select case when ic.rarity = 'rare' then 'holo' else 'normal' end as variant
  union all
  select 'reverse_holo' where ic.rarity in ('common','rare')
) as x(variant)
on conflict (card_id, variant) do nothing;

-- Set: DP Black Star Promos (dpp) -- 2007/05/01
insert into sets (category_slug, category_name, slug, name, is_visible)
  values ('diamond-pearl', 'Diamond & Pearl', 'dp-black-star-promos', 'DP Black Star Promos', false)
  on conflict (slug) do nothing;

with s as (select id from sets where slug = 'dp-black-star-promos'),
inserted_cards as (
  insert into cards (set_id, number, name, rarity, image_url, pokemon_type)
  select s.id, v.number, v.name, v.rarity, v.image_url, v.pokemon_type
  from s, (values
    (501001, 'Turtwig', 'promo', 'https://images.pokemontcg.io/dpp/DP01_hires.png', 'grass'),
    (501002, 'Chimchar', 'promo', 'https://images.pokemontcg.io/dpp/DP02_hires.png', 'fire'),
    (501003, 'Piplup', 'promo', 'https://images.pokemontcg.io/dpp/DP03_hires.png', 'water'),
    (501004, 'Pachirisu', 'promo', 'https://images.pokemontcg.io/dpp/DP04_hires.png', 'lightning'),
    (501005, 'Tropical Wind', 'promo', 'https://images.pokemontcg.io/dpp/DP05_hires.png', NULL),
    (501006, 'Buneary', 'promo', 'https://images.pokemontcg.io/dpp/DP06_hires.png', 'colorless'),
    (501007, 'Cranidos', 'promo', 'https://images.pokemontcg.io/dpp/DP07_hires.png', 'fighting'),
    (501008, 'Shieldon', 'promo', 'https://images.pokemontcg.io/dpp/DP08_hires.png', 'metal'),
    (501009, 'Torterra LV.X', 'promo', 'https://images.pokemontcg.io/dpp/DP09_hires.png', 'grass'),
    (501010, 'Infernape LV.X', 'promo', 'https://images.pokemontcg.io/dpp/DP10_hires.png', 'fire'),
    (501011, 'Empoleon LV.X', 'promo', 'https://images.pokemontcg.io/dpp/DP11_hires.png', 'water'),
    (501012, 'Lucario LV.X', 'promo', 'https://images.pokemontcg.io/dpp/DP12_hires.png', 'fighting'),
    (501013, 'Buizel', 'promo', 'https://images.pokemontcg.io/dpp/DP13_hires.png', 'water'),
    (501014, 'Chatot', 'promo', 'https://images.pokemontcg.io/dpp/DP14_hires.png', 'colorless'),
    (501015, 'Shinx', 'promo', 'https://images.pokemontcg.io/dpp/DP15_hires.png', 'lightning'),
    (501016, 'Pikachu', 'promo', 'https://images.pokemontcg.io/dpp/DP16_hires.png', 'lightning'),
    (501017, 'Dialga LV.X', 'promo', 'https://images.pokemontcg.io/dpp/DP17_hires.png', 'metal'),
    (501018, 'Palkia LV.X', 'promo', 'https://images.pokemontcg.io/dpp/DP18_hires.png', 'water'),
    (501019, 'Darkrai LV.X', 'promo', 'https://images.pokemontcg.io/dpp/DP19_hires.png', 'darkness'),
    (501020, 'Magmortar', 'promo', 'https://images.pokemontcg.io/dpp/DP20_hires.png', 'fire'),
    (501021, 'Raichu', 'promo', 'https://images.pokemontcg.io/dpp/DP21_hires.png', 'lightning'),
    (501022, 'Mime Jr.', 'promo', 'https://images.pokemontcg.io/dpp/DP22_hires.png', 'psychic'),
    (501023, 'Glameow', 'promo', 'https://images.pokemontcg.io/dpp/DP23_hires.png', 'colorless'),
    (501024, 'Darkrai', 'promo', 'https://images.pokemontcg.io/dpp/DP24_hires.png', 'darkness'),
    (501025, 'Tropical Wind', 'promo', 'https://images.pokemontcg.io/dpp/DP25_hires.png', NULL),
    (501026, 'Dialga', 'promo', 'https://images.pokemontcg.io/dpp/DP26_hires.png', 'metal'),
    (501027, 'Palkia', 'promo', 'https://images.pokemontcg.io/dpp/DP27_hires.png', 'water'),
    (501028, 'Mewtwo LV.X', 'promo', 'https://images.pokemontcg.io/dpp/DP28_hires.png', 'psychic'),
    (501029, 'Rhyperior LV.X', 'promo', 'https://images.pokemontcg.io/dpp/DP29_hires.png', 'fighting'),
    (501030, 'Regigigas LV.X', 'promo', 'https://images.pokemontcg.io/dpp/DP30_hires.png', 'colorless'),
    (501031, 'Heatran LV.X', 'promo', 'https://images.pokemontcg.io/dpp/DP31_hires.png', 'fire'),
    (501032, 'Magnezone', 'promo', 'https://images.pokemontcg.io/dpp/DP32_hires.png', 'metal'),
    (501033, 'Dusknoir', 'promo', 'https://images.pokemontcg.io/dpp/DP33_hires.png', 'psychic'),
    (501034, 'Drifblim', 'promo', 'https://images.pokemontcg.io/dpp/DP34_hires.png', 'psychic'),
    (501035, 'Porygon-Z', 'promo', 'https://images.pokemontcg.io/dpp/DP35_hires.png', 'colorless'),
    (501036, 'Gliscor', 'promo', 'https://images.pokemontcg.io/dpp/DP36_hires.png', 'fighting'),
    (501037, 'Dialga LV.X', 'promo', 'https://images.pokemontcg.io/dpp/DP37_hires.png', 'metal'),
    (501038, 'Giratina LV.X', 'promo', 'https://images.pokemontcg.io/dpp/DP38_hires.png', 'psychic'),
    (501039, 'Shaymin LV.X', 'promo', 'https://images.pokemontcg.io/dpp/DP39_hires.png', 'grass'),
    (501040, 'Regigigas', 'promo', 'https://images.pokemontcg.io/dpp/DP40_hires.png', 'colorless'),
    (501041, 'Toxicroak G', 'promo', 'https://images.pokemontcg.io/dpp/DP41_hires.png', 'fighting'),
    (501042, 'Carnivine G', 'promo', 'https://images.pokemontcg.io/dpp/DP42_hires.png', 'grass'),
    (501043, 'Probopass G', 'promo', 'https://images.pokemontcg.io/dpp/DP43_hires.png', 'fighting'),
    (501044, 'Magnezone', 'promo', 'https://images.pokemontcg.io/dpp/DP44_hires.png', 'lightning'),
    (501045, 'Charizard G LV.X', 'promo', 'https://images.pokemontcg.io/dpp/DP45_hires.png', 'fire'),
    (501046, 'Garchomp C LV.X', 'promo', 'https://images.pokemontcg.io/dpp/DP46_hires.png', 'colorless'),
    (501047, 'Rayquaza C LV.X', 'promo', 'https://images.pokemontcg.io/dpp/DP47_hires.png', 'colorless'),
    (501048, 'Tropical Wind', 'promo', 'https://images.pokemontcg.io/dpp/DP48_hires.png', NULL),
    (501049, 'Dialga', 'promo', 'https://images.pokemontcg.io/dpp/DP49_hires.png', 'metal'),
    (501050, 'Arceus', 'promo', 'https://images.pokemontcg.io/dpp/DP50_hires.png', 'colorless'),
    (501051, 'Cresselia', 'promo', 'https://images.pokemontcg.io/dpp/DP51_hires.png', 'psychic'),
    (501052, 'Darkrai', 'promo', 'https://images.pokemontcg.io/dpp/DP52_hires.png', 'darkness'),
    (501053, 'Arceus LV.X', 'promo', 'https://images.pokemontcg.io/dpp/DP53_hires.png', 'colorless'),
    (501054, 'Beginning Door', 'promo', 'https://images.pokemontcg.io/dpp/DP54_hires.png', NULL),
    (501055, 'Ultimate Zone', 'promo', 'https://images.pokemontcg.io/dpp/DP55_hires.png', NULL),
    (501056, 'Arceus LV.X', 'promo', 'https://images.pokemontcg.io/dpp/DP56_hires.png', 'colorless')
  ) as v(number, name, rarity, image_url, pokemon_type)
  on conflict (set_id, number) do nothing
  returning id, rarity
)
insert into card_variants (card_id, variant, price_sek, stock)
select ic.id, x.variant, 0, 0
from inserted_cards ic
cross join lateral (
  select case when ic.rarity = 'rare' then 'holo' else 'normal' end as variant
  union all
  select 'reverse_holo' where ic.rarity in ('common','rare')
) as x(variant)
on conflict (card_id, variant) do nothing;

-- Set: Mysterious Treasures (dp2) -- 2007/08/01
insert into sets (category_slug, category_name, slug, name, is_visible)
  values ('diamond-pearl', 'Diamond & Pearl', 'mysterious-treasures', 'Mysterious Treasures', false)
  on conflict (slug) do nothing;

with s as (select id from sets where slug = 'mysterious-treasures'),
inserted_cards as (
  insert into cards (set_id, number, name, rarity, image_url, pokemon_type)
  select s.id, v.number, v.name, v.rarity, v.image_url, v.pokemon_type
  from s, (values
    (1, 'Aggron', 'rare', 'https://images.pokemontcg.io/dp2/1_hires.png', 'metal'),
    (2, 'Alakazam', 'rare', 'https://images.pokemontcg.io/dp2/2_hires.png', 'psychic'),
    (3, 'Ambipom', 'rare', 'https://images.pokemontcg.io/dp2/3_hires.png', 'colorless'),
    (4, 'Azelf', 'rare', 'https://images.pokemontcg.io/dp2/4_hires.png', 'psychic'),
    (5, 'Blissey', 'rare', 'https://images.pokemontcg.io/dp2/5_hires.png', 'colorless'),
    (6, 'Bronzong', 'rare', 'https://images.pokemontcg.io/dp2/6_hires.png', 'metal'),
    (7, 'Celebi', 'rare', 'https://images.pokemontcg.io/dp2/7_hires.png', 'grass'),
    (8, 'Feraligatr', 'rare', 'https://images.pokemontcg.io/dp2/8_hires.png', 'water'),
    (9, 'Garchomp', 'rare', 'https://images.pokemontcg.io/dp2/9_hires.png', 'colorless'),
    (10, 'Honchkrow', 'rare', 'https://images.pokemontcg.io/dp2/10_hires.png', 'darkness'),
    (11, 'Lumineon', 'rare', 'https://images.pokemontcg.io/dp2/11_hires.png', 'water'),
    (12, 'Magmortar', 'rare', 'https://images.pokemontcg.io/dp2/12_hires.png', 'fire'),
    (13, 'Meganium', 'rare', 'https://images.pokemontcg.io/dp2/13_hires.png', 'grass'),
    (14, 'Mesprit', 'rare', 'https://images.pokemontcg.io/dp2/14_hires.png', 'psychic'),
    (15, 'Raichu', 'rare', 'https://images.pokemontcg.io/dp2/15_hires.png', 'lightning'),
    (16, 'Typhlosion', 'rare', 'https://images.pokemontcg.io/dp2/16_hires.png', 'fire'),
    (17, 'Tyranitar', 'rare', 'https://images.pokemontcg.io/dp2/17_hires.png', 'darkness'),
    (18, 'Uxie', 'rare', 'https://images.pokemontcg.io/dp2/18_hires.png', 'psychic'),
    (19, 'Abomasnow', 'rare', 'https://images.pokemontcg.io/dp2/19_hires.png', 'grass'),
    (20, 'Ariados', 'rare', 'https://images.pokemontcg.io/dp2/20_hires.png', 'grass'),
    (21, 'Bastiodon', 'rare', 'https://images.pokemontcg.io/dp2/21_hires.png', 'metal'),
    (22, 'Chimecho', 'rare', 'https://images.pokemontcg.io/dp2/22_hires.png', 'psychic'),
    (23, 'Crobat', 'rare', 'https://images.pokemontcg.io/dp2/23_hires.png', 'psychic'),
    (24, 'Exeggutor', 'rare', 'https://images.pokemontcg.io/dp2/24_hires.png', 'grass'),
    (25, 'Glalie', 'rare', 'https://images.pokemontcg.io/dp2/25_hires.png', 'water'),
    (26, 'Gyarados', 'rare', 'https://images.pokemontcg.io/dp2/26_hires.png', 'water'),
    (27, 'Kricketune', 'rare', 'https://images.pokemontcg.io/dp2/27_hires.png', 'grass'),
    (28, 'Manectric', 'rare', 'https://images.pokemontcg.io/dp2/28_hires.png', 'lightning'),
    (29, 'Mantine', 'rare', 'https://images.pokemontcg.io/dp2/29_hires.png', 'water'),
    (30, 'Mr. Mime', 'rare', 'https://images.pokemontcg.io/dp2/30_hires.png', 'psychic'),
    (31, 'Nidoqueen', 'rare', 'https://images.pokemontcg.io/dp2/31_hires.png', 'psychic'),
    (32, 'Ninetales', 'rare', 'https://images.pokemontcg.io/dp2/32_hires.png', 'fire'),
    (33, 'Rampardos', 'rare', 'https://images.pokemontcg.io/dp2/33_hires.png', 'fighting'),
    (34, 'Slaking', 'rare', 'https://images.pokemontcg.io/dp2/34_hires.png', 'colorless'),
    (35, 'Sudowoodo', 'rare', 'https://images.pokemontcg.io/dp2/35_hires.png', 'fighting'),
    (36, 'Toxicroak', 'rare', 'https://images.pokemontcg.io/dp2/36_hires.png', 'psychic'),
    (37, 'Unown [I]', 'rare', 'https://images.pokemontcg.io/dp2/37_hires.png', 'psychic'),
    (38, 'Ursaring', 'rare', 'https://images.pokemontcg.io/dp2/38_hires.png', 'colorless'),
    (39, 'Walrein', 'rare', 'https://images.pokemontcg.io/dp2/39_hires.png', 'water'),
    (40, 'Whiscash', 'rare', 'https://images.pokemontcg.io/dp2/40_hires.png', 'water'),
    (41, 'Bayleef', 'common', 'https://images.pokemontcg.io/dp2/41_hires.png', 'grass'),
    (42, 'Chingling', 'common', 'https://images.pokemontcg.io/dp2/42_hires.png', 'psychic'),
    (43, 'Cranidos', 'common', 'https://images.pokemontcg.io/dp2/43_hires.png', 'fighting'),
    (44, 'Croconaw', 'common', 'https://images.pokemontcg.io/dp2/44_hires.png', 'water'),
    (45, 'Dewgong', 'common', 'https://images.pokemontcg.io/dp2/45_hires.png', 'water'),
    (46, 'Dodrio', 'common', 'https://images.pokemontcg.io/dp2/46_hires.png', 'colorless'),
    (47, 'Dunsparce', 'common', 'https://images.pokemontcg.io/dp2/47_hires.png', 'colorless'),
    (48, 'Gabite', 'common', 'https://images.pokemontcg.io/dp2/48_hires.png', 'colorless'),
    (49, 'Girafarig', 'common', 'https://images.pokemontcg.io/dp2/49_hires.png', 'colorless'),
    (50, 'Golbat', 'common', 'https://images.pokemontcg.io/dp2/50_hires.png', 'psychic'),
    (51, 'Graveler', 'common', 'https://images.pokemontcg.io/dp2/51_hires.png', 'fighting'),
    (52, 'Happiny', 'common', 'https://images.pokemontcg.io/dp2/52_hires.png', 'colorless'),
    (53, 'Lairon', 'common', 'https://images.pokemontcg.io/dp2/53_hires.png', 'metal'),
    (54, 'Magmar', 'common', 'https://images.pokemontcg.io/dp2/54_hires.png', 'fire'),
    (55, 'Masquerain', 'common', 'https://images.pokemontcg.io/dp2/55_hires.png', 'grass'),
    (56, 'Nidorina', 'common', 'https://images.pokemontcg.io/dp2/56_hires.png', 'psychic'),
    (57, 'Octillery', 'common', 'https://images.pokemontcg.io/dp2/57_hires.png', 'water'),
    (58, 'Parasect', 'common', 'https://images.pokemontcg.io/dp2/58_hires.png', 'grass'),
    (59, 'Pupitar', 'common', 'https://images.pokemontcg.io/dp2/59_hires.png', 'fighting'),
    (60, 'Quilava', 'common', 'https://images.pokemontcg.io/dp2/60_hires.png', 'fire'),
    (61, 'Sandslash', 'common', 'https://images.pokemontcg.io/dp2/61_hires.png', 'fighting'),
    (62, 'Sealeo', 'common', 'https://images.pokemontcg.io/dp2/62_hires.png', 'water'),
    (63, 'Shieldon', 'common', 'https://images.pokemontcg.io/dp2/63_hires.png', 'metal'),
    (64, 'Tropius', 'common', 'https://images.pokemontcg.io/dp2/64_hires.png', 'grass'),
    (65, 'Unown [E]', 'common', 'https://images.pokemontcg.io/dp2/65_hires.png', 'psychic'),
    (66, 'Unown [M]', 'common', 'https://images.pokemontcg.io/dp2/66_hires.png', 'psychic'),
    (67, 'Unown [T]', 'common', 'https://images.pokemontcg.io/dp2/67_hires.png', 'psychic'),
    (68, 'Vigoroth', 'common', 'https://images.pokemontcg.io/dp2/68_hires.png', 'colorless'),
    (69, 'Abra', 'common', 'https://images.pokemontcg.io/dp2/69_hires.png', 'psychic'),
    (70, 'Aipom', 'common', 'https://images.pokemontcg.io/dp2/70_hires.png', 'colorless'),
    (71, 'Aron', 'common', 'https://images.pokemontcg.io/dp2/71_hires.png', 'metal'),
    (72, 'Barboach', 'common', 'https://images.pokemontcg.io/dp2/72_hires.png', 'water'),
    (73, 'Bidoof', 'common', 'https://images.pokemontcg.io/dp2/73_hires.png', 'colorless'),
    (74, 'Bronzor', 'common', 'https://images.pokemontcg.io/dp2/74_hires.png', 'metal'),
    (75, 'Buizel', 'common', 'https://images.pokemontcg.io/dp2/75_hires.png', 'water'),
    (76, 'Chansey', 'common', 'https://images.pokemontcg.io/dp2/76_hires.png', 'colorless'),
    (77, 'Chikorita', 'common', 'https://images.pokemontcg.io/dp2/77_hires.png', 'grass'),
    (78, 'Croagunk', 'common', 'https://images.pokemontcg.io/dp2/78_hires.png', 'psychic'),
    (79, 'Cyndaquil', 'common', 'https://images.pokemontcg.io/dp2/79_hires.png', 'fire'),
    (80, 'Doduo', 'common', 'https://images.pokemontcg.io/dp2/80_hires.png', 'colorless'),
    (81, 'Electrike', 'common', 'https://images.pokemontcg.io/dp2/81_hires.png', 'lightning'),
    (82, 'Exeggcute', 'common', 'https://images.pokemontcg.io/dp2/82_hires.png', 'grass'),
    (83, 'Finneon', 'common', 'https://images.pokemontcg.io/dp2/83_hires.png', 'water'),
    (84, 'Geodude', 'common', 'https://images.pokemontcg.io/dp2/84_hires.png', 'fighting'),
    (85, 'Gible', 'common', 'https://images.pokemontcg.io/dp2/85_hires.png', 'colorless'),
    (86, 'Kricketot', 'common', 'https://images.pokemontcg.io/dp2/86_hires.png', 'grass'),
    (87, 'Larvitar', 'common', 'https://images.pokemontcg.io/dp2/87_hires.png', 'fighting'),
    (88, 'Magby', 'common', 'https://images.pokemontcg.io/dp2/88_hires.png', 'fire'),
    (89, 'Magikarp', 'common', 'https://images.pokemontcg.io/dp2/89_hires.png', 'water'),
    (90, 'Murkrow', 'common', 'https://images.pokemontcg.io/dp2/90_hires.png', 'darkness'),
    (91, 'Nidoran ♀', 'common', 'https://images.pokemontcg.io/dp2/91_hires.png', 'psychic'),
    (92, 'Paras', 'common', 'https://images.pokemontcg.io/dp2/92_hires.png', 'grass'),
    (93, 'Pichu', 'common', 'https://images.pokemontcg.io/dp2/93_hires.png', 'lightning'),
    (94, 'Pikachu', 'common', 'https://images.pokemontcg.io/dp2/94_hires.png', 'lightning'),
    (95, 'Remoraid', 'common', 'https://images.pokemontcg.io/dp2/95_hires.png', 'water'),
    (96, 'Sandshrew', 'common', 'https://images.pokemontcg.io/dp2/96_hires.png', 'fighting'),
    (97, 'Seel', 'common', 'https://images.pokemontcg.io/dp2/97_hires.png', 'water'),
    (98, 'Shinx', 'common', 'https://images.pokemontcg.io/dp2/98_hires.png', 'lightning'),
    (99, 'Slakoth', 'common', 'https://images.pokemontcg.io/dp2/99_hires.png', 'colorless'),
    (100, 'Snorunt', 'common', 'https://images.pokemontcg.io/dp2/100_hires.png', 'water'),
    (101, 'Snover', 'common', 'https://images.pokemontcg.io/dp2/101_hires.png', 'grass'),
    (102, 'Spheal', 'common', 'https://images.pokemontcg.io/dp2/102_hires.png', 'water'),
    (103, 'Spinarak', 'common', 'https://images.pokemontcg.io/dp2/103_hires.png', 'grass'),
    (104, 'Surskit', 'common', 'https://images.pokemontcg.io/dp2/104_hires.png', 'grass'),
    (105, 'Teddiursa', 'common', 'https://images.pokemontcg.io/dp2/105_hires.png', 'colorless'),
    (106, 'Totodile', 'common', 'https://images.pokemontcg.io/dp2/106_hires.png', 'water'),
    (107, 'Vulpix', 'common', 'https://images.pokemontcg.io/dp2/107_hires.png', 'fire'),
    (108, 'Zubat', 'common', 'https://images.pokemontcg.io/dp2/108_hires.png', 'psychic'),
    (109, 'Bebe''s Search', 'common', 'https://images.pokemontcg.io/dp2/109_hires.png', NULL),
    (110, 'Dusk Ball', 'common', 'https://images.pokemontcg.io/dp2/110_hires.png', NULL),
    (111, 'Fossil Excavator', 'common', 'https://images.pokemontcg.io/dp2/111_hires.png', NULL),
    (112, 'Lake Boundary', 'common', 'https://images.pokemontcg.io/dp2/112_hires.png', NULL),
    (113, 'Night Maintenance', 'common', 'https://images.pokemontcg.io/dp2/113_hires.png', NULL),
    (114, 'Quick Ball', 'common', 'https://images.pokemontcg.io/dp2/114_hires.png', NULL),
    (115, 'Team Galactic''s Wager', 'common', 'https://images.pokemontcg.io/dp2/115_hires.png', NULL),
    (116, 'Armor Fossil', 'common', 'https://images.pokemontcg.io/dp2/116_hires.png', NULL),
    (117, 'Skull Fossil', 'common', 'https://images.pokemontcg.io/dp2/117_hires.png', NULL),
    (118, 'Multi Energy', 'rare', 'https://images.pokemontcg.io/dp2/118_hires.png', NULL),
    (119, 'Darkness Energy', 'common', 'https://images.pokemontcg.io/dp2/119_hires.png', NULL),
    (120, 'Metal Energy', 'common', 'https://images.pokemontcg.io/dp2/120_hires.png', NULL),
    (121, 'Electivire LV.X', 'ultra_rare', 'https://images.pokemontcg.io/dp2/121_hires.png', 'lightning'),
    (122, 'Lucario LV.X', 'ultra_rare', 'https://images.pokemontcg.io/dp2/122_hires.png', 'fighting'),
    (123, 'Magmortar LV.X', 'ultra_rare', 'https://images.pokemontcg.io/dp2/123_hires.png', 'fire'),
    (124, 'Time-Space Distortion', 'mega_hyper_rare', 'https://images.pokemontcg.io/dp2/124_hires.png', NULL)
  ) as v(number, name, rarity, image_url, pokemon_type)
  on conflict (set_id, number) do nothing
  returning id, rarity
)
insert into card_variants (card_id, variant, price_sek, stock)
select ic.id, x.variant, 0, 0
from inserted_cards ic
cross join lateral (
  select case when ic.rarity = 'rare' then 'holo' else 'normal' end as variant
  union all
  select 'reverse_holo' where ic.rarity in ('common','rare')
) as x(variant)
on conflict (card_id, variant) do nothing;

-- Set: Secret Wonders (dp3) -- 2007/11/01
insert into sets (category_slug, category_name, slug, name, is_visible)
  values ('diamond-pearl', 'Diamond & Pearl', 'secret-wonders', 'Secret Wonders', false)
  on conflict (slug) do nothing;

with s as (select id from sets where slug = 'secret-wonders'),
inserted_cards as (
  insert into cards (set_id, number, name, rarity, image_url, pokemon_type)
  select s.id, v.number, v.name, v.rarity, v.image_url, v.pokemon_type
  from s, (values
    (1, 'Ampharos', 'rare', 'https://images.pokemontcg.io/dp3/1_hires.png', 'lightning'),
    (2, 'Blastoise', 'rare', 'https://images.pokemontcg.io/dp3/2_hires.png', 'water'),
    (3, 'Charizard', 'rare', 'https://images.pokemontcg.io/dp3/3_hires.png', 'fire'),
    (4, 'Entei', 'rare', 'https://images.pokemontcg.io/dp3/4_hires.png', 'fire'),
    (5, 'Flygon', 'rare', 'https://images.pokemontcg.io/dp3/5_hires.png', 'fighting'),
    (6, 'Gallade', 'rare', 'https://images.pokemontcg.io/dp3/6_hires.png', 'fighting'),
    (7, 'Gardevoir', 'rare', 'https://images.pokemontcg.io/dp3/7_hires.png', 'psychic'),
    (8, 'Gastrodon East Sea', 'rare', 'https://images.pokemontcg.io/dp3/8_hires.png', 'water'),
    (9, 'Gastrodon West Sea', 'rare', 'https://images.pokemontcg.io/dp3/9_hires.png', 'fighting'),
    (10, 'Ho-Oh', 'rare', 'https://images.pokemontcg.io/dp3/10_hires.png', 'fire'),
    (11, 'Jumpluff', 'rare', 'https://images.pokemontcg.io/dp3/11_hires.png', 'grass'),
    (12, 'Lickilicky', 'rare', 'https://images.pokemontcg.io/dp3/12_hires.png', 'colorless'),
    (13, 'Ludicolo', 'rare', 'https://images.pokemontcg.io/dp3/13_hires.png', 'water'),
    (14, 'Lugia', 'rare', 'https://images.pokemontcg.io/dp3/14_hires.png', 'colorless'),
    (15, 'Mew', 'rare', 'https://images.pokemontcg.io/dp3/15_hires.png', 'psychic'),
    (16, 'Raikou', 'rare', 'https://images.pokemontcg.io/dp3/16_hires.png', 'lightning'),
    (17, 'Roserade', 'rare', 'https://images.pokemontcg.io/dp3/17_hires.png', 'grass'),
    (18, 'Salamence', 'rare', 'https://images.pokemontcg.io/dp3/18_hires.png', 'colorless'),
    (19, 'Suicune', 'rare', 'https://images.pokemontcg.io/dp3/19_hires.png', 'water'),
    (20, 'Venusaur', 'rare', 'https://images.pokemontcg.io/dp3/20_hires.png', 'grass'),
    (21, 'Absol', 'rare', 'https://images.pokemontcg.io/dp3/21_hires.png', 'darkness'),
    (22, 'Arcanine', 'rare', 'https://images.pokemontcg.io/dp3/22_hires.png', 'fire'),
    (23, 'Banette', 'rare', 'https://images.pokemontcg.io/dp3/23_hires.png', 'psychic'),
    (24, 'Dugtrio', 'rare', 'https://images.pokemontcg.io/dp3/24_hires.png', 'fighting'),
    (25, 'Electivire', 'rare', 'https://images.pokemontcg.io/dp3/25_hires.png', 'lightning'),
    (26, 'Electrode', 'rare', 'https://images.pokemontcg.io/dp3/26_hires.png', 'lightning'),
    (27, 'Furret', 'rare', 'https://images.pokemontcg.io/dp3/27_hires.png', 'colorless'),
    (28, 'Golduck', 'rare', 'https://images.pokemontcg.io/dp3/28_hires.png', 'water'),
    (29, 'Golem', 'rare', 'https://images.pokemontcg.io/dp3/29_hires.png', 'fighting'),
    (30, 'Jynx', 'rare', 'https://images.pokemontcg.io/dp3/30_hires.png', 'psychic'),
    (31, 'Magmortar', 'rare', 'https://images.pokemontcg.io/dp3/31_hires.png', 'fire'),
    (32, 'Minun', 'rare', 'https://images.pokemontcg.io/dp3/32_hires.png', 'lightning'),
    (33, 'Mothim', 'rare', 'https://images.pokemontcg.io/dp3/33_hires.png', 'grass'),
    (34, 'Nidoking', 'rare', 'https://images.pokemontcg.io/dp3/34_hires.png', 'psychic'),
    (35, 'Pidgeot', 'rare', 'https://images.pokemontcg.io/dp3/35_hires.png', 'colorless'),
    (36, 'Plusle', 'rare', 'https://images.pokemontcg.io/dp3/36_hires.png', 'lightning'),
    (37, 'Sharpedo', 'rare', 'https://images.pokemontcg.io/dp3/37_hires.png', 'darkness'),
    (38, 'Sunflora', 'rare', 'https://images.pokemontcg.io/dp3/38_hires.png', 'grass'),
    (39, 'Unown [S]', 'rare', 'https://images.pokemontcg.io/dp3/39_hires.png', 'psychic'),
    (40, 'Weavile', 'rare', 'https://images.pokemontcg.io/dp3/40_hires.png', 'water'),
    (41, 'Wormadam Plant Cloak', 'rare', 'https://images.pokemontcg.io/dp3/41_hires.png', 'grass'),
    (42, 'Wormadam Sandy Cloak', 'rare', 'https://images.pokemontcg.io/dp3/42_hires.png', 'fighting'),
    (43, 'Wormadam Trash Cloak', 'rare', 'https://images.pokemontcg.io/dp3/43_hires.png', 'metal'),
    (44, 'Xatu', 'rare', 'https://images.pokemontcg.io/dp3/44_hires.png', 'psychic'),
    (45, 'Breloom', 'common', 'https://images.pokemontcg.io/dp3/45_hires.png', 'grass'),
    (46, 'Charmeleon', 'common', 'https://images.pokemontcg.io/dp3/46_hires.png', 'fire'),
    (47, 'Cloyster', 'common', 'https://images.pokemontcg.io/dp3/47_hires.png', 'water'),
    (48, 'Donphan', 'common', 'https://images.pokemontcg.io/dp3/48_hires.png', 'fighting'),
    (49, 'Farfetch''d', 'common', 'https://images.pokemontcg.io/dp3/49_hires.png', 'colorless'),
    (50, 'Flaaffy', 'common', 'https://images.pokemontcg.io/dp3/50_hires.png', 'lightning'),
    (51, 'Ivysaur', 'common', 'https://images.pokemontcg.io/dp3/51_hires.png', 'grass'),
    (52, 'Kecleon', 'common', 'https://images.pokemontcg.io/dp3/52_hires.png', 'colorless'),
    (53, 'Kirlia', 'common', 'https://images.pokemontcg.io/dp3/53_hires.png', 'psychic'),
    (54, 'Lombre', 'common', 'https://images.pokemontcg.io/dp3/54_hires.png', 'water'),
    (55, 'Miltank', 'common', 'https://images.pokemontcg.io/dp3/55_hires.png', 'colorless'),
    (56, 'Muk', 'common', 'https://images.pokemontcg.io/dp3/56_hires.png', 'psychic'),
    (57, 'Nidorino', 'common', 'https://images.pokemontcg.io/dp3/57_hires.png', 'psychic'),
    (58, 'Pidgeotto', 'common', 'https://images.pokemontcg.io/dp3/58_hires.png', 'colorless'),
    (59, 'Pinsir', 'common', 'https://images.pokemontcg.io/dp3/59_hires.png', 'grass'),
    (60, 'Quagsire', 'common', 'https://images.pokemontcg.io/dp3/60_hires.png', 'water'),
    (61, 'Raticate', 'common', 'https://images.pokemontcg.io/dp3/61_hires.png', 'colorless'),
    (62, 'Roselia', 'common', 'https://images.pokemontcg.io/dp3/62_hires.png', 'grass'),
    (63, 'Sableye', 'common', 'https://images.pokemontcg.io/dp3/63_hires.png', 'darkness'),
    (64, 'Shelgon', 'common', 'https://images.pokemontcg.io/dp3/64_hires.png', 'colorless'),
    (65, 'Skiploom', 'common', 'https://images.pokemontcg.io/dp3/65_hires.png', 'grass'),
    (66, 'Smeargle', 'common', 'https://images.pokemontcg.io/dp3/66_hires.png', 'colorless'),
    (67, 'Smoochum', 'common', 'https://images.pokemontcg.io/dp3/67_hires.png', 'psychic'),
    (68, 'Unown [K]', 'common', 'https://images.pokemontcg.io/dp3/68_hires.png', 'psychic'),
    (69, 'Unown [N]', 'common', 'https://images.pokemontcg.io/dp3/69_hires.png', 'psychic'),
    (70, 'Unown [O]', 'common', 'https://images.pokemontcg.io/dp3/70_hires.png', 'psychic'),
    (71, 'Unown [X]', 'common', 'https://images.pokemontcg.io/dp3/71_hires.png', 'psychic'),
    (72, 'Unown [Z]', 'common', 'https://images.pokemontcg.io/dp3/72_hires.png', 'psychic'),
    (73, 'Venomoth', 'common', 'https://images.pokemontcg.io/dp3/73_hires.png', 'grass'),
    (74, 'Vibrava', 'common', 'https://images.pokemontcg.io/dp3/74_hires.png', 'fighting'),
    (75, 'Wartortle', 'common', 'https://images.pokemontcg.io/dp3/75_hires.png', 'water'),
    (76, 'Bagon', 'common', 'https://images.pokemontcg.io/dp3/76_hires.png', 'colorless'),
    (77, 'Bulbasaur', 'common', 'https://images.pokemontcg.io/dp3/77_hires.png', 'grass'),
    (78, 'Burmy Plant Cloak', 'common', 'https://images.pokemontcg.io/dp3/78_hires.png', 'grass'),
    (79, 'Burmy Sandy Cloak', 'common', 'https://images.pokemontcg.io/dp3/79_hires.png', 'grass'),
    (80, 'Burmy Trash Cloak', 'common', 'https://images.pokemontcg.io/dp3/80_hires.png', 'grass'),
    (81, 'Carvanha', 'common', 'https://images.pokemontcg.io/dp3/81_hires.png', 'darkness'),
    (82, 'Charmander', 'common', 'https://images.pokemontcg.io/dp3/82_hires.png', 'fire'),
    (83, 'Clefairy', 'common', 'https://images.pokemontcg.io/dp3/83_hires.png', 'colorless'),
    (84, 'Corsola', 'common', 'https://images.pokemontcg.io/dp3/84_hires.png', 'water'),
    (85, 'Diglett', 'common', 'https://images.pokemontcg.io/dp3/85_hires.png', 'fighting'),
    (86, 'Duskull', 'common', 'https://images.pokemontcg.io/dp3/86_hires.png', 'psychic'),
    (87, 'Electabuzz', 'common', 'https://images.pokemontcg.io/dp3/87_hires.png', 'lightning'),
    (88, 'Grimer', 'common', 'https://images.pokemontcg.io/dp3/88_hires.png', 'psychic'),
    (89, 'Growlithe', 'common', 'https://images.pokemontcg.io/dp3/89_hires.png', 'fire'),
    (90, 'Hoppip', 'common', 'https://images.pokemontcg.io/dp3/90_hires.png', 'grass'),
    (91, 'Lickitung', 'common', 'https://images.pokemontcg.io/dp3/91_hires.png', 'colorless'),
    (92, 'Lotad', 'common', 'https://images.pokemontcg.io/dp3/92_hires.png', 'water'),
    (93, 'Magmar', 'common', 'https://images.pokemontcg.io/dp3/93_hires.png', 'fire'),
    (94, 'Mareep', 'common', 'https://images.pokemontcg.io/dp3/94_hires.png', 'lightning'),
    (95, 'Murkrow', 'common', 'https://images.pokemontcg.io/dp3/95_hires.png', 'darkness'),
    (96, 'Natu', 'common', 'https://images.pokemontcg.io/dp3/96_hires.png', 'psychic'),
    (97, 'Nidoran ♂', 'common', 'https://images.pokemontcg.io/dp3/97_hires.png', 'psychic'),
    (98, 'Phanpy', 'common', 'https://images.pokemontcg.io/dp3/98_hires.png', 'fighting'),
    (99, 'Pidgey', 'common', 'https://images.pokemontcg.io/dp3/99_hires.png', 'colorless'),
    (100, 'Psyduck', 'common', 'https://images.pokemontcg.io/dp3/100_hires.png', 'water'),
    (101, 'Qwilfish', 'common', 'https://images.pokemontcg.io/dp3/101_hires.png', 'water'),
    (102, 'Ralts', 'common', 'https://images.pokemontcg.io/dp3/102_hires.png', 'psychic'),
    (103, 'Rattata', 'common', 'https://images.pokemontcg.io/dp3/103_hires.png', 'colorless'),
    (104, 'Sentret', 'common', 'https://images.pokemontcg.io/dp3/104_hires.png', 'colorless'),
    (105, 'Shellder', 'common', 'https://images.pokemontcg.io/dp3/105_hires.png', 'water'),
    (106, 'Shellos East Sea', 'common', 'https://images.pokemontcg.io/dp3/106_hires.png', 'water'),
    (107, 'Shellos West Sea', 'common', 'https://images.pokemontcg.io/dp3/107_hires.png', 'water'),
    (108, 'Shroomish', 'common', 'https://images.pokemontcg.io/dp3/108_hires.png', 'grass'),
    (109, 'Shuckle', 'common', 'https://images.pokemontcg.io/dp3/109_hires.png', 'grass'),
    (110, 'Shuppet', 'common', 'https://images.pokemontcg.io/dp3/110_hires.png', 'psychic'),
    (111, 'Spinda', 'common', 'https://images.pokemontcg.io/dp3/111_hires.png', 'colorless'),
    (112, 'Squirtle', 'common', 'https://images.pokemontcg.io/dp3/112_hires.png', 'water'),
    (113, 'Stantler', 'common', 'https://images.pokemontcg.io/dp3/113_hires.png', 'colorless'),
    (114, 'Sunkern', 'common', 'https://images.pokemontcg.io/dp3/114_hires.png', 'grass'),
    (115, 'Trapinch', 'common', 'https://images.pokemontcg.io/dp3/115_hires.png', 'fighting'),
    (116, 'Venonat', 'common', 'https://images.pokemontcg.io/dp3/116_hires.png', 'grass'),
    (117, 'Voltorb', 'common', 'https://images.pokemontcg.io/dp3/117_hires.png', 'lightning'),
    (118, 'Wooper', 'common', 'https://images.pokemontcg.io/dp3/118_hires.png', 'water'),
    (119, 'Bebe''s Search', 'common', 'https://images.pokemontcg.io/dp3/119_hires.png', NULL),
    (120, 'Night Maintenance', 'common', 'https://images.pokemontcg.io/dp3/120_hires.png', NULL),
    (121, 'PlusPower', 'common', 'https://images.pokemontcg.io/dp3/121_hires.png', NULL),
    (122, 'Professor Oak''s Visit', 'common', 'https://images.pokemontcg.io/dp3/122_hires.png', NULL),
    (123, 'Professor Rowan', 'common', 'https://images.pokemontcg.io/dp3/123_hires.png', NULL),
    (124, 'Rival', 'common', 'https://images.pokemontcg.io/dp3/124_hires.png', NULL),
    (125, 'Roseanne''s Research', 'common', 'https://images.pokemontcg.io/dp3/125_hires.png', NULL),
    (126, 'Team Galactic''s Mars', 'common', 'https://images.pokemontcg.io/dp3/126_hires.png', NULL),
    (127, 'Potion', 'common', 'https://images.pokemontcg.io/dp3/127_hires.png', NULL),
    (128, 'Switch', 'common', 'https://images.pokemontcg.io/dp3/128_hires.png', NULL),
    (129, 'Darkness Energy', 'common', 'https://images.pokemontcg.io/dp3/129_hires.png', NULL),
    (130, 'Metal Energy', 'common', 'https://images.pokemontcg.io/dp3/130_hires.png', NULL),
    (131, 'Gardevoir LV.X', 'ultra_rare', 'https://images.pokemontcg.io/dp3/131_hires.png', 'psychic'),
    (132, 'Honchkrow LV.X', 'ultra_rare', 'https://images.pokemontcg.io/dp3/132_hires.png', 'darkness')
  ) as v(number, name, rarity, image_url, pokemon_type)
  on conflict (set_id, number) do nothing
  returning id, rarity
)
insert into card_variants (card_id, variant, price_sek, stock)
select ic.id, x.variant, 0, 0
from inserted_cards ic
cross join lateral (
  select case when ic.rarity = 'rare' then 'holo' else 'normal' end as variant
  union all
  select 'reverse_holo' where ic.rarity in ('common','rare')
) as x(variant)
on conflict (card_id, variant) do nothing;

-- Set: Great Encounters (dp4) -- 2008/02/01
insert into sets (category_slug, category_name, slug, name, is_visible)
  values ('diamond-pearl', 'Diamond & Pearl', 'great-encounters', 'Great Encounters', false)
  on conflict (slug) do nothing;

with s as (select id from sets where slug = 'great-encounters'),
inserted_cards as (
  insert into cards (set_id, number, name, rarity, image_url, pokemon_type)
  select s.id, v.number, v.name, v.rarity, v.image_url, v.pokemon_type
  from s, (values
    (1, 'Blaziken', 'rare', 'https://images.pokemontcg.io/dp4/1_hires.png', 'fire'),
    (2, 'Cresselia', 'rare', 'https://images.pokemontcg.io/dp4/2_hires.png', 'psychic'),
    (3, 'Darkrai', 'rare', 'https://images.pokemontcg.io/dp4/3_hires.png', 'darkness'),
    (4, 'Darkrai', 'rare', 'https://images.pokemontcg.io/dp4/4_hires.png', 'darkness'),
    (5, 'Pachirisu', 'rare', 'https://images.pokemontcg.io/dp4/5_hires.png', 'lightning'),
    (6, 'Porygon-Z', 'rare', 'https://images.pokemontcg.io/dp4/6_hires.png', 'colorless'),
    (7, 'Rotom', 'rare', 'https://images.pokemontcg.io/dp4/7_hires.png', 'lightning'),
    (8, 'Sceptile', 'rare', 'https://images.pokemontcg.io/dp4/8_hires.png', 'grass'),
    (9, 'Swampert', 'rare', 'https://images.pokemontcg.io/dp4/9_hires.png', 'water'),
    (10, 'Tangrowth', 'rare', 'https://images.pokemontcg.io/dp4/10_hires.png', 'grass'),
    (11, 'Togekiss', 'rare', 'https://images.pokemontcg.io/dp4/11_hires.png', 'colorless'),
    (12, 'Altaria', 'rare', 'https://images.pokemontcg.io/dp4/12_hires.png', 'colorless'),
    (13, 'Beedrill', 'rare', 'https://images.pokemontcg.io/dp4/13_hires.png', 'grass'),
    (14, 'Butterfree', 'rare', 'https://images.pokemontcg.io/dp4/14_hires.png', 'grass'),
    (15, 'Claydol', 'rare', 'https://images.pokemontcg.io/dp4/15_hires.png', 'fighting'),
    (16, 'Dialga', 'rare', 'https://images.pokemontcg.io/dp4/16_hires.png', 'metal'),
    (17, 'Exploud', 'rare', 'https://images.pokemontcg.io/dp4/17_hires.png', 'colorless'),
    (18, 'Houndoom', 'rare', 'https://images.pokemontcg.io/dp4/18_hires.png', 'darkness'),
    (19, 'Hypno', 'rare', 'https://images.pokemontcg.io/dp4/19_hires.png', 'psychic'),
    (20, 'Kingler', 'rare', 'https://images.pokemontcg.io/dp4/20_hires.png', 'water'),
    (21, 'Lapras', 'rare', 'https://images.pokemontcg.io/dp4/21_hires.png', 'water'),
    (22, 'Latias', 'rare', 'https://images.pokemontcg.io/dp4/22_hires.png', 'colorless'),
    (23, 'Latios', 'rare', 'https://images.pokemontcg.io/dp4/23_hires.png', 'colorless'),
    (24, 'Mawile', 'rare', 'https://images.pokemontcg.io/dp4/24_hires.png', 'metal'),
    (25, 'Milotic', 'rare', 'https://images.pokemontcg.io/dp4/25_hires.png', 'water'),
    (26, 'Palkia', 'rare', 'https://images.pokemontcg.io/dp4/26_hires.png', 'water'),
    (27, 'Primeape', 'rare', 'https://images.pokemontcg.io/dp4/27_hires.png', 'fighting'),
    (28, 'Slowking', 'rare', 'https://images.pokemontcg.io/dp4/28_hires.png', 'psychic'),
    (29, 'Unown [H]', 'rare', 'https://images.pokemontcg.io/dp4/29_hires.png', 'psychic'),
    (30, 'Wailord', 'rare', 'https://images.pokemontcg.io/dp4/30_hires.png', 'water'),
    (31, 'Weezing', 'rare', 'https://images.pokemontcg.io/dp4/31_hires.png', 'psychic'),
    (32, 'Wigglytuff', 'rare', 'https://images.pokemontcg.io/dp4/32_hires.png', 'colorless'),
    (33, 'Arbok', 'common', 'https://images.pokemontcg.io/dp4/33_hires.png', 'psychic'),
    (34, 'Cacturne', 'common', 'https://images.pokemontcg.io/dp4/34_hires.png', 'darkness'),
    (35, 'Combusken', 'common', 'https://images.pokemontcg.io/dp4/35_hires.png', 'fire'),
    (36, 'Delibird', 'common', 'https://images.pokemontcg.io/dp4/36_hires.png', 'water'),
    (37, 'Floatzel', 'common', 'https://images.pokemontcg.io/dp4/37_hires.png', 'water'),
    (38, 'Gorebyss', 'common', 'https://images.pokemontcg.io/dp4/38_hires.png', 'water'),
    (39, 'Granbull', 'common', 'https://images.pokemontcg.io/dp4/39_hires.png', 'colorless'),
    (40, 'Grovyle', 'common', 'https://images.pokemontcg.io/dp4/40_hires.png', 'grass'),
    (41, 'Hariyama', 'common', 'https://images.pokemontcg.io/dp4/41_hires.png', 'fighting'),
    (42, 'Huntail', 'common', 'https://images.pokemontcg.io/dp4/42_hires.png', 'water'),
    (43, 'Linoone', 'common', 'https://images.pokemontcg.io/dp4/43_hires.png', 'colorless'),
    (44, 'Loudred', 'common', 'https://images.pokemontcg.io/dp4/44_hires.png', 'colorless'),
    (45, 'Magcargo', 'common', 'https://images.pokemontcg.io/dp4/45_hires.png', 'fire'),
    (46, 'Marshtomp', 'common', 'https://images.pokemontcg.io/dp4/46_hires.png', 'water'),
    (47, 'Metapod', 'common', 'https://images.pokemontcg.io/dp4/47_hires.png', 'grass'),
    (48, 'Pelipper', 'common', 'https://images.pokemontcg.io/dp4/48_hires.png', 'water'),
    (49, 'Porygon2', 'common', 'https://images.pokemontcg.io/dp4/49_hires.png', 'colorless'),
    (50, 'Purugly', 'common', 'https://images.pokemontcg.io/dp4/50_hires.png', 'colorless'),
    (51, 'Relicanth', 'common', 'https://images.pokemontcg.io/dp4/51_hires.png', 'water'),
    (52, 'Seviper', 'common', 'https://images.pokemontcg.io/dp4/52_hires.png', 'psychic'),
    (53, 'Skarmory', 'common', 'https://images.pokemontcg.io/dp4/53_hires.png', 'metal'),
    (54, 'Slowbro', 'common', 'https://images.pokemontcg.io/dp4/54_hires.png', 'water'),
    (55, 'Togetic', 'common', 'https://images.pokemontcg.io/dp4/55_hires.png', 'colorless'),
    (56, 'Unown [F]', 'common', 'https://images.pokemontcg.io/dp4/56_hires.png', 'psychic'),
    (57, 'Unown [G]', 'common', 'https://images.pokemontcg.io/dp4/57_hires.png', 'psychic'),
    (58, 'Wailmer', 'common', 'https://images.pokemontcg.io/dp4/58_hires.png', 'water'),
    (59, 'Zangoose', 'common', 'https://images.pokemontcg.io/dp4/59_hires.png', 'colorless'),
    (60, 'Baltoy', 'common', 'https://images.pokemontcg.io/dp4/60_hires.png', 'fighting'),
    (61, 'Buizel', 'common', 'https://images.pokemontcg.io/dp4/61_hires.png', 'water'),
    (62, 'Cacnea', 'common', 'https://images.pokemontcg.io/dp4/62_hires.png', 'grass'),
    (63, 'Caterpie', 'common', 'https://images.pokemontcg.io/dp4/63_hires.png', 'grass'),
    (64, 'Clamperl', 'common', 'https://images.pokemontcg.io/dp4/64_hires.png', 'water'),
    (65, 'Drowzee', 'common', 'https://images.pokemontcg.io/dp4/65_hires.png', 'psychic'),
    (66, 'Ekans', 'common', 'https://images.pokemontcg.io/dp4/66_hires.png', 'psychic'),
    (67, 'Feebas', 'common', 'https://images.pokemontcg.io/dp4/67_hires.png', 'water'),
    (68, 'Glameow', 'common', 'https://images.pokemontcg.io/dp4/68_hires.png', 'colorless'),
    (69, 'Houndour', 'common', 'https://images.pokemontcg.io/dp4/69_hires.png', 'fire'),
    (70, 'Igglybuff', 'common', 'https://images.pokemontcg.io/dp4/70_hires.png', 'colorless'),
    (71, 'Illumise', 'common', 'https://images.pokemontcg.io/dp4/71_hires.png', 'grass'),
    (72, 'Jigglypuff', 'common', 'https://images.pokemontcg.io/dp4/72_hires.png', 'colorless'),
    (73, 'Kakuna', 'common', 'https://images.pokemontcg.io/dp4/73_hires.png', 'grass'),
    (74, 'Koffing', 'common', 'https://images.pokemontcg.io/dp4/74_hires.png', 'psychic'),
    (75, 'Krabby', 'common', 'https://images.pokemontcg.io/dp4/75_hires.png', 'water'),
    (76, 'Lunatone', 'common', 'https://images.pokemontcg.io/dp4/76_hires.png', 'fighting'),
    (77, 'Luvdisc', 'common', 'https://images.pokemontcg.io/dp4/77_hires.png', 'water'),
    (78, 'Makuhita', 'common', 'https://images.pokemontcg.io/dp4/78_hires.png', 'fighting'),
    (79, 'Mankey', 'common', 'https://images.pokemontcg.io/dp4/79_hires.png', 'fighting'),
    (80, 'Mudkip', 'common', 'https://images.pokemontcg.io/dp4/80_hires.png', 'water'),
    (81, 'Porygon', 'common', 'https://images.pokemontcg.io/dp4/81_hires.png', 'colorless'),
    (82, 'Slowpoke', 'common', 'https://images.pokemontcg.io/dp4/82_hires.png', 'water'),
    (83, 'Slugma', 'common', 'https://images.pokemontcg.io/dp4/83_hires.png', 'fire'),
    (84, 'Snubbull', 'common', 'https://images.pokemontcg.io/dp4/84_hires.png', 'colorless'),
    (85, 'Solrock', 'common', 'https://images.pokemontcg.io/dp4/85_hires.png', 'fighting'),
    (86, 'Swablu', 'common', 'https://images.pokemontcg.io/dp4/86_hires.png', 'colorless'),
    (87, 'Tangela', 'common', 'https://images.pokemontcg.io/dp4/87_hires.png', 'grass'),
    (88, 'Togepi', 'common', 'https://images.pokemontcg.io/dp4/88_hires.png', 'colorless'),
    (89, 'Torchic', 'common', 'https://images.pokemontcg.io/dp4/89_hires.png', 'fire'),
    (90, 'Treecko', 'common', 'https://images.pokemontcg.io/dp4/90_hires.png', 'grass'),
    (91, 'Unown [L]', 'common', 'https://images.pokemontcg.io/dp4/91_hires.png', 'psychic'),
    (92, 'Volbeat', 'common', 'https://images.pokemontcg.io/dp4/92_hires.png', 'grass'),
    (93, 'Weedle', 'common', 'https://images.pokemontcg.io/dp4/93_hires.png', 'grass'),
    (94, 'Whismur', 'common', 'https://images.pokemontcg.io/dp4/94_hires.png', 'colorless'),
    (95, 'Wingull', 'common', 'https://images.pokemontcg.io/dp4/95_hires.png', 'water'),
    (96, 'Zigzagoon', 'common', 'https://images.pokemontcg.io/dp4/96_hires.png', 'colorless'),
    (97, 'Amulet Coin', 'common', 'https://images.pokemontcg.io/dp4/97_hires.png', NULL),
    (98, 'Felicity''s Drawing', 'common', 'https://images.pokemontcg.io/dp4/98_hires.png', NULL),
    (99, 'Leftovers', 'common', 'https://images.pokemontcg.io/dp4/99_hires.png', NULL),
    (100, 'Moonlight Stadium', 'common', 'https://images.pokemontcg.io/dp4/100_hires.png', NULL),
    (101, 'Premier Ball', 'common', 'https://images.pokemontcg.io/dp4/101_hires.png', NULL),
    (102, 'Rare Candy', 'common', 'https://images.pokemontcg.io/dp4/102_hires.png', NULL),
    (103, 'Cresselia LV.X', 'ultra_rare', 'https://images.pokemontcg.io/dp4/103_hires.png', 'psychic'),
    (104, 'Darkrai LV.X', 'ultra_rare', 'https://images.pokemontcg.io/dp4/104_hires.png', 'darkness'),
    (105, 'Dialga LV.X', 'ultra_rare', 'https://images.pokemontcg.io/dp4/105_hires.png', 'metal'),
    (106, 'Palkia LV.X', 'ultra_rare', 'https://images.pokemontcg.io/dp4/106_hires.png', 'water')
  ) as v(number, name, rarity, image_url, pokemon_type)
  on conflict (set_id, number) do nothing
  returning id, rarity
)
insert into card_variants (card_id, variant, price_sek, stock)
select ic.id, x.variant, 0, 0
from inserted_cards ic
cross join lateral (
  select case when ic.rarity = 'rare' then 'holo' else 'normal' end as variant
  union all
  select 'reverse_holo' where ic.rarity in ('common','rare')
) as x(variant)
on conflict (card_id, variant) do nothing;

-- Set: Majestic Dawn (dp5) -- 2008/05/01
insert into sets (category_slug, category_name, slug, name, is_visible)
  values ('diamond-pearl', 'Diamond & Pearl', 'majestic-dawn', 'Majestic Dawn', false)
  on conflict (slug) do nothing;

with s as (select id from sets where slug = 'majestic-dawn'),
inserted_cards as (
  insert into cards (set_id, number, name, rarity, image_url, pokemon_type)
  select s.id, v.number, v.name, v.rarity, v.image_url, v.pokemon_type
  from s, (values
    (1, 'Articuno', 'rare', 'https://images.pokemontcg.io/dp5/1_hires.png', 'water'),
    (2, 'Cresselia', 'rare', 'https://images.pokemontcg.io/dp5/2_hires.png', 'psychic'),
    (3, 'Darkrai', 'rare', 'https://images.pokemontcg.io/dp5/3_hires.png', 'darkness'),
    (4, 'Dialga', 'rare', 'https://images.pokemontcg.io/dp5/4_hires.png', 'metal'),
    (5, 'Glaceon', 'rare', 'https://images.pokemontcg.io/dp5/5_hires.png', 'water'),
    (6, 'Kabutops', 'rare', 'https://images.pokemontcg.io/dp5/6_hires.png', 'fighting'),
    (7, 'Leafeon', 'rare', 'https://images.pokemontcg.io/dp5/7_hires.png', 'grass'),
    (8, 'Manaphy', 'rare', 'https://images.pokemontcg.io/dp5/8_hires.png', 'water'),
    (9, 'Mewtwo', 'rare', 'https://images.pokemontcg.io/dp5/9_hires.png', 'psychic'),
    (10, 'Moltres', 'rare', 'https://images.pokemontcg.io/dp5/10_hires.png', 'fire'),
    (11, 'Palkia', 'rare', 'https://images.pokemontcg.io/dp5/11_hires.png', 'water'),
    (12, 'Phione', 'rare', 'https://images.pokemontcg.io/dp5/12_hires.png', 'water'),
    (13, 'Rotom', 'rare', 'https://images.pokemontcg.io/dp5/13_hires.png', 'lightning'),
    (14, 'Zapdos', 'rare', 'https://images.pokemontcg.io/dp5/14_hires.png', 'lightning'),
    (15, 'Aerodactyl', 'rare', 'https://images.pokemontcg.io/dp5/15_hires.png', 'colorless'),
    (16, 'Bronzong', 'rare', 'https://images.pokemontcg.io/dp5/16_hires.png', 'psychic'),
    (17, 'Empoleon', 'rare', 'https://images.pokemontcg.io/dp5/17_hires.png', 'water'),
    (18, 'Espeon', 'rare', 'https://images.pokemontcg.io/dp5/18_hires.png', 'psychic'),
    (19, 'Flareon', 'rare', 'https://images.pokemontcg.io/dp5/19_hires.png', 'fire'),
    (20, 'Glaceon', 'rare', 'https://images.pokemontcg.io/dp5/20_hires.png', 'water'),
    (21, 'Hippowdon', 'rare', 'https://images.pokemontcg.io/dp5/21_hires.png', 'fighting'),
    (22, 'Infernape', 'rare', 'https://images.pokemontcg.io/dp5/22_hires.png', 'fire'),
    (23, 'Jolteon', 'rare', 'https://images.pokemontcg.io/dp5/23_hires.png', 'lightning'),
    (24, 'Leafeon', 'rare', 'https://images.pokemontcg.io/dp5/24_hires.png', 'grass'),
    (25, 'Minun', 'rare', 'https://images.pokemontcg.io/dp5/25_hires.png', 'lightning'),
    (26, 'Omastar', 'rare', 'https://images.pokemontcg.io/dp5/26_hires.png', 'water'),
    (27, 'Phione', 'rare', 'https://images.pokemontcg.io/dp5/27_hires.png', 'water'),
    (28, 'Plusle', 'rare', 'https://images.pokemontcg.io/dp5/28_hires.png', 'lightning'),
    (29, 'Scizor', 'rare', 'https://images.pokemontcg.io/dp5/29_hires.png', 'metal'),
    (30, 'Torterra', 'rare', 'https://images.pokemontcg.io/dp5/30_hires.png', 'grass'),
    (31, 'Toxicroak', 'rare', 'https://images.pokemontcg.io/dp5/31_hires.png', 'psychic'),
    (32, 'Umbreon', 'rare', 'https://images.pokemontcg.io/dp5/32_hires.png', 'darkness'),
    (33, 'Unown [P]', 'rare', 'https://images.pokemontcg.io/dp5/33_hires.png', 'psychic'),
    (34, 'Vaporeon', 'rare', 'https://images.pokemontcg.io/dp5/34_hires.png', 'water'),
    (35, 'Ambipom', 'common', 'https://images.pokemontcg.io/dp5/35_hires.png', 'colorless'),
    (36, 'Fearow', 'common', 'https://images.pokemontcg.io/dp5/36_hires.png', 'colorless'),
    (37, 'Grotle', 'common', 'https://images.pokemontcg.io/dp5/37_hires.png', 'grass'),
    (38, 'Kangaskhan', 'common', 'https://images.pokemontcg.io/dp5/38_hires.png', 'colorless'),
    (39, 'Lickitung', 'common', 'https://images.pokemontcg.io/dp5/39_hires.png', 'colorless'),
    (40, 'Manectric', 'common', 'https://images.pokemontcg.io/dp5/40_hires.png', 'lightning'),
    (41, 'Monferno', 'common', 'https://images.pokemontcg.io/dp5/41_hires.png', 'fire'),
    (42, 'Mothim', 'common', 'https://images.pokemontcg.io/dp5/42_hires.png', 'grass'),
    (43, 'Pachirisu', 'common', 'https://images.pokemontcg.io/dp5/43_hires.png', 'lightning'),
    (44, 'Prinplup', 'common', 'https://images.pokemontcg.io/dp5/44_hires.png', 'water'),
    (45, 'Raichu', 'common', 'https://images.pokemontcg.io/dp5/45_hires.png', 'lightning'),
    (46, 'Scyther', 'common', 'https://images.pokemontcg.io/dp5/46_hires.png', 'grass'),
    (47, 'Staravia', 'common', 'https://images.pokemontcg.io/dp5/47_hires.png', 'colorless'),
    (48, 'Sudowoodo', 'common', 'https://images.pokemontcg.io/dp5/48_hires.png', 'fighting'),
    (49, 'Unown [Q]', 'common', 'https://images.pokemontcg.io/dp5/49_hires.png', 'psychic'),
    (50, 'Aipom', 'common', 'https://images.pokemontcg.io/dp5/50_hires.png', 'colorless'),
    (51, 'Aipom', 'common', 'https://images.pokemontcg.io/dp5/51_hires.png', 'colorless'),
    (52, 'Bronzor', 'common', 'https://images.pokemontcg.io/dp5/52_hires.png', 'psychic'),
    (53, 'Buneary', 'common', 'https://images.pokemontcg.io/dp5/53_hires.png', 'colorless'),
    (54, 'Burmy Sandy Cloak', 'common', 'https://images.pokemontcg.io/dp5/54_hires.png', 'grass'),
    (55, 'Chatot', 'common', 'https://images.pokemontcg.io/dp5/55_hires.png', 'colorless'),
    (56, 'Chimchar', 'common', 'https://images.pokemontcg.io/dp5/56_hires.png', 'fire'),
    (57, 'Chimchar', 'common', 'https://images.pokemontcg.io/dp5/57_hires.png', 'fire'),
    (58, 'Chingling', 'common', 'https://images.pokemontcg.io/dp5/58_hires.png', 'psychic'),
    (59, 'Combee', 'common', 'https://images.pokemontcg.io/dp5/59_hires.png', 'grass'),
    (60, 'Croagunk', 'common', 'https://images.pokemontcg.io/dp5/60_hires.png', 'psychic'),
    (61, 'Drifloon', 'common', 'https://images.pokemontcg.io/dp5/61_hires.png', 'psychic'),
    (62, 'Eevee', 'common', 'https://images.pokemontcg.io/dp5/62_hires.png', 'colorless'),
    (63, 'Eevee', 'common', 'https://images.pokemontcg.io/dp5/63_hires.png', 'colorless'),
    (64, 'Electrike', 'common', 'https://images.pokemontcg.io/dp5/64_hires.png', 'lightning'),
    (65, 'Glameow', 'common', 'https://images.pokemontcg.io/dp5/65_hires.png', 'colorless'),
    (66, 'Hippopotas', 'common', 'https://images.pokemontcg.io/dp5/66_hires.png', 'fighting'),
    (67, 'Kabuto', 'common', 'https://images.pokemontcg.io/dp5/67_hires.png', 'fighting'),
    (68, 'Munchlax', 'common', 'https://images.pokemontcg.io/dp5/68_hires.png', 'colorless'),
    (69, 'Omanyte', 'common', 'https://images.pokemontcg.io/dp5/69_hires.png', 'water'),
    (70, 'Pikachu', 'common', 'https://images.pokemontcg.io/dp5/70_hires.png', 'lightning'),
    (71, 'Piplup', 'common', 'https://images.pokemontcg.io/dp5/71_hires.png', 'water'),
    (72, 'Piplup', 'common', 'https://images.pokemontcg.io/dp5/72_hires.png', 'water'),
    (73, 'Shellos East Sea', 'common', 'https://images.pokemontcg.io/dp5/73_hires.png', 'water'),
    (74, 'Spearow', 'common', 'https://images.pokemontcg.io/dp5/74_hires.png', 'colorless'),
    (75, 'Starly', 'common', 'https://images.pokemontcg.io/dp5/75_hires.png', 'colorless'),
    (76, 'Stunky', 'common', 'https://images.pokemontcg.io/dp5/76_hires.png', 'darkness'),
    (77, 'Turtwig', 'common', 'https://images.pokemontcg.io/dp5/77_hires.png', 'grass'),
    (78, 'Turtwig', 'common', 'https://images.pokemontcg.io/dp5/78_hires.png', 'grass'),
    (79, 'Dawn Stadium', 'common', 'https://images.pokemontcg.io/dp5/79_hires.png', NULL),
    (80, 'Dusk Ball', 'common', 'https://images.pokemontcg.io/dp5/80_hires.png', NULL),
    (81, 'Energy Restore', 'common', 'https://images.pokemontcg.io/dp5/81_hires.png', NULL),
    (82, 'Fossil Excavator', 'common', 'https://images.pokemontcg.io/dp5/82_hires.png', NULL),
    (83, 'Mom''s Kindness', 'common', 'https://images.pokemontcg.io/dp5/83_hires.png', NULL),
    (84, 'Old Amber', 'common', 'https://images.pokemontcg.io/dp5/84_hires.png', NULL),
    (85, 'Poké Ball', 'common', 'https://images.pokemontcg.io/dp5/85_hires.png', NULL),
    (86, 'Quick Ball', 'common', 'https://images.pokemontcg.io/dp5/86_hires.png', NULL),
    (87, 'Super Scoop Up', 'common', 'https://images.pokemontcg.io/dp5/87_hires.png', NULL),
    (88, 'Warp Point', 'common', 'https://images.pokemontcg.io/dp5/88_hires.png', NULL),
    (89, 'Dome Fossil', 'common', 'https://images.pokemontcg.io/dp5/89_hires.png', NULL),
    (90, 'Energy Search', 'common', 'https://images.pokemontcg.io/dp5/90_hires.png', NULL),
    (91, 'Helix Fossil', 'common', 'https://images.pokemontcg.io/dp5/91_hires.png', NULL),
    (92, 'Call Energy', 'common', 'https://images.pokemontcg.io/dp5/92_hires.png', NULL),
    (93, 'Darkness Energy', 'common', 'https://images.pokemontcg.io/dp5/93_hires.png', NULL),
    (94, 'Health Energy', 'common', 'https://images.pokemontcg.io/dp5/94_hires.png', NULL),
    (95, 'Metal Energy', 'common', 'https://images.pokemontcg.io/dp5/95_hires.png', NULL),
    (96, 'Recover Energy', 'common', 'https://images.pokemontcg.io/dp5/96_hires.png', NULL),
    (97, 'Garchomp LV.X', 'ultra_rare', 'https://images.pokemontcg.io/dp5/97_hires.png', 'colorless'),
    (98, 'Glaceon LV.X', 'ultra_rare', 'https://images.pokemontcg.io/dp5/98_hires.png', 'water'),
    (99, 'Leafeon LV.X', 'ultra_rare', 'https://images.pokemontcg.io/dp5/99_hires.png', 'grass'),
    (100, 'Porygon-Z LV.X', 'ultra_rare', 'https://images.pokemontcg.io/dp5/100_hires.png', 'colorless')
  ) as v(number, name, rarity, image_url, pokemon_type)
  on conflict (set_id, number) do nothing
  returning id, rarity
)
insert into card_variants (card_id, variant, price_sek, stock)
select ic.id, x.variant, 0, 0
from inserted_cards ic
cross join lateral (
  select case when ic.rarity = 'rare' then 'holo' else 'normal' end as variant
  union all
  select 'reverse_holo' where ic.rarity in ('common','rare')
) as x(variant)
on conflict (card_id, variant) do nothing;

-- Set: Legends Awakened (dp6) -- 2008/08/01
insert into sets (category_slug, category_name, slug, name, is_visible)
  values ('diamond-pearl', 'Diamond & Pearl', 'legends-awakened', 'Legends Awakened', false)
  on conflict (slug) do nothing;

with s as (select id from sets where slug = 'legends-awakened'),
inserted_cards as (
  insert into cards (set_id, number, name, rarity, image_url, pokemon_type)
  select s.id, v.number, v.name, v.rarity, v.image_url, v.pokemon_type
  from s, (values
    (1, 'Deoxys Normal Forme', 'rare', 'https://images.pokemontcg.io/dp6/1_hires.png', 'psychic'),
    (2, 'Dragonite', 'rare', 'https://images.pokemontcg.io/dp6/2_hires.png', 'colorless'),
    (3, 'Froslass', 'rare', 'https://images.pokemontcg.io/dp6/3_hires.png', 'water'),
    (4, 'Giratina', 'rare', 'https://images.pokemontcg.io/dp6/4_hires.png', 'psychic'),
    (5, 'Gliscor', 'rare', 'https://images.pokemontcg.io/dp6/5_hires.png', 'fighting'),
    (6, 'Heatran', 'rare', 'https://images.pokemontcg.io/dp6/6_hires.png', 'fire'),
    (7, 'Kingdra', 'rare', 'https://images.pokemontcg.io/dp6/7_hires.png', 'water'),
    (8, 'Luxray', 'rare', 'https://images.pokemontcg.io/dp6/8_hires.png', 'lightning'),
    (9, 'Mamoswine', 'rare', 'https://images.pokemontcg.io/dp6/9_hires.png', 'water'),
    (10, 'Metagross', 'rare', 'https://images.pokemontcg.io/dp6/10_hires.png', 'metal'),
    (11, 'Mewtwo', 'rare', 'https://images.pokemontcg.io/dp6/11_hires.png', 'psychic'),
    (12, 'Politoed', 'rare', 'https://images.pokemontcg.io/dp6/12_hires.png', 'water'),
    (13, 'Probopass', 'rare', 'https://images.pokemontcg.io/dp6/13_hires.png', 'fighting'),
    (14, 'Rayquaza', 'rare', 'https://images.pokemontcg.io/dp6/14_hires.png', 'colorless'),
    (15, 'Regigigas', 'rare', 'https://images.pokemontcg.io/dp6/15_hires.png', 'colorless'),
    (16, 'Spiritomb', 'rare', 'https://images.pokemontcg.io/dp6/16_hires.png', 'psychic'),
    (17, 'Yanmega', 'rare', 'https://images.pokemontcg.io/dp6/17_hires.png', 'grass'),
    (18, 'Armaldo', 'rare', 'https://images.pokemontcg.io/dp6/18_hires.png', 'fighting'),
    (19, 'Azelf', 'rare', 'https://images.pokemontcg.io/dp6/19_hires.png', 'psychic'),
    (20, 'Bellossom', 'rare', 'https://images.pokemontcg.io/dp6/20_hires.png', 'grass'),
    (21, 'Cradily', 'rare', 'https://images.pokemontcg.io/dp6/21_hires.png', 'grass'),
    (22, 'Crawdaunt', 'rare', 'https://images.pokemontcg.io/dp6/22_hires.png', 'water'),
    (23, 'Delcatty', 'rare', 'https://images.pokemontcg.io/dp6/23_hires.png', 'colorless'),
    (24, 'Deoxys Attack Forme', 'rare', 'https://images.pokemontcg.io/dp6/24_hires.png', 'psychic'),
    (25, 'Deoxys Defense Forme', 'rare', 'https://images.pokemontcg.io/dp6/25_hires.png', 'psychic'),
    (26, 'Deoxys Speed Forme', 'rare', 'https://images.pokemontcg.io/dp6/26_hires.png', 'psychic'),
    (27, 'Ditto', 'rare', 'https://images.pokemontcg.io/dp6/27_hires.png', 'colorless'),
    (28, 'Forretress', 'rare', 'https://images.pokemontcg.io/dp6/28_hires.png', 'metal'),
    (29, 'Groudon', 'rare', 'https://images.pokemontcg.io/dp6/29_hires.png', 'fighting'),
    (30, 'Heatran', 'rare', 'https://images.pokemontcg.io/dp6/30_hires.png', 'metal'),
    (31, 'Jirachi', 'rare', 'https://images.pokemontcg.io/dp6/31_hires.png', 'metal'),
    (32, 'Kyogre', 'rare', 'https://images.pokemontcg.io/dp6/32_hires.png', 'water'),
    (33, 'Lopunny', 'rare', 'https://images.pokemontcg.io/dp6/33_hires.png', 'colorless'),
    (34, 'Mesprit', 'rare', 'https://images.pokemontcg.io/dp6/34_hires.png', 'psychic'),
    (35, 'Poliwrath', 'rare', 'https://images.pokemontcg.io/dp6/35_hires.png', 'water'),
    (36, 'Regice', 'rare', 'https://images.pokemontcg.io/dp6/36_hires.png', 'water'),
    (37, 'Regigigas', 'rare', 'https://images.pokemontcg.io/dp6/37_hires.png', 'colorless'),
    (38, 'Regirock', 'rare', 'https://images.pokemontcg.io/dp6/38_hires.png', 'fighting'),
    (39, 'Registeel', 'rare', 'https://images.pokemontcg.io/dp6/39_hires.png', 'metal'),
    (40, 'Shedinja', 'rare', 'https://images.pokemontcg.io/dp6/40_hires.png', 'grass'),
    (41, 'Torkoal', 'rare', 'https://images.pokemontcg.io/dp6/41_hires.png', 'fire'),
    (42, 'Unown [!]', 'rare', 'https://images.pokemontcg.io/dp6/42_hires.png', 'psychic'),
    (43, 'Uxie', 'rare', 'https://images.pokemontcg.io/dp6/43_hires.png', 'psychic'),
    (44, 'Victreebel', 'rare', 'https://images.pokemontcg.io/dp6/44_hires.png', 'grass'),
    (45, 'Vileplume', 'rare', 'https://images.pokemontcg.io/dp6/45_hires.png', 'grass'),
    (46, 'Anorith', 'common', 'https://images.pokemontcg.io/dp6/46_hires.png', 'fighting'),
    (47, 'Camerupt', 'common', 'https://images.pokemontcg.io/dp6/47_hires.png', 'fire'),
    (48, 'Castform', 'common', 'https://images.pokemontcg.io/dp6/48_hires.png', 'colorless'),
    (49, 'Castform Rain Form', 'common', 'https://images.pokemontcg.io/dp6/49_hires.png', 'water'),
    (50, 'Castform Snow-Cloud Form', 'common', 'https://images.pokemontcg.io/dp6/50_hires.png', 'water'),
    (51, 'Castform Sunny Form', 'common', 'https://images.pokemontcg.io/dp6/51_hires.png', 'fire'),
    (52, 'Dragonair', 'common', 'https://images.pokemontcg.io/dp6/52_hires.png', 'colorless'),
    (53, 'Drifblim', 'common', 'https://images.pokemontcg.io/dp6/53_hires.png', 'psychic'),
    (54, 'Exeggutor', 'common', 'https://images.pokemontcg.io/dp6/54_hires.png', 'psychic'),
    (55, 'Gliscor', 'common', 'https://images.pokemontcg.io/dp6/55_hires.png', 'fighting'),
    (56, 'Grumpig', 'common', 'https://images.pokemontcg.io/dp6/56_hires.png', 'psychic'),
    (57, 'Houndoom', 'common', 'https://images.pokemontcg.io/dp6/57_hires.png', 'fire'),
    (58, 'Lanturn', 'common', 'https://images.pokemontcg.io/dp6/58_hires.png', 'water'),
    (59, 'Lanturn', 'common', 'https://images.pokemontcg.io/dp6/59_hires.png', 'lightning'),
    (60, 'Ledian', 'common', 'https://images.pokemontcg.io/dp6/60_hires.png', 'grass'),
    (61, 'Lucario', 'common', 'https://images.pokemontcg.io/dp6/61_hires.png', 'fighting'),
    (62, 'Luxio', 'common', 'https://images.pokemontcg.io/dp6/62_hires.png', 'lightning'),
    (63, 'Marowak', 'common', 'https://images.pokemontcg.io/dp6/63_hires.png', 'fighting'),
    (64, 'Metang', 'common', 'https://images.pokemontcg.io/dp6/64_hires.png', 'metal'),
    (65, 'Metang', 'common', 'https://images.pokemontcg.io/dp6/65_hires.png', 'metal'),
    (66, 'Mightyena', 'common', 'https://images.pokemontcg.io/dp6/66_hires.png', 'darkness'),
    (67, 'Ninjask', 'common', 'https://images.pokemontcg.io/dp6/67_hires.png', 'grass'),
    (68, 'Persian', 'common', 'https://images.pokemontcg.io/dp6/68_hires.png', 'colorless'),
    (69, 'Piloswine', 'common', 'https://images.pokemontcg.io/dp6/69_hires.png', 'water'),
    (70, 'Seadra', 'common', 'https://images.pokemontcg.io/dp6/70_hires.png', 'water'),
    (71, 'Starmie', 'common', 'https://images.pokemontcg.io/dp6/71_hires.png', 'water'),
    (72, 'Swalot', 'common', 'https://images.pokemontcg.io/dp6/72_hires.png', 'psychic'),
    (73, 'Swellow', 'common', 'https://images.pokemontcg.io/dp6/73_hires.png', 'colorless'),
    (74, 'Tauros', 'common', 'https://images.pokemontcg.io/dp6/74_hires.png', 'colorless'),
    (75, 'Tentacruel', 'common', 'https://images.pokemontcg.io/dp6/75_hires.png', 'water'),
    (76, 'Unown [J]', 'common', 'https://images.pokemontcg.io/dp6/76_hires.png', 'psychic'),
    (77, 'Unown [R]', 'common', 'https://images.pokemontcg.io/dp6/77_hires.png', 'psychic'),
    (78, 'Unown [U]', 'common', 'https://images.pokemontcg.io/dp6/78_hires.png', 'psychic'),
    (79, 'Unown [V]', 'common', 'https://images.pokemontcg.io/dp6/79_hires.png', 'psychic'),
    (80, 'Unown [W]', 'common', 'https://images.pokemontcg.io/dp6/80_hires.png', 'psychic'),
    (81, 'Unown [Y]', 'common', 'https://images.pokemontcg.io/dp6/81_hires.png', 'psychic'),
    (82, 'Unown [?]', 'common', 'https://images.pokemontcg.io/dp6/82_hires.png', 'psychic'),
    (83, 'Beldum', 'common', 'https://images.pokemontcg.io/dp6/83_hires.png', 'metal'),
    (84, 'Beldum', 'common', 'https://images.pokemontcg.io/dp6/84_hires.png', 'metal'),
    (85, 'Bellsprout', 'common', 'https://images.pokemontcg.io/dp6/85_hires.png', 'grass'),
    (86, 'Buneary', 'common', 'https://images.pokemontcg.io/dp6/86_hires.png', 'colorless'),
    (87, 'Chinchou', 'common', 'https://images.pokemontcg.io/dp6/87_hires.png', 'water'),
    (88, 'Chinchou', 'common', 'https://images.pokemontcg.io/dp6/88_hires.png', 'lightning'),
    (89, 'Corphish', 'common', 'https://images.pokemontcg.io/dp6/89_hires.png', 'water'),
    (90, 'Cubone', 'common', 'https://images.pokemontcg.io/dp6/90_hires.png', 'fighting'),
    (91, 'Dratini', 'common', 'https://images.pokemontcg.io/dp6/91_hires.png', 'colorless'),
    (92, 'Drifloon', 'common', 'https://images.pokemontcg.io/dp6/92_hires.png', 'psychic'),
    (93, 'Exeggcute', 'common', 'https://images.pokemontcg.io/dp6/93_hires.png', 'psychic'),
    (94, 'Gligar', 'common', 'https://images.pokemontcg.io/dp6/94_hires.png', 'fighting'),
    (95, 'Gligar', 'common', 'https://images.pokemontcg.io/dp6/95_hires.png', 'fighting'),
    (96, 'Gloom', 'common', 'https://images.pokemontcg.io/dp6/96_hires.png', 'grass'),
    (97, 'Gloom', 'common', 'https://images.pokemontcg.io/dp6/97_hires.png', 'psychic'),
    (98, 'Gulpin', 'common', 'https://images.pokemontcg.io/dp6/98_hires.png', 'psychic'),
    (99, 'Hitmonchan', 'common', 'https://images.pokemontcg.io/dp6/99_hires.png', 'fighting'),
    (100, 'Hitmonlee', 'common', 'https://images.pokemontcg.io/dp6/100_hires.png', 'fighting'),
    (101, 'Hitmontop', 'common', 'https://images.pokemontcg.io/dp6/101_hires.png', 'fighting'),
    (102, 'Horsea', 'common', 'https://images.pokemontcg.io/dp6/102_hires.png', 'water'),
    (103, 'Houndour', 'common', 'https://images.pokemontcg.io/dp6/103_hires.png', 'darkness'),
    (104, 'Ledyba', 'common', 'https://images.pokemontcg.io/dp6/104_hires.png', 'grass'),
    (105, 'Lileep', 'common', 'https://images.pokemontcg.io/dp6/105_hires.png', 'grass'),
    (106, 'Meowth', 'common', 'https://images.pokemontcg.io/dp6/106_hires.png', 'colorless'),
    (107, 'Misdreavus', 'common', 'https://images.pokemontcg.io/dp6/107_hires.png', 'psychic'),
    (108, 'Nincada', 'common', 'https://images.pokemontcg.io/dp6/108_hires.png', 'grass'),
    (109, 'Nosepass', 'common', 'https://images.pokemontcg.io/dp6/109_hires.png', 'fighting'),
    (110, 'Numel', 'common', 'https://images.pokemontcg.io/dp6/110_hires.png', 'fire'),
    (111, 'Oddish', 'common', 'https://images.pokemontcg.io/dp6/111_hires.png', 'grass'),
    (112, 'Oddish', 'common', 'https://images.pokemontcg.io/dp6/112_hires.png', 'psychic'),
    (113, 'Pineco', 'common', 'https://images.pokemontcg.io/dp6/113_hires.png', 'grass'),
    (114, 'Poliwag', 'common', 'https://images.pokemontcg.io/dp6/114_hires.png', 'water'),
    (115, 'Poliwhirl', 'common', 'https://images.pokemontcg.io/dp6/115_hires.png', 'water'),
    (116, 'Poochyena', 'common', 'https://images.pokemontcg.io/dp6/116_hires.png', 'darkness'),
    (117, 'Riolu', 'common', 'https://images.pokemontcg.io/dp6/117_hires.png', 'fighting'),
    (118, 'Shinx', 'common', 'https://images.pokemontcg.io/dp6/118_hires.png', 'lightning'),
    (119, 'Skitty', 'common', 'https://images.pokemontcg.io/dp6/119_hires.png', 'colorless'),
    (120, 'Sneasel', 'common', 'https://images.pokemontcg.io/dp6/120_hires.png', 'darkness'),
    (121, 'Spoink', 'common', 'https://images.pokemontcg.io/dp6/121_hires.png', 'psychic'),
    (122, 'Staryu', 'common', 'https://images.pokemontcg.io/dp6/122_hires.png', 'water'),
    (123, 'Swinub', 'common', 'https://images.pokemontcg.io/dp6/123_hires.png', 'water'),
    (124, 'Taillow', 'common', 'https://images.pokemontcg.io/dp6/124_hires.png', 'colorless'),
    (125, 'Tentacool', 'common', 'https://images.pokemontcg.io/dp6/125_hires.png', 'water'),
    (126, 'Tyrogue', 'common', 'https://images.pokemontcg.io/dp6/126_hires.png', 'fighting'),
    (127, 'Weepinbell', 'common', 'https://images.pokemontcg.io/dp6/127_hires.png', 'grass'),
    (128, 'Yanma', 'common', 'https://images.pokemontcg.io/dp6/128_hires.png', 'grass'),
    (129, 'Bubble Coat', 'common', 'https://images.pokemontcg.io/dp6/129_hires.png', NULL),
    (130, 'Buck''s Training', 'common', 'https://images.pokemontcg.io/dp6/130_hires.png', NULL),
    (131, 'Cynthia''s Feelings', 'common', 'https://images.pokemontcg.io/dp6/131_hires.png', NULL),
    (132, 'Energy Pickup', 'common', 'https://images.pokemontcg.io/dp6/132_hires.png', NULL),
    (133, 'Poké Radar', 'common', 'https://images.pokemontcg.io/dp6/133_hires.png', NULL),
    (134, 'Snowpoint Temple', 'common', 'https://images.pokemontcg.io/dp6/134_hires.png', NULL),
    (135, 'Stark Mountain', 'common', 'https://images.pokemontcg.io/dp6/135_hires.png', NULL),
    (136, 'Technical Machine TS-1', 'common', 'https://images.pokemontcg.io/dp6/136_hires.png', NULL),
    (137, 'Technical Machine TS-2', 'common', 'https://images.pokemontcg.io/dp6/137_hires.png', NULL),
    (138, 'Claw Fossil', 'common', 'https://images.pokemontcg.io/dp6/138_hires.png', NULL),
    (139, 'Root Fossil', 'common', 'https://images.pokemontcg.io/dp6/139_hires.png', NULL),
    (140, 'Azelf LV.X', 'ultra_rare', 'https://images.pokemontcg.io/dp6/140_hires.png', 'psychic'),
    (141, 'Gliscor LV.X', 'ultra_rare', 'https://images.pokemontcg.io/dp6/141_hires.png', 'fighting'),
    (142, 'Magnezone LV.X', 'ultra_rare', 'https://images.pokemontcg.io/dp6/142_hires.png', 'metal'),
    (143, 'Mesprit LV.X', 'ultra_rare', 'https://images.pokemontcg.io/dp6/143_hires.png', 'psychic'),
    (144, 'Mewtwo LV.X', 'ultra_rare', 'https://images.pokemontcg.io/dp6/144_hires.png', 'psychic'),
    (145, 'Rhyperior LV.X', 'ultra_rare', 'https://images.pokemontcg.io/dp6/145_hires.png', 'fighting'),
    (146, 'Uxie LV.X', 'ultra_rare', 'https://images.pokemontcg.io/dp6/146_hires.png', 'psychic')
  ) as v(number, name, rarity, image_url, pokemon_type)
  on conflict (set_id, number) do nothing
  returning id, rarity
)
insert into card_variants (card_id, variant, price_sek, stock)
select ic.id, x.variant, 0, 0
from inserted_cards ic
cross join lateral (
  select case when ic.rarity = 'rare' then 'holo' else 'normal' end as variant
  union all
  select 'reverse_holo' where ic.rarity in ('common','rare')
) as x(variant)
on conflict (card_id, variant) do nothing;

-- Set: Stormfront (dp7) -- 2008/11/01
insert into sets (category_slug, category_name, slug, name, is_visible)
  values ('diamond-pearl', 'Diamond & Pearl', 'stormfront', 'Stormfront', false)
  on conflict (slug) do nothing;

with s as (select id from sets where slug = 'stormfront'),
inserted_cards as (
  insert into cards (set_id, number, name, rarity, image_url, pokemon_type)
  select s.id, v.number, v.name, v.rarity, v.image_url, v.pokemon_type
  from s, (values
    (1, 'Dusknoir', 'rare', 'https://images.pokemontcg.io/dp7/1_hires.png', 'psychic'),
    (2, 'Empoleon', 'rare', 'https://images.pokemontcg.io/dp7/2_hires.png', 'metal'),
    (3, 'Infernape', 'rare', 'https://images.pokemontcg.io/dp7/3_hires.png', 'fighting'),
    (4, 'Lumineon', 'rare', 'https://images.pokemontcg.io/dp7/4_hires.png', 'water'),
    (5, 'Magnezone', 'rare', 'https://images.pokemontcg.io/dp7/5_hires.png', 'metal'),
    (6, 'Magnezone', 'rare', 'https://images.pokemontcg.io/dp7/6_hires.png', 'lightning'),
    (7, 'Mismagius', 'rare', 'https://images.pokemontcg.io/dp7/7_hires.png', 'psychic'),
    (8, 'Raichu', 'rare', 'https://images.pokemontcg.io/dp7/8_hires.png', 'lightning'),
    (9, 'Regigigas', 'rare', 'https://images.pokemontcg.io/dp7/9_hires.png', 'colorless'),
    (10, 'Sceptile', 'rare', 'https://images.pokemontcg.io/dp7/10_hires.png', 'grass'),
    (11, 'Torterra', 'rare', 'https://images.pokemontcg.io/dp7/11_hires.png', 'fighting'),
    (12, 'Abomasnow', 'rare', 'https://images.pokemontcg.io/dp7/12_hires.png', 'water'),
    (13, 'Bronzong', 'rare', 'https://images.pokemontcg.io/dp7/13_hires.png', 'psychic'),
    (14, 'Cherrim', 'rare', 'https://images.pokemontcg.io/dp7/14_hires.png', 'grass'),
    (15, 'Drapion', 'rare', 'https://images.pokemontcg.io/dp7/15_hires.png', 'darkness'),
    (16, 'Drifblim', 'rare', 'https://images.pokemontcg.io/dp7/16_hires.png', 'psychic'),
    (17, 'Dusknoir', 'rare', 'https://images.pokemontcg.io/dp7/17_hires.png', 'psychic'),
    (18, 'Gengar', 'rare', 'https://images.pokemontcg.io/dp7/18_hires.png', 'psychic'),
    (19, 'Gyarados', 'rare', 'https://images.pokemontcg.io/dp7/19_hires.png', 'water'),
    (20, 'Machamp', 'rare', 'https://images.pokemontcg.io/dp7/20_hires.png', 'fighting'),
    (21, 'Mamoswine', 'rare', 'https://images.pokemontcg.io/dp7/21_hires.png', 'fighting'),
    (22, 'Rapidash', 'rare', 'https://images.pokemontcg.io/dp7/22_hires.png', 'fire'),
    (23, 'Roserade', 'rare', 'https://images.pokemontcg.io/dp7/23_hires.png', 'psychic'),
    (24, 'Salamence', 'rare', 'https://images.pokemontcg.io/dp7/24_hires.png', 'colorless'),
    (25, 'Scizor', 'rare', 'https://images.pokemontcg.io/dp7/25_hires.png', 'grass'),
    (26, 'Skuntank', 'rare', 'https://images.pokemontcg.io/dp7/26_hires.png', 'darkness'),
    (27, 'Staraptor', 'rare', 'https://images.pokemontcg.io/dp7/27_hires.png', 'colorless'),
    (28, 'Steelix', 'rare', 'https://images.pokemontcg.io/dp7/28_hires.png', 'metal'),
    (29, 'Tangrowth', 'rare', 'https://images.pokemontcg.io/dp7/29_hires.png', 'grass'),
    (30, 'Tyranitar', 'rare', 'https://images.pokemontcg.io/dp7/30_hires.png', 'darkness'),
    (31, 'Vespiquen', 'rare', 'https://images.pokemontcg.io/dp7/31_hires.png', 'grass'),
    (32, 'Bibarel', 'common', 'https://images.pokemontcg.io/dp7/32_hires.png', 'water'),
    (33, 'Budew', 'common', 'https://images.pokemontcg.io/dp7/33_hires.png', 'psychic'),
    (34, 'Dusclops', 'common', 'https://images.pokemontcg.io/dp7/34_hires.png', 'psychic'),
    (35, 'Dusclops', 'common', 'https://images.pokemontcg.io/dp7/35_hires.png', 'psychic'),
    (36, 'Electrode', 'common', 'https://images.pokemontcg.io/dp7/36_hires.png', 'lightning'),
    (37, 'Electrode', 'common', 'https://images.pokemontcg.io/dp7/37_hires.png', 'lightning'),
    (38, 'Farfetch''d', 'common', 'https://images.pokemontcg.io/dp7/38_hires.png', 'colorless'),
    (39, 'Grovyle', 'common', 'https://images.pokemontcg.io/dp7/39_hires.png', 'grass'),
    (40, 'Haunter', 'common', 'https://images.pokemontcg.io/dp7/40_hires.png', 'psychic'),
    (41, 'Machoke', 'common', 'https://images.pokemontcg.io/dp7/41_hires.png', 'fighting'),
    (42, 'Magneton', 'common', 'https://images.pokemontcg.io/dp7/42_hires.png', 'metal'),
    (43, 'Magneton', 'common', 'https://images.pokemontcg.io/dp7/43_hires.png', 'lightning'),
    (44, 'Miltank', 'common', 'https://images.pokemontcg.io/dp7/44_hires.png', 'colorless'),
    (45, 'Pichu', 'common', 'https://images.pokemontcg.io/dp7/45_hires.png', 'lightning'),
    (46, 'Piloswine', 'common', 'https://images.pokemontcg.io/dp7/46_hires.png', 'fighting'),
    (47, 'Pupitar', 'common', 'https://images.pokemontcg.io/dp7/47_hires.png', 'fighting'),
    (48, 'Sableye', 'common', 'https://images.pokemontcg.io/dp7/48_hires.png', 'darkness'),
    (49, 'Scyther', 'common', 'https://images.pokemontcg.io/dp7/49_hires.png', 'grass'),
    (50, 'Shelgon', 'common', 'https://images.pokemontcg.io/dp7/50_hires.png', 'colorless'),
    (51, 'Skarmory', 'common', 'https://images.pokemontcg.io/dp7/51_hires.png', 'metal'),
    (52, 'Staravia', 'common', 'https://images.pokemontcg.io/dp7/52_hires.png', 'colorless'),
    (53, 'Bagon', 'common', 'https://images.pokemontcg.io/dp7/53_hires.png', 'colorless'),
    (54, 'Bidoof', 'common', 'https://images.pokemontcg.io/dp7/54_hires.png', 'colorless'),
    (55, 'Bronzor', 'common', 'https://images.pokemontcg.io/dp7/55_hires.png', 'psychic'),
    (56, 'Cherubi', 'common', 'https://images.pokemontcg.io/dp7/56_hires.png', 'grass'),
    (57, 'Combee', 'common', 'https://images.pokemontcg.io/dp7/57_hires.png', 'grass'),
    (58, 'Drifloon', 'common', 'https://images.pokemontcg.io/dp7/58_hires.png', 'psychic'),
    (59, 'Duskull', 'common', 'https://images.pokemontcg.io/dp7/59_hires.png', 'psychic'),
    (60, 'Duskull', 'common', 'https://images.pokemontcg.io/dp7/60_hires.png', 'psychic'),
    (61, 'Finneon', 'common', 'https://images.pokemontcg.io/dp7/61_hires.png', 'water'),
    (62, 'Gastly', 'common', 'https://images.pokemontcg.io/dp7/62_hires.png', 'psychic'),
    (63, 'Larvitar', 'common', 'https://images.pokemontcg.io/dp7/63_hires.png', 'fighting'),
    (64, 'Machop', 'common', 'https://images.pokemontcg.io/dp7/64_hires.png', 'fighting'),
    (65, 'Magikarp', 'common', 'https://images.pokemontcg.io/dp7/65_hires.png', 'water'),
    (66, 'Magnemite', 'common', 'https://images.pokemontcg.io/dp7/66_hires.png', 'metal'),
    (67, 'Magnemite', 'common', 'https://images.pokemontcg.io/dp7/67_hires.png', 'lightning'),
    (68, 'Misdreavus', 'common', 'https://images.pokemontcg.io/dp7/68_hires.png', 'psychic'),
    (69, 'Onix', 'common', 'https://images.pokemontcg.io/dp7/69_hires.png', 'fighting'),
    (70, 'Pikachu', 'common', 'https://images.pokemontcg.io/dp7/70_hires.png', 'lightning'),
    (71, 'Ponyta', 'common', 'https://images.pokemontcg.io/dp7/71_hires.png', 'fire'),
    (72, 'Roselia', 'common', 'https://images.pokemontcg.io/dp7/72_hires.png', 'psychic'),
    (73, 'Skorupi', 'common', 'https://images.pokemontcg.io/dp7/73_hires.png', 'grass'),
    (74, 'Snover', 'common', 'https://images.pokemontcg.io/dp7/74_hires.png', 'water'),
    (75, 'Starly', 'common', 'https://images.pokemontcg.io/dp7/75_hires.png', 'colorless'),
    (76, 'Stunky', 'common', 'https://images.pokemontcg.io/dp7/76_hires.png', 'darkness'),
    (77, 'Swinub', 'common', 'https://images.pokemontcg.io/dp7/77_hires.png', 'fighting'),
    (78, 'Tangela', 'common', 'https://images.pokemontcg.io/dp7/78_hires.png', 'grass'),
    (79, 'Treecko', 'common', 'https://images.pokemontcg.io/dp7/79_hires.png', 'grass'),
    (80, 'Voltorb', 'common', 'https://images.pokemontcg.io/dp7/80_hires.png', 'lightning'),
    (81, 'Voltorb', 'common', 'https://images.pokemontcg.io/dp7/81_hires.png', 'lightning'),
    (82, 'Conductive Quarry', 'common', 'https://images.pokemontcg.io/dp7/82_hires.png', NULL),
    (83, 'Energy Link', 'common', 'https://images.pokemontcg.io/dp7/83_hires.png', NULL),
    (84, 'Energy Switch', 'common', 'https://images.pokemontcg.io/dp7/84_hires.png', NULL),
    (85, 'Great Ball', 'common', 'https://images.pokemontcg.io/dp7/85_hires.png', NULL),
    (86, 'Luxury Ball', 'common', 'https://images.pokemontcg.io/dp7/86_hires.png', NULL),
    (87, 'Marley''s Request', 'common', 'https://images.pokemontcg.io/dp7/87_hires.png', NULL),
    (88, 'Poké Blower +', 'common', 'https://images.pokemontcg.io/dp7/88_hires.png', NULL),
    (89, 'Poké Drawer +', 'common', 'https://images.pokemontcg.io/dp7/89_hires.png', NULL),
    (90, 'Poké Healer +', 'common', 'https://images.pokemontcg.io/dp7/90_hires.png', NULL),
    (91, 'Premier Ball', 'common', 'https://images.pokemontcg.io/dp7/91_hires.png', NULL),
    (92, 'Potion', 'common', 'https://images.pokemontcg.io/dp7/92_hires.png', NULL),
    (93, 'Switch', 'common', 'https://images.pokemontcg.io/dp7/93_hires.png', NULL),
    (94, 'Cyclone Energy', 'common', 'https://images.pokemontcg.io/dp7/94_hires.png', NULL),
    (95, 'Warp Energy', 'common', 'https://images.pokemontcg.io/dp7/95_hires.png', NULL),
    (96, 'Dusknoir LV.X', 'ultra_rare', 'https://images.pokemontcg.io/dp7/96_hires.png', 'psychic'),
    (97, 'Heatran LV.X', 'ultra_rare', 'https://images.pokemontcg.io/dp7/97_hires.png', 'fire'),
    (98, 'Machamp LV.X', 'ultra_rare', 'https://images.pokemontcg.io/dp7/98_hires.png', 'fighting'),
    (99, 'Raichu LV.X', 'ultra_rare', 'https://images.pokemontcg.io/dp7/99_hires.png', 'lightning'),
    (100, 'Regigigas LV.X', 'ultra_rare', 'https://images.pokemontcg.io/dp7/100_hires.png', 'colorless'),
    (101, 'Charmander', 'mega_hyper_rare', 'https://images.pokemontcg.io/dp7/101_hires.png', 'fire'),
    (102, 'Charmeleon', 'mega_hyper_rare', 'https://images.pokemontcg.io/dp7/102_hires.png', 'fire'),
    (103, 'Charizard', 'mega_hyper_rare', 'https://images.pokemontcg.io/dp7/103_hires.png', 'fire'),
    (501001, 'Drifloon', 'rare', 'https://images.pokemontcg.io/dp7/SH1_hires.png', 'psychic'),
    (501002, 'Duskull', 'rare', 'https://images.pokemontcg.io/dp7/SH2_hires.png', 'psychic'),
    (501003, 'Voltorb', 'rare', 'https://images.pokemontcg.io/dp7/SH3_hires.png', 'lightning')
  ) as v(number, name, rarity, image_url, pokemon_type)
  on conflict (set_id, number) do nothing
  returning id, rarity
)
insert into card_variants (card_id, variant, price_sek, stock)
select ic.id, x.variant, 0, 0
from inserted_cards ic
cross join lateral (
  select case when ic.rarity = 'rare' then 'holo' else 'normal' end as variant
  union all
  select 'reverse_holo' where ic.rarity in ('common','rare')
) as x(variant)
on conflict (card_id, variant) do nothing;
