-- Katalogimport: E-Card (3 set)
-- Endast katalogdata (lager 0, pris 0) för portfölj/önskelista-funktionen.

-- Set: Expedition Base Set (ecard1) -- 2002/09/15
insert into sets (category_slug, category_name, slug, name, is_visible)
  values ('e-card', 'E-Card', 'expedition-base-set', 'Expedition Base Set', false)
  on conflict (slug) do nothing;

with s as (select id from sets where slug = 'expedition-base-set'),
inserted_cards as (
  insert into cards (set_id, number, name, rarity, image_url, pokemon_type)
  select s.id, v.number, v.name, v.rarity, v.image_url, v.pokemon_type
  from s, (values
    (1, 'Alakazam', 'rare', 'https://images.pokemontcg.io/ecard1/1_hires.png', 'psychic'),
    (2, 'Ampharos', 'rare', 'https://images.pokemontcg.io/ecard1/2_hires.png', 'lightning'),
    (3, 'Arbok', 'rare', 'https://images.pokemontcg.io/ecard1/3_hires.png', 'grass'),
    (4, 'Blastoise', 'rare', 'https://images.pokemontcg.io/ecard1/4_hires.png', 'water'),
    (5, 'Butterfree', 'rare', 'https://images.pokemontcg.io/ecard1/5_hires.png', 'grass'),
    (6, 'Charizard', 'rare', 'https://images.pokemontcg.io/ecard1/6_hires.png', 'fire'),
    (7, 'Clefable', 'rare', 'https://images.pokemontcg.io/ecard1/7_hires.png', 'colorless'),
    (8, 'Cloyster', 'rare', 'https://images.pokemontcg.io/ecard1/8_hires.png', 'water'),
    (9, 'Dragonite', 'rare', 'https://images.pokemontcg.io/ecard1/9_hires.png', 'colorless'),
    (10, 'Dugtrio', 'rare', 'https://images.pokemontcg.io/ecard1/10_hires.png', 'fighting'),
    (11, 'Fearow', 'rare', 'https://images.pokemontcg.io/ecard1/11_hires.png', 'colorless'),
    (12, 'Feraligatr', 'rare', 'https://images.pokemontcg.io/ecard1/12_hires.png', 'water'),
    (13, 'Gengar', 'rare', 'https://images.pokemontcg.io/ecard1/13_hires.png', 'psychic'),
    (14, 'Golem', 'rare', 'https://images.pokemontcg.io/ecard1/14_hires.png', 'fighting'),
    (15, 'Kingler', 'rare', 'https://images.pokemontcg.io/ecard1/15_hires.png', 'water'),
    (16, 'Machamp', 'rare', 'https://images.pokemontcg.io/ecard1/16_hires.png', 'fighting'),
    (17, 'Magby', 'rare', 'https://images.pokemontcg.io/ecard1/17_hires.png', 'fire'),
    (18, 'Meganium', 'rare', 'https://images.pokemontcg.io/ecard1/18_hires.png', 'grass'),
    (19, 'Mew', 'rare', 'https://images.pokemontcg.io/ecard1/19_hires.png', 'psychic'),
    (20, 'Mewtwo', 'rare', 'https://images.pokemontcg.io/ecard1/20_hires.png', 'psychic'),
    (21, 'Ninetales', 'rare', 'https://images.pokemontcg.io/ecard1/21_hires.png', 'fire'),
    (22, 'Pichu', 'rare', 'https://images.pokemontcg.io/ecard1/22_hires.png', 'lightning'),
    (23, 'Pidgeot', 'rare', 'https://images.pokemontcg.io/ecard1/23_hires.png', 'colorless'),
    (24, 'Poliwrath', 'rare', 'https://images.pokemontcg.io/ecard1/24_hires.png', 'water'),
    (25, 'Raichu', 'rare', 'https://images.pokemontcg.io/ecard1/25_hires.png', 'lightning'),
    (26, 'Rapidash', 'rare', 'https://images.pokemontcg.io/ecard1/26_hires.png', 'fire'),
    (27, 'Skarmory', 'rare', 'https://images.pokemontcg.io/ecard1/27_hires.png', 'metal'),
    (28, 'Typhlosion', 'rare', 'https://images.pokemontcg.io/ecard1/28_hires.png', 'fire'),
    (29, 'Tyranitar', 'rare', 'https://images.pokemontcg.io/ecard1/29_hires.png', 'darkness'),
    (30, 'Venusaur', 'rare', 'https://images.pokemontcg.io/ecard1/30_hires.png', 'grass'),
    (31, 'Vileplume', 'rare', 'https://images.pokemontcg.io/ecard1/31_hires.png', 'grass'),
    (32, 'Weezing', 'rare', 'https://images.pokemontcg.io/ecard1/32_hires.png', 'grass'),
    (33, 'Alakazam', 'rare', 'https://images.pokemontcg.io/ecard1/33_hires.png', 'psychic'),
    (34, 'Ampharos', 'rare', 'https://images.pokemontcg.io/ecard1/34_hires.png', 'lightning'),
    (35, 'Arbok', 'rare', 'https://images.pokemontcg.io/ecard1/35_hires.png', 'grass'),
    (36, 'Blastoise', 'rare', 'https://images.pokemontcg.io/ecard1/36_hires.png', 'water'),
    (37, 'Blastoise', 'rare', 'https://images.pokemontcg.io/ecard1/37_hires.png', 'water'),
    (38, 'Butterfree', 'rare', 'https://images.pokemontcg.io/ecard1/38_hires.png', 'grass'),
    (39, 'Charizard', 'rare', 'https://images.pokemontcg.io/ecard1/39_hires.png', 'fire'),
    (40, 'Charizard', 'rare', 'https://images.pokemontcg.io/ecard1/40_hires.png', 'fire'),
    (41, 'Clefable', 'rare', 'https://images.pokemontcg.io/ecard1/41_hires.png', 'colorless'),
    (42, 'Cloyster', 'rare', 'https://images.pokemontcg.io/ecard1/42_hires.png', 'water'),
    (43, 'Dragonite', 'rare', 'https://images.pokemontcg.io/ecard1/43_hires.png', 'colorless'),
    (44, 'Dugtrio', 'rare', 'https://images.pokemontcg.io/ecard1/44_hires.png', 'fighting'),
    (45, 'Fearow', 'rare', 'https://images.pokemontcg.io/ecard1/45_hires.png', 'colorless'),
    (46, 'Feraligatr', 'rare', 'https://images.pokemontcg.io/ecard1/46_hires.png', 'water'),
    (47, 'Feraligatr', 'rare', 'https://images.pokemontcg.io/ecard1/47_hires.png', 'water'),
    (48, 'Gengar', 'rare', 'https://images.pokemontcg.io/ecard1/48_hires.png', 'psychic'),
    (49, 'Golem', 'rare', 'https://images.pokemontcg.io/ecard1/49_hires.png', 'fighting'),
    (50, 'Kingler', 'rare', 'https://images.pokemontcg.io/ecard1/50_hires.png', 'water'),
    (51, 'Machamp', 'rare', 'https://images.pokemontcg.io/ecard1/51_hires.png', 'fighting'),
    (52, 'Magby', 'rare', 'https://images.pokemontcg.io/ecard1/52_hires.png', 'fire'),
    (53, 'Meganium', 'rare', 'https://images.pokemontcg.io/ecard1/53_hires.png', 'grass'),
    (54, 'Meganium', 'rare', 'https://images.pokemontcg.io/ecard1/54_hires.png', 'grass'),
    (55, 'Mew', 'rare', 'https://images.pokemontcg.io/ecard1/55_hires.png', 'psychic'),
    (56, 'Mewtwo', 'rare', 'https://images.pokemontcg.io/ecard1/56_hires.png', 'psychic'),
    (57, 'Ninetales', 'rare', 'https://images.pokemontcg.io/ecard1/57_hires.png', 'fire'),
    (58, 'Pichu', 'rare', 'https://images.pokemontcg.io/ecard1/58_hires.png', 'lightning'),
    (59, 'Pidgeot', 'rare', 'https://images.pokemontcg.io/ecard1/59_hires.png', 'colorless'),
    (60, 'Poliwrath', 'rare', 'https://images.pokemontcg.io/ecard1/60_hires.png', 'water'),
    (61, 'Raichu', 'rare', 'https://images.pokemontcg.io/ecard1/61_hires.png', 'lightning'),
    (62, 'Rapidash', 'rare', 'https://images.pokemontcg.io/ecard1/62_hires.png', 'fire'),
    (63, 'Skarmory', 'rare', 'https://images.pokemontcg.io/ecard1/63_hires.png', 'metal'),
    (64, 'Typhlosion', 'rare', 'https://images.pokemontcg.io/ecard1/64_hires.png', 'fire'),
    (65, 'Typhlosion', 'rare', 'https://images.pokemontcg.io/ecard1/65_hires.png', 'fire'),
    (66, 'Tyranitar', 'rare', 'https://images.pokemontcg.io/ecard1/66_hires.png', 'darkness'),
    (67, 'Venusaur', 'rare', 'https://images.pokemontcg.io/ecard1/67_hires.png', 'grass'),
    (68, 'Venusaur', 'rare', 'https://images.pokemontcg.io/ecard1/68_hires.png', 'grass'),
    (69, 'Vileplume', 'rare', 'https://images.pokemontcg.io/ecard1/69_hires.png', 'grass'),
    (70, 'Weezing', 'rare', 'https://images.pokemontcg.io/ecard1/70_hires.png', 'grass'),
    (71, 'Bayleef', 'common', 'https://images.pokemontcg.io/ecard1/71_hires.png', 'grass'),
    (72, 'Chansey', 'common', 'https://images.pokemontcg.io/ecard1/72_hires.png', 'colorless'),
    (73, 'Charmeleon', 'common', 'https://images.pokemontcg.io/ecard1/73_hires.png', 'fire'),
    (74, 'Croconaw', 'common', 'https://images.pokemontcg.io/ecard1/74_hires.png', 'water'),
    (75, 'Dragonair', 'common', 'https://images.pokemontcg.io/ecard1/75_hires.png', 'colorless'),
    (76, 'Electabuzz', 'common', 'https://images.pokemontcg.io/ecard1/76_hires.png', 'lightning'),
    (77, 'Flaaffy', 'common', 'https://images.pokemontcg.io/ecard1/77_hires.png', 'lightning'),
    (78, 'Gloom', 'common', 'https://images.pokemontcg.io/ecard1/78_hires.png', 'grass'),
    (79, 'Graveler', 'common', 'https://images.pokemontcg.io/ecard1/79_hires.png', 'fighting'),
    (80, 'Haunter', 'common', 'https://images.pokemontcg.io/ecard1/80_hires.png', 'psychic'),
    (81, 'Hitmonlee', 'common', 'https://images.pokemontcg.io/ecard1/81_hires.png', 'fighting'),
    (82, 'Ivysaur', 'common', 'https://images.pokemontcg.io/ecard1/82_hires.png', 'grass'),
    (83, 'Jynx', 'common', 'https://images.pokemontcg.io/ecard1/83_hires.png', 'water'),
    (84, 'Kadabra', 'common', 'https://images.pokemontcg.io/ecard1/84_hires.png', 'psychic'),
    (85, 'Machoke', 'common', 'https://images.pokemontcg.io/ecard1/85_hires.png', 'fighting'),
    (86, 'Magmar', 'common', 'https://images.pokemontcg.io/ecard1/86_hires.png', 'fire'),
    (87, 'Metapod', 'common', 'https://images.pokemontcg.io/ecard1/87_hires.png', 'grass'),
    (88, 'Pidgeotto', 'common', 'https://images.pokemontcg.io/ecard1/88_hires.png', 'colorless'),
    (89, 'Poliwhirl', 'common', 'https://images.pokemontcg.io/ecard1/89_hires.png', 'water'),
    (90, 'Pupitar', 'common', 'https://images.pokemontcg.io/ecard1/90_hires.png', 'fighting'),
    (91, 'Quilava', 'common', 'https://images.pokemontcg.io/ecard1/91_hires.png', 'fire'),
    (92, 'Wartortle', 'common', 'https://images.pokemontcg.io/ecard1/92_hires.png', 'water'),
    (93, 'Abra', 'common', 'https://images.pokemontcg.io/ecard1/93_hires.png', 'psychic'),
    (94, 'Bulbasaur', 'common', 'https://images.pokemontcg.io/ecard1/94_hires.png', 'grass'),
    (95, 'Bulbasaur', 'common', 'https://images.pokemontcg.io/ecard1/95_hires.png', 'grass'),
    (96, 'Caterpie', 'common', 'https://images.pokemontcg.io/ecard1/96_hires.png', 'grass'),
    (97, 'Charmander', 'common', 'https://images.pokemontcg.io/ecard1/97_hires.png', 'fire'),
    (98, 'Charmander', 'common', 'https://images.pokemontcg.io/ecard1/98_hires.png', 'fire'),
    (99, 'Chikorita', 'common', 'https://images.pokemontcg.io/ecard1/99_hires.png', 'grass'),
    (100, 'Chikorita', 'common', 'https://images.pokemontcg.io/ecard1/100_hires.png', 'grass'),
    (101, 'Clefairy', 'common', 'https://images.pokemontcg.io/ecard1/101_hires.png', 'colorless'),
    (102, 'Corsola', 'common', 'https://images.pokemontcg.io/ecard1/102_hires.png', 'water'),
    (103, 'Cubone', 'common', 'https://images.pokemontcg.io/ecard1/103_hires.png', 'fighting'),
    (104, 'Cyndaquil', 'common', 'https://images.pokemontcg.io/ecard1/104_hires.png', 'fire'),
    (105, 'Cyndaquil', 'common', 'https://images.pokemontcg.io/ecard1/105_hires.png', 'fire'),
    (106, 'Diglett', 'common', 'https://images.pokemontcg.io/ecard1/106_hires.png', 'fighting'),
    (107, 'Dratini', 'common', 'https://images.pokemontcg.io/ecard1/107_hires.png', 'colorless'),
    (108, 'Ekans', 'common', 'https://images.pokemontcg.io/ecard1/108_hires.png', 'grass'),
    (109, 'Gastly', 'common', 'https://images.pokemontcg.io/ecard1/109_hires.png', 'psychic'),
    (110, 'Geodude', 'common', 'https://images.pokemontcg.io/ecard1/110_hires.png', 'fighting'),
    (111, 'Goldeen', 'common', 'https://images.pokemontcg.io/ecard1/111_hires.png', 'water'),
    (112, 'Hoppip', 'common', 'https://images.pokemontcg.io/ecard1/112_hires.png', 'grass'),
    (113, 'Houndour', 'common', 'https://images.pokemontcg.io/ecard1/113_hires.png', 'darkness'),
    (114, 'Koffing', 'common', 'https://images.pokemontcg.io/ecard1/114_hires.png', 'grass'),
    (115, 'Krabby', 'common', 'https://images.pokemontcg.io/ecard1/115_hires.png', 'water'),
    (116, 'Larvitar', 'common', 'https://images.pokemontcg.io/ecard1/116_hires.png', 'fighting'),
    (117, 'Machop', 'common', 'https://images.pokemontcg.io/ecard1/117_hires.png', 'fighting'),
    (118, 'Magikarp', 'common', 'https://images.pokemontcg.io/ecard1/118_hires.png', 'water'),
    (119, 'Mareep', 'common', 'https://images.pokemontcg.io/ecard1/119_hires.png', 'lightning'),
    (120, 'Marill', 'common', 'https://images.pokemontcg.io/ecard1/120_hires.png', 'water'),
    (121, 'Meowth', 'common', 'https://images.pokemontcg.io/ecard1/121_hires.png', 'colorless'),
    (122, 'Oddish', 'common', 'https://images.pokemontcg.io/ecard1/122_hires.png', 'grass'),
    (123, 'Pidgey', 'common', 'https://images.pokemontcg.io/ecard1/123_hires.png', 'colorless'),
    (124, 'Pikachu', 'common', 'https://images.pokemontcg.io/ecard1/124_hires.png', 'lightning'),
    (125, 'Poliwag', 'common', 'https://images.pokemontcg.io/ecard1/125_hires.png', 'water'),
    (126, 'Ponyta', 'common', 'https://images.pokemontcg.io/ecard1/126_hires.png', 'fire'),
    (127, 'Qwilfish', 'common', 'https://images.pokemontcg.io/ecard1/127_hires.png', 'water'),
    (128, 'Rattata', 'common', 'https://images.pokemontcg.io/ecard1/128_hires.png', 'colorless'),
    (129, 'Shellder', 'common', 'https://images.pokemontcg.io/ecard1/129_hires.png', 'water'),
    (130, 'Spearow', 'common', 'https://images.pokemontcg.io/ecard1/130_hires.png', 'colorless'),
    (131, 'Squirtle', 'common', 'https://images.pokemontcg.io/ecard1/131_hires.png', 'water'),
    (132, 'Squirtle', 'common', 'https://images.pokemontcg.io/ecard1/132_hires.png', 'water'),
    (133, 'Tauros', 'common', 'https://images.pokemontcg.io/ecard1/133_hires.png', 'colorless'),
    (134, 'Totodile', 'common', 'https://images.pokemontcg.io/ecard1/134_hires.png', 'water'),
    (135, 'Totodile', 'common', 'https://images.pokemontcg.io/ecard1/135_hires.png', 'water'),
    (136, 'Vulpix', 'common', 'https://images.pokemontcg.io/ecard1/136_hires.png', 'fire'),
    (137, 'Bill''s Maintenance', 'common', 'https://images.pokemontcg.io/ecard1/137_hires.png', NULL),
    (138, 'Copycat', 'common', 'https://images.pokemontcg.io/ecard1/138_hires.png', NULL),
    (139, 'Dual Ball', 'common', 'https://images.pokemontcg.io/ecard1/139_hires.png', NULL),
    (140, 'Energy Removal 2', 'common', 'https://images.pokemontcg.io/ecard1/140_hires.png', NULL),
    (141, 'Energy Restore', 'common', 'https://images.pokemontcg.io/ecard1/141_hires.png', NULL),
    (142, 'Mary''s Impulse', 'common', 'https://images.pokemontcg.io/ecard1/142_hires.png', NULL),
    (143, 'Master Ball', 'common', 'https://images.pokemontcg.io/ecard1/143_hires.png', NULL),
    (144, 'Multi Technical Machine 01', 'common', 'https://images.pokemontcg.io/ecard1/144_hires.png', NULL),
    (145, 'Pokémon Nurse', 'common', 'https://images.pokemontcg.io/ecard1/145_hires.png', NULL),
    (146, 'Pokémon Reversal', 'common', 'https://images.pokemontcg.io/ecard1/146_hires.png', NULL),
    (147, 'Power Charge', 'common', 'https://images.pokemontcg.io/ecard1/147_hires.png', NULL),
    (148, 'Professor Elm''s Training Method', 'common', 'https://images.pokemontcg.io/ecard1/148_hires.png', NULL),
    (149, 'Professor Oak''s Research', 'common', 'https://images.pokemontcg.io/ecard1/149_hires.png', NULL),
    (150, 'Strength Charm', 'common', 'https://images.pokemontcg.io/ecard1/150_hires.png', NULL),
    (151, 'Super Scoop Up', 'common', 'https://images.pokemontcg.io/ecard1/151_hires.png', NULL),
    (152, 'Warp Point', 'common', 'https://images.pokemontcg.io/ecard1/152_hires.png', NULL),
    (153, 'Energy Search', 'common', 'https://images.pokemontcg.io/ecard1/153_hires.png', NULL),
    (154, 'Full Heal', 'common', 'https://images.pokemontcg.io/ecard1/154_hires.png', NULL),
    (155, 'Moo-Moo Milk', 'common', 'https://images.pokemontcg.io/ecard1/155_hires.png', NULL),
    (156, 'Potion', 'common', 'https://images.pokemontcg.io/ecard1/156_hires.png', NULL),
    (157, 'Switch', 'common', 'https://images.pokemontcg.io/ecard1/157_hires.png', NULL),
    (158, 'Darkness Energy', 'rare', 'https://images.pokemontcg.io/ecard1/158_hires.png', NULL),
    (159, 'Metal Energy', 'rare', 'https://images.pokemontcg.io/ecard1/159_hires.png', NULL),
    (160, 'Fighting Energy', 'base', 'https://images.pokemontcg.io/ecard1/160_hires.png', NULL),
    (161, 'Fire Energy', 'base', 'https://images.pokemontcg.io/ecard1/161_hires.png', NULL),
    (162, 'Grass Energy', 'base', 'https://images.pokemontcg.io/ecard1/162_hires.png', NULL),
    (163, 'Lightning Energy', 'base', 'https://images.pokemontcg.io/ecard1/163_hires.png', NULL),
    (164, 'Psychic Energy', 'base', 'https://images.pokemontcg.io/ecard1/164_hires.png', NULL),
    (165, 'Water Energy', 'base', 'https://images.pokemontcg.io/ecard1/165_hires.png', NULL)
  ) as v(number, name, rarity, image_url, pokemon_type)
  on conflict (set_id, number) do nothing
  returning id, rarity
)
insert into card_variants (card_id, variant, price_sek, stock)
select ic.id, x.variant, 0, 0
from inserted_cards ic
cross join lateral (
  select case when ic.rarity = 'rare' then 'holo' else 'normal' end as variant
  union all
  select 'reverse_holo' where ic.rarity in ('common','rare')
) as x(variant)
on conflict (card_id, variant) do nothing;

-- Set: Aquapolis (ecard2) -- 2003/01/15
insert into sets (category_slug, category_name, slug, name, is_visible)
  values ('e-card', 'E-Card', 'aquapolis', 'Aquapolis', false)
  on conflict (slug) do nothing;

with s as (select id from sets where slug = 'aquapolis'),
inserted_cards as (
  insert into cards (set_id, number, name, rarity, image_url, pokemon_type)
  select s.id, v.number, v.name, v.rarity, v.image_url, v.pokemon_type
  from s, (values
    (1, 'Ampharos', 'rare', 'https://images.pokemontcg.io/ecard2/1_hires.png', 'lightning'),
    (2, 'Arcanine', 'rare', 'https://images.pokemontcg.io/ecard2/2_hires.png', 'fire'),
    (3, 'Ariados', 'rare', 'https://images.pokemontcg.io/ecard2/3_hires.png', 'grass'),
    (4, 'Azumarill', 'rare', 'https://images.pokemontcg.io/ecard2/4_hires.png', 'water'),
    (5, 'Bellossom', 'rare', 'https://images.pokemontcg.io/ecard2/5_hires.png', 'grass'),
    (6, 'Blissey', 'rare', 'https://images.pokemontcg.io/ecard2/6_hires.png', 'colorless'),
    (7, 'Donphan', 'rare', 'https://images.pokemontcg.io/ecard2/7_hires.png', 'fighting'),
    (8, 'Electrode', 'rare', 'https://images.pokemontcg.io/ecard2/8_hires.png', 'lightning'),
    (9, 'Elekid', 'rare', 'https://images.pokemontcg.io/ecard2/9_hires.png', 'lightning'),
    (10, 'Entei', 'rare', 'https://images.pokemontcg.io/ecard2/10_hires.png', 'fire'),
    (11, 'Espeon', 'rare', 'https://images.pokemontcg.io/ecard2/11_hires.png', 'psychic'),
    (12, 'Exeggutor', 'rare', 'https://images.pokemontcg.io/ecard2/12_hires.png', 'grass'),
    (13, 'Exeggutor', 'rare', 'https://images.pokemontcg.io/ecard2/13_hires.png', 'psychic'),
    (14, 'Houndoom', 'rare', 'https://images.pokemontcg.io/ecard2/14_hires.png', 'fire'),
    (15, 'Houndoom', 'rare', 'https://images.pokemontcg.io/ecard2/15_hires.png', 'darkness'),
    (16, 'Hypno', 'rare', 'https://images.pokemontcg.io/ecard2/16_hires.png', 'psychic'),
    (17, 'Jumpluff', 'rare', 'https://images.pokemontcg.io/ecard2/17_hires.png', 'grass'),
    (18, 'Jynx', 'rare', 'https://images.pokemontcg.io/ecard2/18_hires.png', 'psychic'),
    (19, 'Kingdra', 'rare', 'https://images.pokemontcg.io/ecard2/19_hires.png', 'water'),
    (20, 'Lanturn', 'rare', 'https://images.pokemontcg.io/ecard2/20_hires.png', 'water'),
    (21, 'Lanturn', 'rare', 'https://images.pokemontcg.io/ecard2/21_hires.png', 'lightning'),
    (22, 'Magneton', 'rare', 'https://images.pokemontcg.io/ecard2/22_hires.png', 'metal'),
    (23, 'Muk', 'rare', 'https://images.pokemontcg.io/ecard2/23_hires.png', 'grass'),
    (24, 'Nidoking', 'rare', 'https://images.pokemontcg.io/ecard2/24_hires.png', 'fighting'),
    (25, 'Ninetales', 'rare', 'https://images.pokemontcg.io/ecard2/25_hires.png', 'fire'),
    (26, 'Octillery', 'rare', 'https://images.pokemontcg.io/ecard2/26_hires.png', 'water'),
    (27, 'Parasect', 'rare', 'https://images.pokemontcg.io/ecard2/27_hires.png', 'grass'),
    (28, 'Porygon2', 'rare', 'https://images.pokemontcg.io/ecard2/28_hires.png', 'colorless'),
    (29, 'Primeape', 'rare', 'https://images.pokemontcg.io/ecard2/29_hires.png', 'fighting'),
    (30, 'Quagsire', 'rare', 'https://images.pokemontcg.io/ecard2/30_hires.png', 'water'),
    (31, 'Rapidash', 'rare', 'https://images.pokemontcg.io/ecard2/31_hires.png', 'fire'),
    (32, 'Scizor', 'rare', 'https://images.pokemontcg.io/ecard2/32_hires.png', 'metal'),
    (33, 'Slowbro', 'rare', 'https://images.pokemontcg.io/ecard2/33_hires.png', 'water'),
    (34, 'Slowking', 'rare', 'https://images.pokemontcg.io/ecard2/34_hires.png', 'psychic'),
    (35, 'Steelix', 'rare', 'https://images.pokemontcg.io/ecard2/35_hires.png', 'metal'),
    (36, 'Sudowoodo', 'rare', 'https://images.pokemontcg.io/ecard2/36_hires.png', 'fighting'),
    (37, 'Suicune', 'rare', 'https://images.pokemontcg.io/ecard2/37_hires.png', 'water'),
    (38, 'Tentacruel', 'rare', 'https://images.pokemontcg.io/ecard2/38_hires.png', 'water'),
    (39, 'Togetic', 'rare', 'https://images.pokemontcg.io/ecard2/39_hires.png', 'colorless'),
    (40, 'Tyranitar', 'rare', 'https://images.pokemontcg.io/ecard2/40_hires.png', 'darkness'),
    (41, 'Umbreon', 'rare', 'https://images.pokemontcg.io/ecard2/41_hires.png', 'darkness'),
    (42, 'Victreebel', 'rare', 'https://images.pokemontcg.io/ecard2/42_hires.png', 'grass'),
    (43, 'Vileplume', 'rare', 'https://images.pokemontcg.io/ecard2/43_hires.png', 'grass'),
    (44, 'Zapdos', 'rare', 'https://images.pokemontcg.io/ecard2/44_hires.png', 'lightning'),
    (45, 'Bellsprout', 'common', 'https://images.pokemontcg.io/ecard2/45_hires.png', 'grass'),
    (46, 'Dodrio', 'common', 'https://images.pokemontcg.io/ecard2/46_hires.png', 'colorless'),
    (47, 'Flaaffy', 'common', 'https://images.pokemontcg.io/ecard2/47_hires.png', 'lightning'),
    (48, 'Furret', 'common', 'https://images.pokemontcg.io/ecard2/48_hires.png', 'colorless'),
    (49, 'Gloom', 'common', 'https://images.pokemontcg.io/ecard2/49_hires.png', 'grass'),
    (50, 'Golduck', 'common', 'https://images.pokemontcg.io/ecard2/50_hires.png', 'water'),
    (51, 'Growlithe', 'common', 'https://images.pokemontcg.io/ecard2/51_hires.png', 'fire'),
    (52, 'Magnemite', 'common', 'https://images.pokemontcg.io/ecard2/52_hires.png', 'metal'),
    (53, 'Marill', 'common', 'https://images.pokemontcg.io/ecard2/53_hires.png', 'water'),
    (54, 'Marowak', 'common', 'https://images.pokemontcg.io/ecard2/54_hires.png', 'fighting'),
    (55, 'Nidorino', 'common', 'https://images.pokemontcg.io/ecard2/55_hires.png', 'grass'),
    (56, 'Pupitar', 'common', 'https://images.pokemontcg.io/ecard2/56_hires.png', 'fighting'),
    (57, 'Scyther', 'common', 'https://images.pokemontcg.io/ecard2/57_hires.png', 'grass'),
    (58, 'Seadra', 'common', 'https://images.pokemontcg.io/ecard2/58_hires.png', 'water'),
    (59, 'Seaking', 'common', 'https://images.pokemontcg.io/ecard2/59_hires.png', 'water'),
    (60, 'Skiploom', 'common', 'https://images.pokemontcg.io/ecard2/60_hires.png', 'grass'),
    (61, 'Smoochum', 'common', 'https://images.pokemontcg.io/ecard2/61_hires.png', 'psychic'),
    (62, 'Spinarak', 'common', 'https://images.pokemontcg.io/ecard2/62_hires.png', 'grass'),
    (63, 'Tyrogue', 'common', 'https://images.pokemontcg.io/ecard2/63_hires.png', 'fighting'),
    (64, 'Voltorb', 'common', 'https://images.pokemontcg.io/ecard2/64_hires.png', 'lightning'),
    (65, 'Weepinbell', 'common', 'https://images.pokemontcg.io/ecard2/65_hires.png', 'grass'),
    (66, 'Wooper', 'common', 'https://images.pokemontcg.io/ecard2/66_hires.png', 'water'),
    (67, 'Aipom', 'common', 'https://images.pokemontcg.io/ecard2/67_hires.png', 'colorless'),
    (68, 'Bellsprout', 'common', 'https://images.pokemontcg.io/ecard2/68_hires.png', 'grass'),
    (69, 'Chansey', 'common', 'https://images.pokemontcg.io/ecard2/69_hires.png', 'colorless'),
    (70, 'Chinchou', 'common', 'https://images.pokemontcg.io/ecard2/70_hires.png', 'water'),
    (71, 'Chinchou', 'common', 'https://images.pokemontcg.io/ecard2/71_hires.png', 'lightning'),
    (72, 'Cubone', 'common', 'https://images.pokemontcg.io/ecard2/72_hires.png', 'fighting'),
    (73, 'Doduo', 'common', 'https://images.pokemontcg.io/ecard2/73_hires.png', 'colorless'),
    (74, 'Drowzee', 'common', 'https://images.pokemontcg.io/ecard2/74_hires.png', 'psychic'),
    (75, 'Eevee', 'common', 'https://images.pokemontcg.io/ecard2/75_hires.png', 'colorless'),
    (76, 'Exeggcute', 'common', 'https://images.pokemontcg.io/ecard2/76_hires.png', 'grass'),
    (77, 'Exeggcute', 'common', 'https://images.pokemontcg.io/ecard2/77_hires.png', 'psychic'),
    (78, 'Goldeen', 'common', 'https://images.pokemontcg.io/ecard2/78_hires.png', 'water'),
    (79, 'Grimer', 'common', 'https://images.pokemontcg.io/ecard2/79_hires.png', 'grass'),
    (80, 'Growlithe', 'common', 'https://images.pokemontcg.io/ecard2/80_hires.png', 'fire'),
    (81, 'Hitmonchan', 'common', 'https://images.pokemontcg.io/ecard2/81_hires.png', 'fighting'),
    (82, 'Hitmontop', 'common', 'https://images.pokemontcg.io/ecard2/82_hires.png', 'fighting'),
    (83, 'Hoppip', 'common', 'https://images.pokemontcg.io/ecard2/83_hires.png', 'grass'),
    (84, 'Horsea', 'common', 'https://images.pokemontcg.io/ecard2/84_hires.png', 'water'),
    (85, 'Horsea', 'common', 'https://images.pokemontcg.io/ecard2/85_hires.png', 'water'),
    (86, 'Houndour', 'common', 'https://images.pokemontcg.io/ecard2/86_hires.png', 'fire'),
    (87, 'Houndour', 'common', 'https://images.pokemontcg.io/ecard2/87_hires.png', 'darkness'),
    (88, 'Kangaskhan', 'common', 'https://images.pokemontcg.io/ecard2/88_hires.png', 'colorless'),
    (89, 'Larvitar', 'common', 'https://images.pokemontcg.io/ecard2/89_hires.png', 'fighting'),
    (90, 'Lickitung', 'common', 'https://images.pokemontcg.io/ecard2/90_hires.png', 'colorless'),
    (91, 'Magnemite', 'common', 'https://images.pokemontcg.io/ecard2/91_hires.png', 'lightning'),
    (92, 'Mankey', 'common', 'https://images.pokemontcg.io/ecard2/92_hires.png', 'fighting'),
    (93, 'Mareep', 'common', 'https://images.pokemontcg.io/ecard2/93_hires.png', 'lightning'),
    (94, 'Miltank', 'common', 'https://images.pokemontcg.io/ecard2/94_hires.png', 'colorless'),
    (95, 'Mr. Mime', 'common', 'https://images.pokemontcg.io/ecard2/95_hires.png', 'psychic'),
    (96, 'Nidoran ♂', 'common', 'https://images.pokemontcg.io/ecard2/96_hires.png', 'grass'),
    (97, 'Oddish', 'common', 'https://images.pokemontcg.io/ecard2/97_hires.png', 'grass'),
    (98, 'Onix', 'common', 'https://images.pokemontcg.io/ecard2/98_hires.png', 'fighting'),
    (99, 'Paras', 'common', 'https://images.pokemontcg.io/ecard2/99_hires.png', 'grass'),
    (100, 'Phanpy', 'common', 'https://images.pokemontcg.io/ecard2/100_hires.png', 'fighting'),
    (101, 'Pinsir', 'common', 'https://images.pokemontcg.io/ecard2/101_hires.png', 'grass'),
    (102, 'Ponyta', 'common', 'https://images.pokemontcg.io/ecard2/102_hires.png', 'fire'),
    (103, 'Porygon', 'common', 'https://images.pokemontcg.io/ecard2/103_hires.png', 'colorless'),
    (104, 'Psyduck', 'common', 'https://images.pokemontcg.io/ecard2/104_hires.png', 'water'),
    (105, 'Remoraid', 'common', 'https://images.pokemontcg.io/ecard2/105_hires.png', 'water'),
    (106, 'Scyther', 'common', 'https://images.pokemontcg.io/ecard2/106_hires.png', 'grass'),
    (107, 'Sentret', 'common', 'https://images.pokemontcg.io/ecard2/107_hires.png', 'colorless'),
    (108, 'Slowpoke', 'common', 'https://images.pokemontcg.io/ecard2/108_hires.png', 'water'),
    (109, 'Smeargle', 'common', 'https://images.pokemontcg.io/ecard2/109_hires.png', 'colorless'),
    (110, 'Sneasel', 'common', 'https://images.pokemontcg.io/ecard2/110_hires.png', 'darkness'),
    (111, 'Spinarak', 'common', 'https://images.pokemontcg.io/ecard2/111_hires.png', 'grass'),
    (112, 'Tangela', 'common', 'https://images.pokemontcg.io/ecard2/112_hires.png', 'grass'),
    (113, 'Tentacool', 'common', 'https://images.pokemontcg.io/ecard2/113_hires.png', 'water'),
    (114, 'Togepi', 'common', 'https://images.pokemontcg.io/ecard2/114_hires.png', 'colorless'),
    (115, 'Voltorb', 'common', 'https://images.pokemontcg.io/ecard2/115_hires.png', 'lightning'),
    (116, 'Vulpix', 'common', 'https://images.pokemontcg.io/ecard2/116_hires.png', 'fire'),
    (117, 'Wooper', 'common', 'https://images.pokemontcg.io/ecard2/117_hires.png', 'water'),
    (118, 'Apricorn Forest', 'rare', 'https://images.pokemontcg.io/ecard2/118_hires.png', NULL),
    (119, 'Darkness Cube 01', 'common', 'https://images.pokemontcg.io/ecard2/119_hires.png', NULL),
    (120, 'Energy Switch', 'common', 'https://images.pokemontcg.io/ecard2/120_hires.png', NULL),
    (121, 'Fighting Cube 01', 'common', 'https://images.pokemontcg.io/ecard2/121_hires.png', NULL),
    (122, 'Fire Cube 01', 'common', 'https://images.pokemontcg.io/ecard2/122_hires.png', NULL),
    (123, 'Forest Guardian', 'common', 'https://images.pokemontcg.io/ecard2/123_hires.png', NULL),
    (124, 'Grass Cube 01', 'common', 'https://images.pokemontcg.io/ecard2/124_hires.png', NULL),
    (125, 'Healing Berry', 'common', 'https://images.pokemontcg.io/ecard2/125_hires.png', NULL),
    (126, 'Juggler', 'common', 'https://images.pokemontcg.io/ecard2/126_hires.png', NULL),
    (127, 'Lightning Cube 01', 'common', 'https://images.pokemontcg.io/ecard2/127_hires.png', NULL),
    (128, 'Memory Berry', 'common', 'https://images.pokemontcg.io/ecard2/128_hires.png', NULL),
    (129, 'Metal Cube 01', 'common', 'https://images.pokemontcg.io/ecard2/129_hires.png', NULL),
    (130, 'Pokémon Fan Club', 'common', 'https://images.pokemontcg.io/ecard2/130_hires.png', NULL),
    (131, 'Pokémon Park', 'common', 'https://images.pokemontcg.io/ecard2/131_hires.png', NULL),
    (132, 'Psychic Cube 01', 'common', 'https://images.pokemontcg.io/ecard2/132_hires.png', NULL),
    (133, 'Seer', 'common', 'https://images.pokemontcg.io/ecard2/133_hires.png', NULL),
    (134, 'Super Energy Removal 2', 'common', 'https://images.pokemontcg.io/ecard2/134_hires.png', NULL),
    (135, 'Time Shard', 'common', 'https://images.pokemontcg.io/ecard2/135_hires.png', NULL),
    (136, 'Town Volunteers', 'common', 'https://images.pokemontcg.io/ecard2/136_hires.png', NULL),
    (137, 'Traveling Salesman', 'common', 'https://images.pokemontcg.io/ecard2/137_hires.png', NULL),
    (138, 'Undersea Ruins', 'common', 'https://images.pokemontcg.io/ecard2/138_hires.png', NULL),
    (139, 'Power Plant', 'common', 'https://images.pokemontcg.io/ecard2/139_hires.png', NULL),
    (140, 'Water Cube 01', 'common', 'https://images.pokemontcg.io/ecard2/140_hires.png', NULL),
    (141, 'Weakness Guard', 'common', 'https://images.pokemontcg.io/ecard2/141_hires.png', NULL),
    (142, 'Darkness Energy', 'rare', 'https://images.pokemontcg.io/ecard2/142_hires.png', NULL),
    (143, 'Metal Energy', 'rare', 'https://images.pokemontcg.io/ecard2/143_hires.png', NULL),
    (144, 'Rainbow Energy', 'rare', 'https://images.pokemontcg.io/ecard2/144_hires.png', NULL),
    (145, 'Boost Energy', 'common', 'https://images.pokemontcg.io/ecard2/145_hires.png', NULL),
    (146, 'Crystal Energy', 'common', 'https://images.pokemontcg.io/ecard2/146_hires.png', NULL),
    (147, 'Warp Energy', 'common', 'https://images.pokemontcg.io/ecard2/147_hires.png', NULL),
    (148, 'Kingdra', 'mega_hyper_rare', 'https://images.pokemontcg.io/ecard2/148_hires.png', 'colorless'),
    (149, 'Lugia', 'mega_hyper_rare', 'https://images.pokemontcg.io/ecard2/149_hires.png', 'colorless'),
    (150, 'Nidoking', 'mega_hyper_rare', 'https://images.pokemontcg.io/ecard2/150_hires.png', 'colorless'),
    (501001, 'Ampharos', 'rare', 'https://images.pokemontcg.io/ecard2/H1_hires.png', 'lightning'),
    (501002, 'Arcanine', 'rare', 'https://images.pokemontcg.io/ecard2/H2_hires.png', 'fire'),
    (501003, 'Ariados', 'rare', 'https://images.pokemontcg.io/ecard2/H3_hires.png', 'grass'),
    (501004, 'Azumarill', 'rare', 'https://images.pokemontcg.io/ecard2/H4_hires.png', 'water'),
    (501005, 'Bellossom', 'rare', 'https://images.pokemontcg.io/ecard2/H5_hires.png', 'grass'),
    (501006, 'Blissey', 'rare', 'https://images.pokemontcg.io/ecard2/H6_hires.png', 'colorless'),
    (501007, 'Electrode', 'rare', 'https://images.pokemontcg.io/ecard2/H7_hires.png', 'lightning'),
    (501008, 'Entei', 'rare', 'https://images.pokemontcg.io/ecard2/H8_hires.png', 'fire'),
    (501009, 'Espeon', 'rare', 'https://images.pokemontcg.io/ecard2/H9_hires.png', 'psychic'),
    (501010, 'Exeggutor', 'rare', 'https://images.pokemontcg.io/ecard2/H10_hires.png', 'grass'),
    (501011, 'Houndoom', 'rare', 'https://images.pokemontcg.io/ecard2/H11_hires.png', 'darkness'),
    (501012, 'Hypno', 'rare', 'https://images.pokemontcg.io/ecard2/H12_hires.png', 'psychic'),
    (501013, 'Jumpluff', 'rare', 'https://images.pokemontcg.io/ecard2/H13_hires.png', 'grass'),
    (501014, 'Kingdra', 'rare', 'https://images.pokemontcg.io/ecard2/H14_hires.png', 'water'),
    (501015, 'Lanturn', 'rare', 'https://images.pokemontcg.io/ecard2/H15_hires.png', 'lightning'),
    (501016, 'Magneton', 'rare', 'https://images.pokemontcg.io/ecard2/H16_hires.png', 'metal'),
    (501017, 'Muk', 'rare', 'https://images.pokemontcg.io/ecard2/H17_hires.png', 'grass'),
    (501018, 'Nidoking', 'rare', 'https://images.pokemontcg.io/ecard2/H18_hires.png', 'fighting'),
    (501019, 'Ninetales', 'rare', 'https://images.pokemontcg.io/ecard2/H19_hires.png', 'fire'),
    (501020, 'Octillery', 'rare', 'https://images.pokemontcg.io/ecard2/H20_hires.png', 'water'),
    (501021, 'Scizor', 'rare', 'https://images.pokemontcg.io/ecard2/H21_hires.png', 'metal'),
    (501022, 'Slowking', 'rare', 'https://images.pokemontcg.io/ecard2/H22_hires.png', 'psychic'),
    (501023, 'Steelix', 'rare', 'https://images.pokemontcg.io/ecard2/H23_hires.png', 'metal'),
    (501024, 'Sudowoodo', 'rare', 'https://images.pokemontcg.io/ecard2/H24_hires.png', 'fighting'),
    (501025, 'Suicune', 'rare', 'https://images.pokemontcg.io/ecard2/H25_hires.png', 'water'),
    (501026, 'Tentacruel', 'rare', 'https://images.pokemontcg.io/ecard2/H26_hires.png', 'water'),
    (501027, 'Togetic', 'rare', 'https://images.pokemontcg.io/ecard2/H27_hires.png', 'colorless'),
    (501028, 'Tyranitar', 'rare', 'https://images.pokemontcg.io/ecard2/H28_hires.png', 'darkness'),
    (501029, 'Umbreon', 'rare', 'https://images.pokemontcg.io/ecard2/H29_hires.png', 'darkness'),
    (501030, 'Victreebel', 'rare', 'https://images.pokemontcg.io/ecard2/H30_hires.png', 'grass'),
    (501031, 'Vileplume', 'rare', 'https://images.pokemontcg.io/ecard2/H31_hires.png', 'grass'),
    (501032, 'Zapdos', 'rare', 'https://images.pokemontcg.io/ecard2/H32_hires.png', 'lightning')
  ) as v(number, name, rarity, image_url, pokemon_type)
  on conflict (set_id, number) do nothing
  returning id, rarity
)
insert into card_variants (card_id, variant, price_sek, stock)
select ic.id, x.variant, 0, 0
from inserted_cards ic
cross join lateral (
  select case when ic.rarity = 'rare' then 'holo' else 'normal' end as variant
  union all
  select 'reverse_holo' where ic.rarity in ('common','rare')
) as x(variant)
on conflict (card_id, variant) do nothing;

-- Set: Skyridge (ecard3) -- 2003/05/12
insert into sets (category_slug, category_name, slug, name, is_visible)
  values ('e-card', 'E-Card', 'skyridge', 'Skyridge', false)
  on conflict (slug) do nothing;

with s as (select id from sets where slug = 'skyridge'),
inserted_cards as (
  insert into cards (set_id, number, name, rarity, image_url, pokemon_type)
  select s.id, v.number, v.name, v.rarity, v.image_url, v.pokemon_type
  from s, (values
    (1, 'Aerodactyl', 'rare', 'https://images.pokemontcg.io/ecard3/1_hires.png', 'fighting'),
    (2, 'Alakazam', 'rare', 'https://images.pokemontcg.io/ecard3/2_hires.png', 'psychic'),
    (3, 'Arcanine', 'rare', 'https://images.pokemontcg.io/ecard3/3_hires.png', 'fire'),
    (4, 'Articuno', 'rare', 'https://images.pokemontcg.io/ecard3/4_hires.png', 'water'),
    (5, 'Beedrill', 'rare', 'https://images.pokemontcg.io/ecard3/5_hires.png', 'grass'),
    (6, 'Crobat', 'rare', 'https://images.pokemontcg.io/ecard3/6_hires.png', 'grass'),
    (7, 'Dewgong', 'rare', 'https://images.pokemontcg.io/ecard3/7_hires.png', 'water'),
    (8, 'Flareon', 'rare', 'https://images.pokemontcg.io/ecard3/8_hires.png', 'fire'),
    (9, 'Forretress', 'rare', 'https://images.pokemontcg.io/ecard3/9_hires.png', 'metal'),
    (10, 'Gengar', 'rare', 'https://images.pokemontcg.io/ecard3/10_hires.png', 'psychic'),
    (11, 'Gyarados', 'rare', 'https://images.pokemontcg.io/ecard3/11_hires.png', 'water'),
    (12, 'Houndoom', 'rare', 'https://images.pokemontcg.io/ecard3/12_hires.png', 'darkness'),
    (13, 'Jolteon', 'rare', 'https://images.pokemontcg.io/ecard3/13_hires.png', 'lightning'),
    (14, 'Kabutops', 'rare', 'https://images.pokemontcg.io/ecard3/14_hires.png', 'fighting'),
    (15, 'Ledian', 'rare', 'https://images.pokemontcg.io/ecard3/15_hires.png', 'grass'),
    (16, 'Machamp', 'rare', 'https://images.pokemontcg.io/ecard3/16_hires.png', 'fighting'),
    (17, 'Magcargo', 'rare', 'https://images.pokemontcg.io/ecard3/17_hires.png', 'fire'),
    (18, 'Magcargo', 'rare', 'https://images.pokemontcg.io/ecard3/18_hires.png', 'fighting'),
    (19, 'Magneton', 'rare', 'https://images.pokemontcg.io/ecard3/19_hires.png', 'lightning'),
    (20, 'Magneton', 'rare', 'https://images.pokemontcg.io/ecard3/20_hires.png', 'metal'),
    (21, 'Moltres', 'rare', 'https://images.pokemontcg.io/ecard3/21_hires.png', 'fire'),
    (22, 'Nidoqueen', 'rare', 'https://images.pokemontcg.io/ecard3/22_hires.png', 'grass'),
    (23, 'Omastar', 'rare', 'https://images.pokemontcg.io/ecard3/23_hires.png', 'water'),
    (24, 'Piloswine', 'rare', 'https://images.pokemontcg.io/ecard3/24_hires.png', 'water'),
    (25, 'Politoed', 'rare', 'https://images.pokemontcg.io/ecard3/25_hires.png', 'water'),
    (26, 'Poliwrath', 'rare', 'https://images.pokemontcg.io/ecard3/26_hires.png', 'fighting'),
    (27, 'Raichu', 'rare', 'https://images.pokemontcg.io/ecard3/27_hires.png', 'lightning'),
    (28, 'Raikou', 'rare', 'https://images.pokemontcg.io/ecard3/28_hires.png', 'lightning'),
    (29, 'Rhydon', 'rare', 'https://images.pokemontcg.io/ecard3/29_hires.png', 'fighting'),
    (30, 'Starmie', 'rare', 'https://images.pokemontcg.io/ecard3/30_hires.png', 'psychic'),
    (31, 'Steelix', 'rare', 'https://images.pokemontcg.io/ecard3/31_hires.png', 'metal'),
    (32, 'Umbreon', 'rare', 'https://images.pokemontcg.io/ecard3/32_hires.png', 'darkness'),
    (33, 'Vaporeon', 'rare', 'https://images.pokemontcg.io/ecard3/33_hires.png', 'water'),
    (34, 'Wigglytuff', 'rare', 'https://images.pokemontcg.io/ecard3/34_hires.png', 'colorless'),
    (35, 'Xatu', 'rare', 'https://images.pokemontcg.io/ecard3/35_hires.png', 'psychic'),
    (36, 'Electrode', 'common', 'https://images.pokemontcg.io/ecard3/36_hires.png', 'lightning'),
    (37, 'Kabuto', 'common', 'https://images.pokemontcg.io/ecard3/37_hires.png', 'fighting'),
    (38, 'Machoke', 'common', 'https://images.pokemontcg.io/ecard3/38_hires.png', 'fighting'),
    (39, 'Misdreavus', 'common', 'https://images.pokemontcg.io/ecard3/39_hires.png', 'psychic'),
    (40, 'Noctowl', 'common', 'https://images.pokemontcg.io/ecard3/40_hires.png', 'colorless'),
    (41, 'Omanyte', 'common', 'https://images.pokemontcg.io/ecard3/41_hires.png', 'water'),
    (42, 'Persian', 'common', 'https://images.pokemontcg.io/ecard3/42_hires.png', 'colorless'),
    (43, 'Piloswine', 'common', 'https://images.pokemontcg.io/ecard3/43_hires.png', 'fighting'),
    (44, 'Starmie', 'common', 'https://images.pokemontcg.io/ecard3/44_hires.png', 'water'),
    (45, 'Wobbuffet', 'common', 'https://images.pokemontcg.io/ecard3/45_hires.png', 'psychic'),
    (46, 'Abra', 'common', 'https://images.pokemontcg.io/ecard3/46_hires.png', 'psychic'),
    (47, 'Buried Fossil', 'common', 'https://images.pokemontcg.io/ecard3/47_hires.png', 'colorless'),
    (48, 'Cleffa', 'common', 'https://images.pokemontcg.io/ecard3/48_hires.png', 'colorless'),
    (49, 'Delibird', 'common', 'https://images.pokemontcg.io/ecard3/49_hires.png', 'water'),
    (50, 'Diglett', 'common', 'https://images.pokemontcg.io/ecard3/50_hires.png', 'fighting'),
    (51, 'Ditto', 'common', 'https://images.pokemontcg.io/ecard3/51_hires.png', 'colorless'),
    (52, 'Dugtrio', 'common', 'https://images.pokemontcg.io/ecard3/52_hires.png', 'fighting'),
    (53, 'Dunsparce', 'common', 'https://images.pokemontcg.io/ecard3/53_hires.png', 'colorless'),
    (54, 'Eevee', 'common', 'https://images.pokemontcg.io/ecard3/54_hires.png', 'colorless'),
    (55, 'Farfetch''d', 'common', 'https://images.pokemontcg.io/ecard3/55_hires.png', 'colorless'),
    (56, 'Forretress', 'common', 'https://images.pokemontcg.io/ecard3/56_hires.png', 'grass'),
    (57, 'Gastly', 'common', 'https://images.pokemontcg.io/ecard3/57_hires.png', 'psychic'),
    (58, 'Girafarig', 'common', 'https://images.pokemontcg.io/ecard3/58_hires.png', 'psychic'),
    (59, 'Gligar', 'common', 'https://images.pokemontcg.io/ecard3/59_hires.png', 'fighting'),
    (60, 'Golbat', 'common', 'https://images.pokemontcg.io/ecard3/60_hires.png', 'grass'),
    (61, 'Granbull', 'common', 'https://images.pokemontcg.io/ecard3/61_hires.png', 'colorless'),
    (62, 'Growlithe', 'common', 'https://images.pokemontcg.io/ecard3/62_hires.png', 'fire'),
    (63, 'Haunter', 'common', 'https://images.pokemontcg.io/ecard3/63_hires.png', 'psychic'),
    (64, 'Heracross', 'common', 'https://images.pokemontcg.io/ecard3/64_hires.png', 'grass'),
    (65, 'Hoothoot', 'common', 'https://images.pokemontcg.io/ecard3/65_hires.png', 'colorless'),
    (66, 'Houndour', 'common', 'https://images.pokemontcg.io/ecard3/66_hires.png', 'fire'),
    (67, 'Igglybuff', 'common', 'https://images.pokemontcg.io/ecard3/67_hires.png', 'colorless'),
    (68, 'Jigglypuff', 'common', 'https://images.pokemontcg.io/ecard3/68_hires.png', 'colorless'),
    (69, 'Kadabra', 'common', 'https://images.pokemontcg.io/ecard3/69_hires.png', 'psychic'),
    (70, 'Kakuna', 'common', 'https://images.pokemontcg.io/ecard3/70_hires.png', 'grass'),
    (71, 'Lapras', 'common', 'https://images.pokemontcg.io/ecard3/71_hires.png', 'water'),
    (72, 'Ledyba', 'common', 'https://images.pokemontcg.io/ecard3/72_hires.png', 'grass'),
    (73, 'Ledyba', 'common', 'https://images.pokemontcg.io/ecard3/73_hires.png', 'grass'),
    (74, 'Machop', 'common', 'https://images.pokemontcg.io/ecard3/74_hires.png', 'fighting'),
    (75, 'Magikarp', 'common', 'https://images.pokemontcg.io/ecard3/75_hires.png', 'water'),
    (76, 'Magnemite', 'common', 'https://images.pokemontcg.io/ecard3/76_hires.png', 'lightning'),
    (77, 'Mantine', 'common', 'https://images.pokemontcg.io/ecard3/77_hires.png', 'water'),
    (78, 'Meowth', 'common', 'https://images.pokemontcg.io/ecard3/78_hires.png', 'colorless'),
    (79, 'Murkrow', 'common', 'https://images.pokemontcg.io/ecard3/79_hires.png', 'darkness'),
    (80, 'Natu', 'common', 'https://images.pokemontcg.io/ecard3/80_hires.png', 'psychic'),
    (81, 'Nidoran ♀', 'common', 'https://images.pokemontcg.io/ecard3/81_hires.png', 'grass'),
    (82, 'Nidoran ♀', 'common', 'https://images.pokemontcg.io/ecard3/82_hires.png', 'grass'),
    (83, 'Nidorina', 'common', 'https://images.pokemontcg.io/ecard3/83_hires.png', 'grass'),
    (84, 'Pikachu', 'common', 'https://images.pokemontcg.io/ecard3/84_hires.png', 'lightning'),
    (85, 'Pineco', 'common', 'https://images.pokemontcg.io/ecard3/85_hires.png', 'grass'),
    (86, 'Pineco', 'common', 'https://images.pokemontcg.io/ecard3/86_hires.png', 'grass'),
    (87, 'Poliwag', 'common', 'https://images.pokemontcg.io/ecard3/87_hires.png', 'water'),
    (88, 'Poliwhirl', 'common', 'https://images.pokemontcg.io/ecard3/88_hires.png', 'water'),
    (89, 'Raticate', 'common', 'https://images.pokemontcg.io/ecard3/89_hires.png', 'colorless'),
    (90, 'Rattata', 'common', 'https://images.pokemontcg.io/ecard3/90_hires.png', 'colorless'),
    (91, 'Rhyhorn', 'common', 'https://images.pokemontcg.io/ecard3/91_hires.png', 'fighting'),
    (92, 'Sandshrew', 'common', 'https://images.pokemontcg.io/ecard3/92_hires.png', 'fighting'),
    (93, 'Sandslash', 'common', 'https://images.pokemontcg.io/ecard3/93_hires.png', 'fighting'),
    (94, 'Seel', 'common', 'https://images.pokemontcg.io/ecard3/94_hires.png', 'water'),
    (95, 'Seel', 'common', 'https://images.pokemontcg.io/ecard3/95_hires.png', 'water'),
    (96, 'Shuckle', 'common', 'https://images.pokemontcg.io/ecard3/96_hires.png', 'grass'),
    (97, 'Skarmory', 'common', 'https://images.pokemontcg.io/ecard3/97_hires.png', 'metal'),
    (98, 'Slugma', 'common', 'https://images.pokemontcg.io/ecard3/98_hires.png', 'fire'),
    (99, 'Slugma', 'common', 'https://images.pokemontcg.io/ecard3/99_hires.png', 'fire'),
    (100, 'Snorlax', 'common', 'https://images.pokemontcg.io/ecard3/100_hires.png', 'colorless'),
    (101, 'Snubbull', 'common', 'https://images.pokemontcg.io/ecard3/101_hires.png', 'colorless'),
    (102, 'Stantler', 'common', 'https://images.pokemontcg.io/ecard3/102_hires.png', 'colorless'),
    (103, 'Staryu', 'common', 'https://images.pokemontcg.io/ecard3/103_hires.png', 'water'),
    (104, 'Staryu', 'common', 'https://images.pokemontcg.io/ecard3/104_hires.png', 'water'),
    (105, 'Sunflora', 'common', 'https://images.pokemontcg.io/ecard3/105_hires.png', 'grass'),
    (106, 'Sunkern', 'common', 'https://images.pokemontcg.io/ecard3/106_hires.png', 'grass'),
    (107, 'Swinub', 'common', 'https://images.pokemontcg.io/ecard3/107_hires.png', 'water'),
    (108, 'Swinub', 'common', 'https://images.pokemontcg.io/ecard3/108_hires.png', 'fighting'),
    (109, 'Teddiursa', 'common', 'https://images.pokemontcg.io/ecard3/109_hires.png', 'colorless'),
    (110, 'Ursaring', 'common', 'https://images.pokemontcg.io/ecard3/110_hires.png', 'colorless'),
    (111, 'Venomoth', 'common', 'https://images.pokemontcg.io/ecard3/111_hires.png', 'grass'),
    (112, 'Venonat', 'common', 'https://images.pokemontcg.io/ecard3/112_hires.png', 'grass'),
    (113, 'Voltorb', 'common', 'https://images.pokemontcg.io/ecard3/113_hires.png', 'lightning'),
    (114, 'Weedle', 'common', 'https://images.pokemontcg.io/ecard3/114_hires.png', 'grass'),
    (115, 'Weedle', 'common', 'https://images.pokemontcg.io/ecard3/115_hires.png', 'grass'),
    (116, 'Yanma', 'common', 'https://images.pokemontcg.io/ecard3/116_hires.png', 'grass'),
    (117, 'Zubat', 'common', 'https://images.pokemontcg.io/ecard3/117_hires.png', 'grass'),
    (118, 'Zubat', 'common', 'https://images.pokemontcg.io/ecard3/118_hires.png', 'grass'),
    (119, 'Ancient Ruins', 'common', 'https://images.pokemontcg.io/ecard3/119_hires.png', NULL),
    (120, 'Relic Hunter', 'common', 'https://images.pokemontcg.io/ecard3/120_hires.png', NULL),
    (121, 'Apricorn Maker', 'common', 'https://images.pokemontcg.io/ecard3/121_hires.png', NULL),
    (122, 'Crystal Shard', 'common', 'https://images.pokemontcg.io/ecard3/122_hires.png', NULL),
    (123, 'Desert Shaman', 'common', 'https://images.pokemontcg.io/ecard3/123_hires.png', NULL),
    (124, 'Fast Ball', 'common', 'https://images.pokemontcg.io/ecard3/124_hires.png', NULL),
    (125, 'Fisherman', 'common', 'https://images.pokemontcg.io/ecard3/125_hires.png', NULL),
    (126, 'Friend Ball', 'common', 'https://images.pokemontcg.io/ecard3/126_hires.png', NULL),
    (127, 'Hyper Potion', 'common', 'https://images.pokemontcg.io/ecard3/127_hires.png', NULL),
    (128, 'Lure Ball', 'common', 'https://images.pokemontcg.io/ecard3/128_hires.png', NULL),
    (129, 'Miracle Sphere α', 'common', 'https://images.pokemontcg.io/ecard3/129_hires.png', NULL),
    (130, 'Miracle Sphere β', 'common', 'https://images.pokemontcg.io/ecard3/130_hires.png', NULL),
    (131, 'Miracle Sphere γ', 'common', 'https://images.pokemontcg.io/ecard3/131_hires.png', NULL),
    (132, 'Mirage Stadium', 'common', 'https://images.pokemontcg.io/ecard3/132_hires.png', NULL),
    (133, 'Mystery Plate α', 'common', 'https://images.pokemontcg.io/ecard3/133_hires.png', NULL),
    (134, 'Mystery Plate β', 'common', 'https://images.pokemontcg.io/ecard3/134_hires.png', NULL),
    (135, 'Mystery Plate γ', 'common', 'https://images.pokemontcg.io/ecard3/135_hires.png', NULL),
    (136, 'Mystery Plate δ', 'common', 'https://images.pokemontcg.io/ecard3/136_hires.png', NULL),
    (137, 'Mystery Zone', 'common', 'https://images.pokemontcg.io/ecard3/137_hires.png', NULL),
    (138, 'Oracle', 'common', 'https://images.pokemontcg.io/ecard3/138_hires.png', NULL),
    (139, 'Star Piece', 'common', 'https://images.pokemontcg.io/ecard3/139_hires.png', NULL),
    (140, 'Underground Expedition', 'common', 'https://images.pokemontcg.io/ecard3/140_hires.png', NULL),
    (141, 'Underground Lake', 'common', 'https://images.pokemontcg.io/ecard3/141_hires.png', NULL),
    (142, 'Bounce Energy', 'common', 'https://images.pokemontcg.io/ecard3/142_hires.png', NULL),
    (143, 'Cyclone Energy', 'common', 'https://images.pokemontcg.io/ecard3/143_hires.png', NULL),
    (144, 'Retro Energy', 'common', 'https://images.pokemontcg.io/ecard3/144_hires.png', NULL),
    (145, 'Celebi', 'mega_hyper_rare', 'https://images.pokemontcg.io/ecard3/145_hires.png', 'colorless'),
    (146, 'Charizard', 'mega_hyper_rare', 'https://images.pokemontcg.io/ecard3/146_hires.png', 'colorless'),
    (147, 'Crobat', 'mega_hyper_rare', 'https://images.pokemontcg.io/ecard3/147_hires.png', 'colorless'),
    (148, 'Golem', 'mega_hyper_rare', 'https://images.pokemontcg.io/ecard3/148_hires.png', 'colorless'),
    (149, 'Ho-oh', 'mega_hyper_rare', 'https://images.pokemontcg.io/ecard3/149_hires.png', 'colorless'),
    (150, 'Kabutops', 'mega_hyper_rare', 'https://images.pokemontcg.io/ecard3/150_hires.png', 'colorless'),
    (501001, 'Alakazam', 'rare', 'https://images.pokemontcg.io/ecard3/H1_hires.png', 'psychic'),
    (501002, 'Arcanine', 'rare', 'https://images.pokemontcg.io/ecard3/H2_hires.png', 'fire'),
    (501003, 'Articuno', 'rare', 'https://images.pokemontcg.io/ecard3/H3_hires.png', 'water'),
    (501004, 'Beedrill', 'rare', 'https://images.pokemontcg.io/ecard3/H4_hires.png', 'grass'),
    (501005, 'Crobat', 'rare', 'https://images.pokemontcg.io/ecard3/H5_hires.png', 'grass'),
    (501006, 'Dewgong', 'rare', 'https://images.pokemontcg.io/ecard3/H6_hires.png', 'water'),
    (501007, 'Flareon', 'rare', 'https://images.pokemontcg.io/ecard3/H7_hires.png', 'fire'),
    (501008, 'Forretress', 'rare', 'https://images.pokemontcg.io/ecard3/H8_hires.png', 'metal'),
    (501009, 'Gengar', 'rare', 'https://images.pokemontcg.io/ecard3/H9_hires.png', 'psychic'),
    (501010, 'Gyarados', 'rare', 'https://images.pokemontcg.io/ecard3/H10_hires.png', 'water'),
    (501011, 'Houndoom', 'rare', 'https://images.pokemontcg.io/ecard3/H11_hires.png', 'darkness'),
    (501012, 'Jolteon', 'rare', 'https://images.pokemontcg.io/ecard3/H12_hires.png', 'lightning'),
    (501013, 'Kabutops', 'rare', 'https://images.pokemontcg.io/ecard3/H13_hires.png', 'fighting'),
    (501014, 'Ledian', 'rare', 'https://images.pokemontcg.io/ecard3/H14_hires.png', 'grass'),
    (501015, 'Machamp', 'rare', 'https://images.pokemontcg.io/ecard3/H15_hires.png', 'fighting'),
    (501016, 'Magcargo', 'rare', 'https://images.pokemontcg.io/ecard3/H16_hires.png', 'fire'),
    (501017, 'Magcargo', 'rare', 'https://images.pokemontcg.io/ecard3/H17_hires.png', 'fighting'),
    (501018, 'Magneton', 'rare', 'https://images.pokemontcg.io/ecard3/H18_hires.png', 'lightning'),
    (501019, 'Magneton', 'rare', 'https://images.pokemontcg.io/ecard3/H19_hires.png', 'metal'),
    (501020, 'Moltres', 'rare', 'https://images.pokemontcg.io/ecard3/H20_hires.png', 'fire'),
    (501021, 'Nidoqueen', 'rare', 'https://images.pokemontcg.io/ecard3/H21_hires.png', 'grass'),
    (501022, 'Piloswine', 'rare', 'https://images.pokemontcg.io/ecard3/H22_hires.png', 'water'),
    (501023, 'Politoed', 'rare', 'https://images.pokemontcg.io/ecard3/H23_hires.png', 'water'),
    (501024, 'Poliwrath', 'rare', 'https://images.pokemontcg.io/ecard3/H24_hires.png', 'fighting'),
    (501025, 'Raichu', 'rare', 'https://images.pokemontcg.io/ecard3/H25_hires.png', 'lightning'),
    (501026, 'Raikou', 'rare', 'https://images.pokemontcg.io/ecard3/H26_hires.png', 'lightning'),
    (501027, 'Rhydon', 'rare', 'https://images.pokemontcg.io/ecard3/H27_hires.png', 'fighting'),
    (501028, 'Starmie', 'rare', 'https://images.pokemontcg.io/ecard3/H28_hires.png', 'psychic'),
    (501029, 'Steelix', 'rare', 'https://images.pokemontcg.io/ecard3/H29_hires.png', 'metal'),
    (501030, 'Umbreon', 'rare', 'https://images.pokemontcg.io/ecard3/H30_hires.png', 'darkness'),
    (501031, 'Vaporeon', 'rare', 'https://images.pokemontcg.io/ecard3/H31_hires.png', 'water'),
    (501032, 'Xatu', 'rare', 'https://images.pokemontcg.io/ecard3/H32_hires.png', 'psychic')
  ) as v(number, name, rarity, image_url, pokemon_type)
  on conflict (set_id, number) do nothing
  returning id, rarity
)
insert into card_variants (card_id, variant, price_sek, stock)
select ic.id, x.variant, 0, 0
from inserted_cards ic
cross join lateral (
  select case when ic.rarity = 'rare' then 'holo' else 'normal' end as variant
  union all
  select 'reverse_holo' where ic.rarity in ('common','rare')
) as x(variant)
on conflict (card_id, variant) do nothing;
