-- Katalogimport: Gym (2 set)
-- Endast katalogdata (lager 0, pris 0) för portfölj/önskelista-funktionen.

-- Set: Gym Heroes (gym1) -- 2000/08/14
insert into sets (category_slug, category_name, slug, name, is_visible)
  values ('gym', 'Gym', 'gym-heroes', 'Gym Heroes', false)
  on conflict (slug) do nothing;

with s as (select id from sets where slug = 'gym-heroes'),
inserted_cards as (
  insert into cards (set_id, number, name, rarity, image_url, pokemon_type)
  select s.id, v.number, v.name, v.rarity, v.image_url, v.pokemon_type
  from s, (values
    (1, 'Blaine''s Moltres', 'rare', 'https://images.pokemontcg.io/gym1/1_hires.png', 'fire'),
    (2, 'Brock''s Rhydon', 'rare', 'https://images.pokemontcg.io/gym1/2_hires.png', 'fighting'),
    (3, 'Erika''s Clefable', 'rare', 'https://images.pokemontcg.io/gym1/3_hires.png', 'colorless'),
    (4, 'Erika''s Dragonair', 'rare', 'https://images.pokemontcg.io/gym1/4_hires.png', 'colorless'),
    (5, 'Erika''s Vileplume', 'rare', 'https://images.pokemontcg.io/gym1/5_hires.png', 'grass'),
    (6, 'Lt. Surge''s Electabuzz', 'rare', 'https://images.pokemontcg.io/gym1/6_hires.png', 'lightning'),
    (7, 'Lt. Surge''s Fearow', 'rare', 'https://images.pokemontcg.io/gym1/7_hires.png', 'colorless'),
    (8, 'Lt. Surge''s Magneton', 'rare', 'https://images.pokemontcg.io/gym1/8_hires.png', 'lightning'),
    (9, 'Misty''s Seadra', 'rare', 'https://images.pokemontcg.io/gym1/9_hires.png', 'water'),
    (10, 'Misty''s Tentacruel', 'rare', 'https://images.pokemontcg.io/gym1/10_hires.png', 'water'),
    (11, 'Rocket''s Hitmonchan', 'rare', 'https://images.pokemontcg.io/gym1/11_hires.png', 'fighting'),
    (12, 'Rocket''s Moltres', 'rare', 'https://images.pokemontcg.io/gym1/12_hires.png', 'fire'),
    (13, 'Rocket''s Scyther', 'rare', 'https://images.pokemontcg.io/gym1/13_hires.png', 'grass'),
    (14, 'Sabrina''s Gengar', 'rare', 'https://images.pokemontcg.io/gym1/14_hires.png', 'psychic'),
    (15, 'Brock', 'rare', 'https://images.pokemontcg.io/gym1/15_hires.png', NULL),
    (16, 'Erika', 'rare', 'https://images.pokemontcg.io/gym1/16_hires.png', NULL),
    (17, 'Lt. Surge', 'rare', 'https://images.pokemontcg.io/gym1/17_hires.png', NULL),
    (18, 'Misty', 'rare', 'https://images.pokemontcg.io/gym1/18_hires.png', NULL),
    (19, 'The Rocket''s Trap', 'rare', 'https://images.pokemontcg.io/gym1/19_hires.png', NULL),
    (20, 'Brock''s Golem', 'rare', 'https://images.pokemontcg.io/gym1/20_hires.png', 'fighting'),
    (21, 'Brock''s Onix', 'rare', 'https://images.pokemontcg.io/gym1/21_hires.png', 'fighting'),
    (22, 'Brock''s Rhyhorn', 'rare', 'https://images.pokemontcg.io/gym1/22_hires.png', 'fighting'),
    (23, 'Brock''s Sandslash', 'rare', 'https://images.pokemontcg.io/gym1/23_hires.png', 'fighting'),
    (24, 'Brock''s Zubat', 'rare', 'https://images.pokemontcg.io/gym1/24_hires.png', 'grass'),
    (25, 'Erika''s Clefairy', 'rare', 'https://images.pokemontcg.io/gym1/25_hires.png', 'colorless'),
    (26, 'Erika''s Victreebel', 'rare', 'https://images.pokemontcg.io/gym1/26_hires.png', 'grass'),
    (27, 'Lt. Surge''s Electabuzz', 'rare', 'https://images.pokemontcg.io/gym1/27_hires.png', 'lightning'),
    (28, 'Lt. Surge''s Raichu', 'rare', 'https://images.pokemontcg.io/gym1/28_hires.png', 'lightning'),
    (29, 'Misty''s Cloyster', 'rare', 'https://images.pokemontcg.io/gym1/29_hires.png', 'water'),
    (30, 'Misty''s Goldeen', 'rare', 'https://images.pokemontcg.io/gym1/30_hires.png', 'water'),
    (31, 'Misty''s Poliwrath', 'rare', 'https://images.pokemontcg.io/gym1/31_hires.png', 'water'),
    (32, 'Misty''s Tentacool', 'rare', 'https://images.pokemontcg.io/gym1/32_hires.png', 'water'),
    (33, 'Rocket''s Snorlax', 'rare', 'https://images.pokemontcg.io/gym1/33_hires.png', 'colorless'),
    (34, 'Sabrina''s Venomoth', 'rare', 'https://images.pokemontcg.io/gym1/34_hires.png', 'grass'),
    (35, 'Blaine''s Growlithe', 'common', 'https://images.pokemontcg.io/gym1/35_hires.png', 'fire'),
    (36, 'Blaine''s Kangaskhan', 'common', 'https://images.pokemontcg.io/gym1/36_hires.png', 'colorless'),
    (37, 'Blaine''s Magmar', 'common', 'https://images.pokemontcg.io/gym1/37_hires.png', 'fire'),
    (38, 'Brock''s Geodude', 'common', 'https://images.pokemontcg.io/gym1/38_hires.png', 'fighting'),
    (39, 'Brock''s Golbat', 'common', 'https://images.pokemontcg.io/gym1/39_hires.png', 'grass'),
    (40, 'Brock''s Graveler', 'common', 'https://images.pokemontcg.io/gym1/40_hires.png', 'fighting'),
    (41, 'Brock''s Lickitung', 'common', 'https://images.pokemontcg.io/gym1/41_hires.png', 'colorless'),
    (42, 'Erika''s Dratini', 'common', 'https://images.pokemontcg.io/gym1/42_hires.png', 'colorless'),
    (43, 'Erika''s Exeggcute', 'common', 'https://images.pokemontcg.io/gym1/43_hires.png', 'grass'),
    (44, 'Erika''s Exeggutor', 'common', 'https://images.pokemontcg.io/gym1/44_hires.png', 'grass'),
    (45, 'Erika''s Gloom', 'common', 'https://images.pokemontcg.io/gym1/45_hires.png', 'grass'),
    (46, 'Erika''s Gloom', 'common', 'https://images.pokemontcg.io/gym1/46_hires.png', 'grass'),
    (47, 'Erika''s Oddish', 'common', 'https://images.pokemontcg.io/gym1/47_hires.png', 'grass'),
    (48, 'Erika''s Weepinbell', 'common', 'https://images.pokemontcg.io/gym1/48_hires.png', 'grass'),
    (49, 'Erika''s Weepinbell', 'common', 'https://images.pokemontcg.io/gym1/49_hires.png', 'grass'),
    (50, 'Lt. Surge''s Magnemite', 'common', 'https://images.pokemontcg.io/gym1/50_hires.png', 'lightning'),
    (51, 'Lt. Surge''s Raticate', 'common', 'https://images.pokemontcg.io/gym1/51_hires.png', 'colorless'),
    (52, 'Lt. Surge''s Spearow', 'common', 'https://images.pokemontcg.io/gym1/52_hires.png', 'colorless'),
    (53, 'Misty''s Poliwhirl', 'common', 'https://images.pokemontcg.io/gym1/53_hires.png', 'water'),
    (54, 'Misty''s Psyduck', 'common', 'https://images.pokemontcg.io/gym1/54_hires.png', 'water'),
    (55, 'Misty''s Seaking', 'common', 'https://images.pokemontcg.io/gym1/55_hires.png', 'water'),
    (56, 'Misty''s Starmie', 'common', 'https://images.pokemontcg.io/gym1/56_hires.png', 'water'),
    (57, 'Misty''s Tentacool', 'common', 'https://images.pokemontcg.io/gym1/57_hires.png', 'water'),
    (58, 'Sabrina''s Haunter', 'common', 'https://images.pokemontcg.io/gym1/58_hires.png', 'psychic'),
    (59, 'Sabrina''s Jynx', 'common', 'https://images.pokemontcg.io/gym1/59_hires.png', 'psychic'),
    (60, 'Sabrina''s Slowbro', 'common', 'https://images.pokemontcg.io/gym1/60_hires.png', 'psychic'),
    (61, 'Blaine''s Charmander', 'common', 'https://images.pokemontcg.io/gym1/61_hires.png', 'fire'),
    (62, 'Blaine''s Growlithe', 'common', 'https://images.pokemontcg.io/gym1/62_hires.png', 'fire'),
    (63, 'Blaine''s Ponyta', 'common', 'https://images.pokemontcg.io/gym1/63_hires.png', 'fire'),
    (64, 'Blaine''s Tauros', 'common', 'https://images.pokemontcg.io/gym1/64_hires.png', 'colorless'),
    (65, 'Blaine''s Vulpix', 'common', 'https://images.pokemontcg.io/gym1/65_hires.png', 'fire'),
    (66, 'Brock''s Geodude', 'common', 'https://images.pokemontcg.io/gym1/66_hires.png', 'fighting'),
    (67, 'Brock''s Mankey', 'common', 'https://images.pokemontcg.io/gym1/67_hires.png', 'fighting'),
    (68, 'Brock''s Mankey', 'common', 'https://images.pokemontcg.io/gym1/68_hires.png', 'fighting'),
    (69, 'Brock''s Onix', 'common', 'https://images.pokemontcg.io/gym1/69_hires.png', 'fighting'),
    (70, 'Brock''s Rhyhorn', 'common', 'https://images.pokemontcg.io/gym1/70_hires.png', 'fighting'),
    (71, 'Brock''s Sandshrew', 'common', 'https://images.pokemontcg.io/gym1/71_hires.png', 'fighting'),
    (72, 'Brock''s Sandshrew', 'common', 'https://images.pokemontcg.io/gym1/72_hires.png', 'fighting'),
    (73, 'Brock''s Vulpix', 'common', 'https://images.pokemontcg.io/gym1/73_hires.png', 'fire'),
    (74, 'Brock''s Zubat', 'common', 'https://images.pokemontcg.io/gym1/74_hires.png', 'grass'),
    (75, 'Erika''s Bellsprout', 'common', 'https://images.pokemontcg.io/gym1/75_hires.png', 'grass'),
    (76, 'Erika''s Bellsprout', 'common', 'https://images.pokemontcg.io/gym1/76_hires.png', 'grass'),
    (77, 'Erika''s Exeggcute', 'common', 'https://images.pokemontcg.io/gym1/77_hires.png', 'grass'),
    (78, 'Erika''s Oddish', 'common', 'https://images.pokemontcg.io/gym1/78_hires.png', 'grass'),
    (79, 'Erika''s Tangela', 'common', 'https://images.pokemontcg.io/gym1/79_hires.png', 'grass'),
    (80, 'Lt. Surge''s Magnemite', 'common', 'https://images.pokemontcg.io/gym1/80_hires.png', 'lightning'),
    (81, 'Lt. Surge''s Pikachu', 'common', 'https://images.pokemontcg.io/gym1/81_hires.png', 'lightning'),
    (82, 'Lt. Surge''s Rattata', 'common', 'https://images.pokemontcg.io/gym1/82_hires.png', 'colorless'),
    (83, 'Lt. Surge''s Spearow', 'common', 'https://images.pokemontcg.io/gym1/83_hires.png', 'colorless'),
    (84, 'Lt. Surge''s Voltorb', 'common', 'https://images.pokemontcg.io/gym1/84_hires.png', 'lightning'),
    (85, 'Misty''s Goldeen', 'common', 'https://images.pokemontcg.io/gym1/85_hires.png', 'water'),
    (86, 'Misty''s Horsea', 'common', 'https://images.pokemontcg.io/gym1/86_hires.png', 'water'),
    (87, 'Misty''s Poliwag', 'common', 'https://images.pokemontcg.io/gym1/87_hires.png', 'water'),
    (88, 'Misty''s Seel', 'common', 'https://images.pokemontcg.io/gym1/88_hires.png', 'water'),
    (89, 'Misty''s Shellder', 'common', 'https://images.pokemontcg.io/gym1/89_hires.png', 'water'),
    (90, 'Misty''s Staryu', 'common', 'https://images.pokemontcg.io/gym1/90_hires.png', 'water'),
    (91, 'Sabrina''s Abra', 'common', 'https://images.pokemontcg.io/gym1/91_hires.png', 'psychic'),
    (92, 'Sabrina''s Drowzee', 'common', 'https://images.pokemontcg.io/gym1/92_hires.png', 'psychic'),
    (93, 'Sabrina''s Gastly', 'common', 'https://images.pokemontcg.io/gym1/93_hires.png', 'psychic'),
    (94, 'Sabrina''s Mr. Mime', 'common', 'https://images.pokemontcg.io/gym1/94_hires.png', 'psychic'),
    (95, 'Sabrina''s Slowpoke', 'common', 'https://images.pokemontcg.io/gym1/95_hires.png', 'psychic'),
    (96, 'Sabrina''s Venonat', 'common', 'https://images.pokemontcg.io/gym1/96_hires.png', 'grass'),
    (97, 'Blaine''s Quiz #1', 'rare', 'https://images.pokemontcg.io/gym1/97_hires.png', NULL),
    (98, 'Brock', 'rare', 'https://images.pokemontcg.io/gym1/98_hires.png', NULL),
    (99, 'Charity', 'rare', 'https://images.pokemontcg.io/gym1/99_hires.png', NULL),
    (100, 'Erika', 'rare', 'https://images.pokemontcg.io/gym1/100_hires.png', NULL),
    (101, 'Lt. Surge', 'rare', 'https://images.pokemontcg.io/gym1/101_hires.png', NULL),
    (102, 'Misty', 'rare', 'https://images.pokemontcg.io/gym1/102_hires.png', NULL),
    (103, 'No Removal Gym', 'rare', 'https://images.pokemontcg.io/gym1/103_hires.png', NULL),
    (104, 'The Rocket''s Training Gym', 'rare', 'https://images.pokemontcg.io/gym1/104_hires.png', NULL),
    (105, 'Blaine''s Last Resort', 'common', 'https://images.pokemontcg.io/gym1/105_hires.png', NULL),
    (106, 'Brock''s Training Method', 'common', 'https://images.pokemontcg.io/gym1/106_hires.png', NULL),
    (107, 'Celadon City Gym', 'common', 'https://images.pokemontcg.io/gym1/107_hires.png', NULL),
    (108, 'Cerulean City Gym', 'common', 'https://images.pokemontcg.io/gym1/108_hires.png', NULL),
    (109, 'Erika''s Maids', 'common', 'https://images.pokemontcg.io/gym1/109_hires.png', NULL),
    (110, 'Erika''s Perfume', 'common', 'https://images.pokemontcg.io/gym1/110_hires.png', NULL),
    (111, 'Good Manners', 'common', 'https://images.pokemontcg.io/gym1/111_hires.png', NULL),
    (112, 'Lt. Surge''s Treaty', 'common', 'https://images.pokemontcg.io/gym1/112_hires.png', NULL),
    (113, 'Minion of Team Rocket', 'common', 'https://images.pokemontcg.io/gym1/113_hires.png', NULL),
    (114, 'Misty''s Wrath', 'common', 'https://images.pokemontcg.io/gym1/114_hires.png', NULL),
    (115, 'Pewter City Gym', 'common', 'https://images.pokemontcg.io/gym1/115_hires.png', NULL),
    (116, 'Recall', 'common', 'https://images.pokemontcg.io/gym1/116_hires.png', NULL),
    (117, 'Sabrina''s ESP', 'common', 'https://images.pokemontcg.io/gym1/117_hires.png', NULL),
    (118, 'Secret Mission', 'common', 'https://images.pokemontcg.io/gym1/118_hires.png', NULL),
    (119, 'Tickling Machine', 'common', 'https://images.pokemontcg.io/gym1/119_hires.png', NULL),
    (120, 'Vermilion City Gym', 'common', 'https://images.pokemontcg.io/gym1/120_hires.png', NULL),
    (121, 'Blaine''s Gamble', 'common', 'https://images.pokemontcg.io/gym1/121_hires.png', NULL),
    (122, 'Energy Flow', 'common', 'https://images.pokemontcg.io/gym1/122_hires.png', NULL),
    (123, 'Misty''s Duel', 'common', 'https://images.pokemontcg.io/gym1/123_hires.png', NULL),
    (124, 'Narrow Gym', 'common', 'https://images.pokemontcg.io/gym1/124_hires.png', NULL),
    (125, 'Sabrina''s Gaze', 'common', 'https://images.pokemontcg.io/gym1/125_hires.png', NULL),
    (126, 'Trash Exchange', 'common', 'https://images.pokemontcg.io/gym1/126_hires.png', NULL),
    (127, 'Fighting Energy', 'base', 'https://images.pokemontcg.io/gym1/127_hires.png', NULL),
    (128, 'Fire Energy', 'base', 'https://images.pokemontcg.io/gym1/128_hires.png', NULL),
    (129, 'Grass Energy', 'base', 'https://images.pokemontcg.io/gym1/129_hires.png', NULL),
    (130, 'Lightning Energy', 'base', 'https://images.pokemontcg.io/gym1/130_hires.png', NULL),
    (131, 'Psychic Energy', 'base', 'https://images.pokemontcg.io/gym1/131_hires.png', NULL),
    (132, 'Water Energy', 'base', 'https://images.pokemontcg.io/gym1/132_hires.png', NULL)
  ) as v(number, name, rarity, image_url, pokemon_type)
  on conflict (set_id, number) do nothing
  returning id, rarity
)
insert into card_variants (card_id, variant, price_sek, stock)
select ic.id, x.variant, 0, 0
from inserted_cards ic
cross join lateral (
  select case when ic.rarity = 'rare' then 'holo' else 'normal' end as variant
  union all
  select 'reverse_holo' where ic.rarity in ('common','rare')
) as x(variant)
on conflict (card_id, variant) do nothing;

-- Set: Gym Challenge (gym2) -- 2000/10/16
insert into sets (category_slug, category_name, slug, name, is_visible)
  values ('gym', 'Gym', 'gym-challenge', 'Gym Challenge', false)
  on conflict (slug) do nothing;

with s as (select id from sets where slug = 'gym-challenge'),
inserted_cards as (
  insert into cards (set_id, number, name, rarity, image_url, pokemon_type)
  select s.id, v.number, v.name, v.rarity, v.image_url, v.pokemon_type
  from s, (values
    (1, 'Blaine''s Arcanine', 'rare', 'https://images.pokemontcg.io/gym2/1_hires.png', 'fire'),
    (2, 'Blaine''s Charizard', 'rare', 'https://images.pokemontcg.io/gym2/2_hires.png', 'fire'),
    (3, 'Brock''s Ninetales', 'rare', 'https://images.pokemontcg.io/gym2/3_hires.png', 'fire'),
    (4, 'Erika''s Venusaur', 'rare', 'https://images.pokemontcg.io/gym2/4_hires.png', 'grass'),
    (5, 'Giovanni''s Gyarados', 'rare', 'https://images.pokemontcg.io/gym2/5_hires.png', 'water'),
    (6, 'Giovanni''s Machamp', 'rare', 'https://images.pokemontcg.io/gym2/6_hires.png', 'fighting'),
    (7, 'Giovanni''s Nidoking', 'rare', 'https://images.pokemontcg.io/gym2/7_hires.png', 'grass'),
    (8, 'Giovanni''s Persian', 'rare', 'https://images.pokemontcg.io/gym2/8_hires.png', 'colorless'),
    (9, 'Koga''s Beedrill', 'rare', 'https://images.pokemontcg.io/gym2/9_hires.png', 'grass'),
    (10, 'Koga''s Ditto', 'rare', 'https://images.pokemontcg.io/gym2/10_hires.png', 'colorless'),
    (11, 'Lt. Surge''s Raichu', 'rare', 'https://images.pokemontcg.io/gym2/11_hires.png', 'lightning'),
    (12, 'Misty''s Golduck', 'rare', 'https://images.pokemontcg.io/gym2/12_hires.png', 'water'),
    (13, 'Misty''s Gyarados', 'rare', 'https://images.pokemontcg.io/gym2/13_hires.png', 'water'),
    (14, 'Rocket''s Mewtwo', 'rare', 'https://images.pokemontcg.io/gym2/14_hires.png', 'psychic'),
    (15, 'Rocket''s Zapdos', 'rare', 'https://images.pokemontcg.io/gym2/15_hires.png', 'lightning'),
    (16, 'Sabrina''s Alakazam', 'rare', 'https://images.pokemontcg.io/gym2/16_hires.png', 'psychic'),
    (17, 'Blaine', 'rare', 'https://images.pokemontcg.io/gym2/17_hires.png', NULL),
    (18, 'Giovanni', 'rare', 'https://images.pokemontcg.io/gym2/18_hires.png', NULL),
    (19, 'Koga', 'rare', 'https://images.pokemontcg.io/gym2/19_hires.png', NULL),
    (20, 'Sabrina', 'rare', 'https://images.pokemontcg.io/gym2/20_hires.png', NULL),
    (21, 'Blaine''s Ninetales', 'rare', 'https://images.pokemontcg.io/gym2/21_hires.png', 'fire'),
    (22, 'Brock''s Dugtrio', 'rare', 'https://images.pokemontcg.io/gym2/22_hires.png', 'fighting'),
    (23, 'Giovanni''s Nidoqueen', 'rare', 'https://images.pokemontcg.io/gym2/23_hires.png', 'grass'),
    (24, 'Giovanni''s Pinsir', 'rare', 'https://images.pokemontcg.io/gym2/24_hires.png', 'grass'),
    (25, 'Koga''s Arbok', 'rare', 'https://images.pokemontcg.io/gym2/25_hires.png', 'grass'),
    (26, 'Koga''s Muk', 'rare', 'https://images.pokemontcg.io/gym2/26_hires.png', 'grass'),
    (27, 'Koga''s Pidgeotto', 'rare', 'https://images.pokemontcg.io/gym2/27_hires.png', 'colorless'),
    (28, 'Lt. Surge''s Jolteon', 'rare', 'https://images.pokemontcg.io/gym2/28_hires.png', 'lightning'),
    (29, 'Sabrina''s Gengar', 'rare', 'https://images.pokemontcg.io/gym2/29_hires.png', 'psychic'),
    (30, 'Sabrina''s Golduck', 'rare', 'https://images.pokemontcg.io/gym2/30_hires.png', 'water'),
    (31, 'Blaine''s Charmeleon', 'common', 'https://images.pokemontcg.io/gym2/31_hires.png', 'fire'),
    (32, 'Blaine''s Dodrio', 'common', 'https://images.pokemontcg.io/gym2/32_hires.png', 'colorless'),
    (33, 'Blaine''s Rapidash', 'common', 'https://images.pokemontcg.io/gym2/33_hires.png', 'fire'),
    (34, 'Brock''s Graveler', 'common', 'https://images.pokemontcg.io/gym2/34_hires.png', 'fighting'),
    (35, 'Brock''s Primeape', 'common', 'https://images.pokemontcg.io/gym2/35_hires.png', 'fighting'),
    (36, 'Brock''s Sandslash', 'common', 'https://images.pokemontcg.io/gym2/36_hires.png', 'fighting'),
    (37, 'Brock''s Vulpix', 'common', 'https://images.pokemontcg.io/gym2/37_hires.png', 'fire'),
    (38, 'Erika''s Bellsprout', 'common', 'https://images.pokemontcg.io/gym2/38_hires.png', 'grass'),
    (39, 'Erika''s Bulbasaur', 'common', 'https://images.pokemontcg.io/gym2/39_hires.png', 'grass'),
    (40, 'Erika''s Clefairy', 'common', 'https://images.pokemontcg.io/gym2/40_hires.png', 'colorless'),
    (41, 'Erika''s Ivysaur', 'common', 'https://images.pokemontcg.io/gym2/41_hires.png', 'grass'),
    (42, 'Giovanni''s Machoke', 'common', 'https://images.pokemontcg.io/gym2/42_hires.png', 'fighting'),
    (43, 'Giovanni''s Meowth', 'common', 'https://images.pokemontcg.io/gym2/43_hires.png', 'colorless'),
    (44, 'Giovanni''s Nidorina', 'common', 'https://images.pokemontcg.io/gym2/44_hires.png', 'grass'),
    (45, 'Giovanni''s Nidorino', 'common', 'https://images.pokemontcg.io/gym2/45_hires.png', 'grass'),
    (46, 'Koga''s Golbat', 'common', 'https://images.pokemontcg.io/gym2/46_hires.png', 'grass'),
    (47, 'Koga''s Kakuna', 'common', 'https://images.pokemontcg.io/gym2/47_hires.png', 'grass'),
    (48, 'Koga''s Koffing', 'common', 'https://images.pokemontcg.io/gym2/48_hires.png', 'grass'),
    (49, 'Koga''s Pidgey', 'common', 'https://images.pokemontcg.io/gym2/49_hires.png', 'colorless'),
    (50, 'Koga''s Weezing', 'common', 'https://images.pokemontcg.io/gym2/50_hires.png', 'grass'),
    (51, 'Lt. Surge''s Eevee', 'common', 'https://images.pokemontcg.io/gym2/51_hires.png', 'colorless'),
    (52, 'Lt. Surge''s Electrode', 'common', 'https://images.pokemontcg.io/gym2/52_hires.png', 'lightning'),
    (53, 'Lt. Surge''s Raticate', 'common', 'https://images.pokemontcg.io/gym2/53_hires.png', 'colorless'),
    (54, 'Misty''s Dewgong', 'common', 'https://images.pokemontcg.io/gym2/54_hires.png', 'water'),
    (55, 'Sabrina''s Haunter', 'common', 'https://images.pokemontcg.io/gym2/55_hires.png', 'psychic'),
    (56, 'Sabrina''s Hypno', 'common', 'https://images.pokemontcg.io/gym2/56_hires.png', 'psychic'),
    (57, 'Sabrina''s Jynx', 'common', 'https://images.pokemontcg.io/gym2/57_hires.png', 'psychic'),
    (58, 'Sabrina''s Kadabra', 'common', 'https://images.pokemontcg.io/gym2/58_hires.png', 'psychic'),
    (59, 'Sabrina''s Mr. Mime', 'common', 'https://images.pokemontcg.io/gym2/59_hires.png', 'psychic'),
    (60, 'Blaine''s Charmander', 'common', 'https://images.pokemontcg.io/gym2/60_hires.png', 'fire'),
    (61, 'Blaine''s Doduo', 'common', 'https://images.pokemontcg.io/gym2/61_hires.png', 'colorless'),
    (62, 'Blaine''s Growlithe', 'common', 'https://images.pokemontcg.io/gym2/62_hires.png', 'fire'),
    (63, 'Blaine''s Mankey', 'common', 'https://images.pokemontcg.io/gym2/63_hires.png', 'fighting'),
    (64, 'Blaine''s Ponyta', 'common', 'https://images.pokemontcg.io/gym2/64_hires.png', 'fire'),
    (65, 'Blaine''s Rhyhorn', 'common', 'https://images.pokemontcg.io/gym2/65_hires.png', 'fighting'),
    (66, 'Blaine''s Vulpix', 'common', 'https://images.pokemontcg.io/gym2/66_hires.png', 'fire'),
    (67, 'Brock''s Diglett', 'common', 'https://images.pokemontcg.io/gym2/67_hires.png', 'fighting'),
    (68, 'Brock''s Geodude', 'common', 'https://images.pokemontcg.io/gym2/68_hires.png', 'fighting'),
    (69, 'Erika''s Jigglypuff', 'common', 'https://images.pokemontcg.io/gym2/69_hires.png', 'colorless'),
    (70, 'Erika''s Oddish', 'common', 'https://images.pokemontcg.io/gym2/70_hires.png', 'grass'),
    (71, 'Erika''s Paras', 'common', 'https://images.pokemontcg.io/gym2/71_hires.png', 'grass'),
    (72, 'Giovanni''s Machop', 'common', 'https://images.pokemontcg.io/gym2/72_hires.png', 'fighting'),
    (73, 'Giovanni''s Magikarp', 'common', 'https://images.pokemontcg.io/gym2/73_hires.png', 'water'),
    (74, 'Giovanni''s Meowth', 'common', 'https://images.pokemontcg.io/gym2/74_hires.png', 'colorless'),
    (75, 'Giovanni''s Nidoran ♀', 'common', 'https://images.pokemontcg.io/gym2/75_hires.png', 'grass'),
    (76, 'Giovanni''s Nidoran ♂', 'common', 'https://images.pokemontcg.io/gym2/76_hires.png', 'grass'),
    (77, 'Koga''s Ekans', 'common', 'https://images.pokemontcg.io/gym2/77_hires.png', 'grass'),
    (78, 'Koga''s Grimer', 'common', 'https://images.pokemontcg.io/gym2/78_hires.png', 'grass'),
    (79, 'Koga''s Koffing', 'common', 'https://images.pokemontcg.io/gym2/79_hires.png', 'grass'),
    (80, 'Koga''s Pidgey', 'common', 'https://images.pokemontcg.io/gym2/80_hires.png', 'colorless'),
    (81, 'Koga''s Tangela', 'common', 'https://images.pokemontcg.io/gym2/81_hires.png', 'grass'),
    (82, 'Koga''s Weedle', 'common', 'https://images.pokemontcg.io/gym2/82_hires.png', 'grass'),
    (83, 'Koga''s Zubat', 'common', 'https://images.pokemontcg.io/gym2/83_hires.png', 'grass'),
    (84, 'Lt. Surge''s Pikachu', 'common', 'https://images.pokemontcg.io/gym2/84_hires.png', 'lightning'),
    (85, 'Lt. Surge''s Rattata', 'common', 'https://images.pokemontcg.io/gym2/85_hires.png', 'colorless'),
    (86, 'Lt. Surge''s Voltorb', 'common', 'https://images.pokemontcg.io/gym2/86_hires.png', 'lightning'),
    (87, 'Misty''s Horsea', 'common', 'https://images.pokemontcg.io/gym2/87_hires.png', 'water'),
    (88, 'Misty''s Magikarp', 'common', 'https://images.pokemontcg.io/gym2/88_hires.png', 'water'),
    (89, 'Misty''s Poliwag', 'common', 'https://images.pokemontcg.io/gym2/89_hires.png', 'water'),
    (90, 'Misty''s Psyduck', 'common', 'https://images.pokemontcg.io/gym2/90_hires.png', 'water'),
    (91, 'Misty''s Seel', 'common', 'https://images.pokemontcg.io/gym2/91_hires.png', 'water'),
    (92, 'Misty''s Staryu', 'common', 'https://images.pokemontcg.io/gym2/92_hires.png', 'water'),
    (93, 'Sabrina''s Abra', 'common', 'https://images.pokemontcg.io/gym2/93_hires.png', 'psychic'),
    (94, 'Sabrina''s Abra', 'common', 'https://images.pokemontcg.io/gym2/94_hires.png', 'psychic'),
    (95, 'Sabrina''s Drowzee', 'common', 'https://images.pokemontcg.io/gym2/95_hires.png', 'psychic'),
    (96, 'Sabrina''s Gastly', 'common', 'https://images.pokemontcg.io/gym2/96_hires.png', 'psychic'),
    (97, 'Sabrina''s Gastly', 'common', 'https://images.pokemontcg.io/gym2/97_hires.png', 'psychic'),
    (98, 'Sabrina''s Porygon', 'common', 'https://images.pokemontcg.io/gym2/98_hires.png', 'colorless'),
    (99, 'Sabrina''s Psyduck', 'common', 'https://images.pokemontcg.io/gym2/99_hires.png', 'water'),
    (100, 'Blaine', 'rare', 'https://images.pokemontcg.io/gym2/100_hires.png', NULL),
    (101, 'Brock''s Protection', 'rare', 'https://images.pokemontcg.io/gym2/101_hires.png', NULL),
    (102, 'Chaos Gym', 'rare', 'https://images.pokemontcg.io/gym2/102_hires.png', NULL),
    (103, 'Erika''s Kindness', 'rare', 'https://images.pokemontcg.io/gym2/103_hires.png', NULL),
    (104, 'Giovanni', 'rare', 'https://images.pokemontcg.io/gym2/104_hires.png', NULL),
    (105, 'Giovanni''s Last Resort', 'rare', 'https://images.pokemontcg.io/gym2/105_hires.png', NULL),
    (106, 'Koga', 'rare', 'https://images.pokemontcg.io/gym2/106_hires.png', NULL),
    (107, 'Lt. Surge''s Secret Plan', 'rare', 'https://images.pokemontcg.io/gym2/107_hires.png', NULL),
    (108, 'Misty''s Wish', 'rare', 'https://images.pokemontcg.io/gym2/108_hires.png', NULL),
    (109, 'Resistance Gym', 'rare', 'https://images.pokemontcg.io/gym2/109_hires.png', NULL),
    (110, 'Sabrina', 'rare', 'https://images.pokemontcg.io/gym2/110_hires.png', NULL),
    (111, 'Blaine''s Quiz #2', 'common', 'https://images.pokemontcg.io/gym2/111_hires.png', NULL),
    (112, 'Blaine''s Quiz #3', 'common', 'https://images.pokemontcg.io/gym2/112_hires.png', NULL),
    (113, 'Cinnabar City Gym', 'common', 'https://images.pokemontcg.io/gym2/113_hires.png', NULL),
    (114, 'Fuchsia City Gym', 'common', 'https://images.pokemontcg.io/gym2/114_hires.png', NULL),
    (115, 'Koga''s Ninja Trick', 'common', 'https://images.pokemontcg.io/gym2/115_hires.png', NULL),
    (116, 'Master Ball', 'common', 'https://images.pokemontcg.io/gym2/116_hires.png', NULL),
    (117, 'Max Revive', 'common', 'https://images.pokemontcg.io/gym2/117_hires.png', NULL),
    (118, 'Misty''s Tears', 'common', 'https://images.pokemontcg.io/gym2/118_hires.png', NULL),
    (119, 'Rocket''s Minefield Gym', 'common', 'https://images.pokemontcg.io/gym2/119_hires.png', NULL),
    (120, 'Rocket''s Secret Experiment', 'common', 'https://images.pokemontcg.io/gym2/120_hires.png', NULL),
    (121, 'Sabrina''s Psychic Control', 'common', 'https://images.pokemontcg.io/gym2/121_hires.png', NULL),
    (122, 'Saffron City Gym', 'common', 'https://images.pokemontcg.io/gym2/122_hires.png', NULL),
    (123, 'Viridian City Gym', 'common', 'https://images.pokemontcg.io/gym2/123_hires.png', NULL),
    (124, 'Fervor', 'common', 'https://images.pokemontcg.io/gym2/124_hires.png', NULL),
    (125, 'Transparent Walls', 'common', 'https://images.pokemontcg.io/gym2/125_hires.png', NULL),
    (126, 'Warp Point', 'common', 'https://images.pokemontcg.io/gym2/126_hires.png', NULL),
    (127, 'Fighting Energy', 'base', 'https://images.pokemontcg.io/gym2/127_hires.png', NULL),
    (128, 'Fire Energy', 'base', 'https://images.pokemontcg.io/gym2/128_hires.png', NULL),
    (129, 'Grass Energy', 'base', 'https://images.pokemontcg.io/gym2/129_hires.png', NULL),
    (130, 'Lightning Energy', 'base', 'https://images.pokemontcg.io/gym2/130_hires.png', NULL),
    (131, 'Psychic Energy', 'base', 'https://images.pokemontcg.io/gym2/131_hires.png', NULL),
    (132, 'Water Energy', 'base', 'https://images.pokemontcg.io/gym2/132_hires.png', NULL)
  ) as v(number, name, rarity, image_url, pokemon_type)
  on conflict (set_id, number) do nothing
  returning id, rarity
)
insert into card_variants (card_id, variant, price_sek, stock)
select ic.id, x.variant, 0, 0
from inserted_cards ic
cross join lateral (
  select case when ic.rarity = 'rare' then 'holo' else 'normal' end as variant
  union all
  select 'reverse_holo' where ic.rarity in ('common','rare')
) as x(variant)
on conflict (card_id, variant) do nothing;
