-- Katalogimport: Platinum (4 set)
-- Endast katalogdata (lager 0, pris 0) för portfölj/önskelista-funktionen.

-- Set: Platinum (pl1) -- 2009/02/11
insert into sets (category_slug, category_name, slug, name, is_visible)
  values ('platinum', 'Platinum', 'platinum', 'Platinum', false)
  on conflict (slug) do nothing;

with s as (select id from sets where slug = 'platinum'),
inserted_cards as (
  insert into cards (set_id, number, name, rarity, image_url, pokemon_type)
  select s.id, v.number, v.name, v.rarity, v.image_url, v.pokemon_type
  from s, (values
    (1, 'Ampharos', 'rare', 'https://images.pokemontcg.io/pl1/1_hires.png', 'lightning'),
    (2, 'Blastoise', 'rare', 'https://images.pokemontcg.io/pl1/2_hires.png', 'water'),
    (3, 'Blaziken', 'rare', 'https://images.pokemontcg.io/pl1/3_hires.png', 'fire'),
    (4, 'Delcatty', 'rare', 'https://images.pokemontcg.io/pl1/4_hires.png', 'colorless'),
    (5, 'Dialga', 'rare', 'https://images.pokemontcg.io/pl1/5_hires.png', 'metal'),
    (6, 'Dialga', 'rare', 'https://images.pokemontcg.io/pl1/6_hires.png', 'metal'),
    (7, 'Dialga G', 'rare', 'https://images.pokemontcg.io/pl1/7_hires.png', 'metal'),
    (8, 'Gardevoir', 'rare', 'https://images.pokemontcg.io/pl1/8_hires.png', 'psychic'),
    (9, 'Giratina', 'rare', 'https://images.pokemontcg.io/pl1/9_hires.png', 'psychic'),
    (10, 'Giratina', 'rare', 'https://images.pokemontcg.io/pl1/10_hires.png', 'psychic'),
    (11, 'Manectric', 'rare', 'https://images.pokemontcg.io/pl1/11_hires.png', 'lightning'),
    (12, 'Palkia G', 'rare', 'https://images.pokemontcg.io/pl1/12_hires.png', 'water'),
    (13, 'Rampardos', 'rare', 'https://images.pokemontcg.io/pl1/13_hires.png', 'fighting'),
    (14, 'Shaymin', 'rare', 'https://images.pokemontcg.io/pl1/14_hires.png', 'grass'),
    (15, 'Shaymin', 'rare', 'https://images.pokemontcg.io/pl1/15_hires.png', 'grass'),
    (16, 'Slaking', 'rare', 'https://images.pokemontcg.io/pl1/16_hires.png', 'colorless'),
    (17, 'Weavile G', 'rare', 'https://images.pokemontcg.io/pl1/17_hires.png', 'darkness'),
    (18, 'Altaria', 'rare', 'https://images.pokemontcg.io/pl1/18_hires.png', 'colorless'),
    (19, 'Banette', 'rare', 'https://images.pokemontcg.io/pl1/19_hires.png', 'psychic'),
    (20, 'Bastiodon', 'rare', 'https://images.pokemontcg.io/pl1/20_hires.png', 'metal'),
    (21, 'Beautifly', 'rare', 'https://images.pokemontcg.io/pl1/21_hires.png', 'grass'),
    (22, 'Blissey', 'rare', 'https://images.pokemontcg.io/pl1/22_hires.png', 'colorless'),
    (23, 'Dialga', 'rare', 'https://images.pokemontcg.io/pl1/23_hires.png', 'metal'),
    (24, 'Dugtrio', 'rare', 'https://images.pokemontcg.io/pl1/24_hires.png', 'fighting'),
    (25, 'Dustox', 'rare', 'https://images.pokemontcg.io/pl1/25_hires.png', 'psychic'),
    (26, 'Empoleon', 'rare', 'https://images.pokemontcg.io/pl1/26_hires.png', 'water'),
    (27, 'Giratina', 'rare', 'https://images.pokemontcg.io/pl1/27_hires.png', 'psychic'),
    (28, 'Giratina', 'rare', 'https://images.pokemontcg.io/pl1/28_hires.png', 'psychic'),
    (29, 'Golduck', 'rare', 'https://images.pokemontcg.io/pl1/29_hires.png', 'water'),
    (30, 'Gyarados G', 'rare', 'https://images.pokemontcg.io/pl1/30_hires.png', 'water'),
    (31, 'Infernape', 'rare', 'https://images.pokemontcg.io/pl1/31_hires.png', 'fire'),
    (32, 'Kricketune', 'rare', 'https://images.pokemontcg.io/pl1/32_hires.png', 'grass'),
    (33, 'Lickilicky', 'rare', 'https://images.pokemontcg.io/pl1/33_hires.png', 'colorless'),
    (34, 'Ludicolo', 'rare', 'https://images.pokemontcg.io/pl1/34_hires.png', 'grass'),
    (35, 'Luvdisc', 'rare', 'https://images.pokemontcg.io/pl1/35_hires.png', 'water'),
    (36, 'Ninetales', 'rare', 'https://images.pokemontcg.io/pl1/36_hires.png', 'fire'),
    (37, 'Palkia', 'rare', 'https://images.pokemontcg.io/pl1/37_hires.png', 'water'),
    (38, 'Shaymin', 'rare', 'https://images.pokemontcg.io/pl1/38_hires.png', 'grass'),
    (39, 'Torterra', 'rare', 'https://images.pokemontcg.io/pl1/39_hires.png', 'grass'),
    (40, 'Toxicroak G', 'rare', 'https://images.pokemontcg.io/pl1/40_hires.png', 'psychic'),
    (41, 'Bronzong G', 'common', 'https://images.pokemontcg.io/pl1/41_hires.png', 'metal'),
    (42, 'Cacturne', 'common', 'https://images.pokemontcg.io/pl1/42_hires.png', 'grass'),
    (43, 'Carnivine', 'common', 'https://images.pokemontcg.io/pl1/43_hires.png', 'grass'),
    (44, 'Cascoon', 'common', 'https://images.pokemontcg.io/pl1/44_hires.png', 'grass'),
    (45, 'Combusken', 'common', 'https://images.pokemontcg.io/pl1/45_hires.png', 'fire'),
    (46, 'Cranidos', 'common', 'https://images.pokemontcg.io/pl1/46_hires.png', 'fighting'),
    (47, 'Crobat G', 'common', 'https://images.pokemontcg.io/pl1/47_hires.png', 'psychic'),
    (48, 'Flaaffy', 'common', 'https://images.pokemontcg.io/pl1/48_hires.png', 'lightning'),
    (49, 'Grotle', 'common', 'https://images.pokemontcg.io/pl1/49_hires.png', 'grass'),
    (50, 'Houndoom G', 'common', 'https://images.pokemontcg.io/pl1/50_hires.png', 'fire'),
    (51, 'Kirlia', 'common', 'https://images.pokemontcg.io/pl1/51_hires.png', 'psychic'),
    (52, 'Lombre', 'common', 'https://images.pokemontcg.io/pl1/52_hires.png', 'grass'),
    (53, 'Lucario', 'common', 'https://images.pokemontcg.io/pl1/53_hires.png', 'metal'),
    (54, 'Mightyena', 'common', 'https://images.pokemontcg.io/pl1/54_hires.png', 'darkness'),
    (55, 'Mismagius', 'common', 'https://images.pokemontcg.io/pl1/55_hires.png', 'psychic'),
    (56, 'Monferno', 'common', 'https://images.pokemontcg.io/pl1/56_hires.png', 'fire'),
    (57, 'Muk', 'common', 'https://images.pokemontcg.io/pl1/57_hires.png', 'psychic'),
    (58, 'Octillery', 'common', 'https://images.pokemontcg.io/pl1/58_hires.png', 'water'),
    (59, 'Prinplup', 'common', 'https://images.pokemontcg.io/pl1/59_hires.png', 'water'),
    (60, 'Probopass', 'common', 'https://images.pokemontcg.io/pl1/60_hires.png', 'fighting'),
    (61, 'Seviper', 'common', 'https://images.pokemontcg.io/pl1/61_hires.png', 'psychic'),
    (62, 'Shieldon', 'common', 'https://images.pokemontcg.io/pl1/62_hires.png', 'metal'),
    (63, 'Silcoon', 'common', 'https://images.pokemontcg.io/pl1/63_hires.png', 'grass'),
    (64, 'Vigoroth', 'common', 'https://images.pokemontcg.io/pl1/64_hires.png', 'colorless'),
    (65, 'Wartortle', 'common', 'https://images.pokemontcg.io/pl1/65_hires.png', 'water'),
    (66, 'Zangoose', 'common', 'https://images.pokemontcg.io/pl1/66_hires.png', 'colorless'),
    (67, 'Cacnea', 'common', 'https://images.pokemontcg.io/pl1/67_hires.png', 'grass'),
    (68, 'Carnivine', 'common', 'https://images.pokemontcg.io/pl1/68_hires.png', 'grass'),
    (69, 'Chansey', 'common', 'https://images.pokemontcg.io/pl1/69_hires.png', 'colorless'),
    (70, 'Chimchar', 'common', 'https://images.pokemontcg.io/pl1/70_hires.png', 'fire'),
    (71, 'Combee', 'common', 'https://images.pokemontcg.io/pl1/71_hires.png', 'grass'),
    (72, 'Diglett', 'common', 'https://images.pokemontcg.io/pl1/72_hires.png', 'fighting'),
    (73, 'Dunsparce', 'common', 'https://images.pokemontcg.io/pl1/73_hires.png', 'colorless'),
    (74, 'Electrike', 'common', 'https://images.pokemontcg.io/pl1/74_hires.png', 'lightning'),
    (75, 'Grimer', 'common', 'https://images.pokemontcg.io/pl1/75_hires.png', 'psychic'),
    (76, 'Happiny', 'common', 'https://images.pokemontcg.io/pl1/76_hires.png', 'colorless'),
    (77, 'Honchkrow G', 'common', 'https://images.pokemontcg.io/pl1/77_hires.png', 'darkness'),
    (78, 'Kricketot', 'common', 'https://images.pokemontcg.io/pl1/78_hires.png', 'grass'),
    (79, 'Lapras', 'common', 'https://images.pokemontcg.io/pl1/79_hires.png', 'water'),
    (80, 'Lickitung', 'common', 'https://images.pokemontcg.io/pl1/80_hires.png', 'colorless'),
    (81, 'Lotad', 'common', 'https://images.pokemontcg.io/pl1/81_hires.png', 'grass'),
    (82, 'Mareep', 'common', 'https://images.pokemontcg.io/pl1/82_hires.png', 'lightning'),
    (83, 'Misdreavus', 'common', 'https://images.pokemontcg.io/pl1/83_hires.png', 'psychic'),
    (84, 'Nosepass', 'common', 'https://images.pokemontcg.io/pl1/84_hires.png', 'fighting'),
    (85, 'Piplup', 'common', 'https://images.pokemontcg.io/pl1/85_hires.png', 'water'),
    (86, 'Poochyena', 'common', 'https://images.pokemontcg.io/pl1/86_hires.png', 'darkness'),
    (87, 'Psyduck', 'common', 'https://images.pokemontcg.io/pl1/87_hires.png', 'water'),
    (88, 'Purugly G', 'common', 'https://images.pokemontcg.io/pl1/88_hires.png', 'colorless'),
    (89, 'Ralts', 'common', 'https://images.pokemontcg.io/pl1/89_hires.png', 'psychic'),
    (90, 'Remoraid', 'common', 'https://images.pokemontcg.io/pl1/90_hires.png', 'water'),
    (91, 'Riolu', 'common', 'https://images.pokemontcg.io/pl1/91_hires.png', 'fighting'),
    (92, 'Shuppet', 'common', 'https://images.pokemontcg.io/pl1/92_hires.png', 'psychic'),
    (93, 'Skitty', 'common', 'https://images.pokemontcg.io/pl1/93_hires.png', 'colorless'),
    (94, 'Skuntank G', 'common', 'https://images.pokemontcg.io/pl1/94_hires.png', 'psychic'),
    (95, 'Slakoth', 'common', 'https://images.pokemontcg.io/pl1/95_hires.png', 'colorless'),
    (96, 'Squirtle', 'common', 'https://images.pokemontcg.io/pl1/96_hires.png', 'water'),
    (97, 'Swablu', 'common', 'https://images.pokemontcg.io/pl1/97_hires.png', 'colorless'),
    (98, 'Tauros', 'common', 'https://images.pokemontcg.io/pl1/98_hires.png', 'colorless'),
    (99, 'Torchic', 'common', 'https://images.pokemontcg.io/pl1/99_hires.png', 'fire'),
    (100, 'Torkoal', 'common', 'https://images.pokemontcg.io/pl1/100_hires.png', 'fire'),
    (101, 'Turtwig', 'common', 'https://images.pokemontcg.io/pl1/101_hires.png', 'grass'),
    (102, 'Vulpix', 'common', 'https://images.pokemontcg.io/pl1/102_hires.png', 'fire'),
    (103, 'Wurmple', 'common', 'https://images.pokemontcg.io/pl1/103_hires.png', 'grass'),
    (104, 'Broken Time-Space', 'common', 'https://images.pokemontcg.io/pl1/104_hires.png', NULL),
    (105, 'Cyrus''s Conspiracy', 'common', 'https://images.pokemontcg.io/pl1/105_hires.png', NULL),
    (106, 'Galactic HQ', 'common', 'https://images.pokemontcg.io/pl1/106_hires.png', NULL),
    (107, 'Level Max', 'common', 'https://images.pokemontcg.io/pl1/107_hires.png', NULL),
    (108, 'Life Herb', 'common', 'https://images.pokemontcg.io/pl1/108_hires.png', NULL),
    (109, 'Looker''s Investigation', 'common', 'https://images.pokemontcg.io/pl1/109_hires.png', NULL),
    (110, 'Memory Berry', 'common', 'https://images.pokemontcg.io/pl1/110_hires.png', NULL),
    (111, 'Miasma Valley', 'common', 'https://images.pokemontcg.io/pl1/111_hires.png', NULL),
    (112, 'PlusPower', 'common', 'https://images.pokemontcg.io/pl1/112_hires.png', NULL),
    (113, 'Poké Ball', 'common', 'https://images.pokemontcg.io/pl1/113_hires.png', NULL),
    (114, 'Pokédex HANDY910is', 'common', 'https://images.pokemontcg.io/pl1/114_hires.png', NULL),
    (115, 'Pokémon Rescue', 'common', 'https://images.pokemontcg.io/pl1/115_hires.png', NULL),
    (116, 'Team Galactic''s Invention G-101 Energy Gain', 'common', 'https://images.pokemontcg.io/pl1/116_hires.png', NULL),
    (117, 'Team Galactic''s Invention G-103 Power Spray', 'common', 'https://images.pokemontcg.io/pl1/117_hires.png', NULL),
    (118, 'Team Galactic''s Invention G-105 Poké Turn', 'common', 'https://images.pokemontcg.io/pl1/118_hires.png', NULL),
    (119, 'Armor Fossil', 'common', 'https://images.pokemontcg.io/pl1/119_hires.png', NULL),
    (120, 'Skull Fossil', 'common', 'https://images.pokemontcg.io/pl1/120_hires.png', NULL),
    (121, 'Rainbow Energy', 'common', 'https://images.pokemontcg.io/pl1/121_hires.png', NULL),
    (122, 'Dialga G LV.X', 'ultra_rare', 'https://images.pokemontcg.io/pl1/122_hires.png', 'metal'),
    (123, 'Drapion LV.X', 'ultra_rare', 'https://images.pokemontcg.io/pl1/123_hires.png', 'darkness'),
    (124, 'Giratina LV.X', 'ultra_rare', 'https://images.pokemontcg.io/pl1/124_hires.png', 'psychic'),
    (125, 'Palkia G LV.X', 'ultra_rare', 'https://images.pokemontcg.io/pl1/125_hires.png', 'water'),
    (126, 'Shaymin LV.X', 'ultra_rare', 'https://images.pokemontcg.io/pl1/126_hires.png', 'grass'),
    (127, 'Shaymin LV.X', 'ultra_rare', 'https://images.pokemontcg.io/pl1/127_hires.png', 'grass'),
    (128, 'Electabuzz', 'mega_hyper_rare', 'https://images.pokemontcg.io/pl1/128_hires.png', 'lightning'),
    (129, 'Hitmonchan', 'mega_hyper_rare', 'https://images.pokemontcg.io/pl1/129_hires.png', 'fighting'),
    (130, 'Scyther', 'mega_hyper_rare', 'https://images.pokemontcg.io/pl1/130_hires.png', 'grass'),
    (501004, 'Lotad', 'rare', 'https://images.pokemontcg.io/pl1/SH4_hires.png', 'grass'),
    (501005, 'Swablu', 'rare', 'https://images.pokemontcg.io/pl1/SH5_hires.png', 'colorless'),
    (501006, 'Vulpix', 'rare', 'https://images.pokemontcg.io/pl1/SH6_hires.png', 'fire')
  ) as v(number, name, rarity, image_url, pokemon_type)
  on conflict (set_id, number) do nothing
  returning id, rarity
)
insert into card_variants (card_id, variant, price_sek, stock)
select ic.id, x.variant, 0, 0
from inserted_cards ic
cross join lateral (
  select case when ic.rarity = 'rare' then 'holo' else 'normal' end as variant
  union all
  select 'reverse_holo' where ic.rarity in ('common','rare')
) as x(variant)
on conflict (card_id, variant) do nothing;

-- Set: Rising Rivals (pl2) -- 2009/05/16
insert into sets (category_slug, category_name, slug, name, is_visible)
  values ('platinum', 'Platinum', 'rising-rivals', 'Rising Rivals', false)
  on conflict (slug) do nothing;

with s as (select id from sets where slug = 'rising-rivals'),
inserted_cards as (
  insert into cards (set_id, number, name, rarity, image_url, pokemon_type)
  select s.id, v.number, v.name, v.rarity, v.image_url, v.pokemon_type
  from s, (values
    (1, 'Arcanine', 'rare', 'https://images.pokemontcg.io/pl2/1_hires.png', 'fire'),
    (2, 'Bastiodon GL', 'rare', 'https://images.pokemontcg.io/pl2/2_hires.png', 'metal'),
    (3, 'Darkrai G', 'rare', 'https://images.pokemontcg.io/pl2/3_hires.png', 'darkness'),
    (4, 'Floatzel GL', 'rare', 'https://images.pokemontcg.io/pl2/4_hires.png', 'water'),
    (5, 'Flygon', 'rare', 'https://images.pokemontcg.io/pl2/5_hires.png', 'colorless'),
    (6, 'Froslass GL', 'rare', 'https://images.pokemontcg.io/pl2/6_hires.png', 'water'),
    (7, 'Jirachi', 'rare', 'https://images.pokemontcg.io/pl2/7_hires.png', 'metal'),
    (8, 'Lucario GL', 'rare', 'https://images.pokemontcg.io/pl2/8_hires.png', 'fighting'),
    (9, 'Luxray GL', 'rare', 'https://images.pokemontcg.io/pl2/9_hires.png', 'lightning'),
    (10, 'Mismagius GL', 'rare', 'https://images.pokemontcg.io/pl2/10_hires.png', 'psychic'),
    (11, 'Rampardos GL', 'rare', 'https://images.pokemontcg.io/pl2/11_hires.png', 'fighting'),
    (12, 'Roserade GL', 'rare', 'https://images.pokemontcg.io/pl2/12_hires.png', 'grass'),
    (13, 'Shiftry', 'rare', 'https://images.pokemontcg.io/pl2/13_hires.png', 'darkness'),
    (14, 'Aggron', 'rare', 'https://images.pokemontcg.io/pl2/14_hires.png', 'metal'),
    (15, 'Beedrill', 'rare', 'https://images.pokemontcg.io/pl2/15_hires.png', 'grass'),
    (16, 'Bronzong E4', 'rare', 'https://images.pokemontcg.io/pl2/16_hires.png', 'psychic'),
    (17, 'Drapion E4', 'rare', 'https://images.pokemontcg.io/pl2/17_hires.png', 'darkness'),
    (18, 'Espeon E4', 'rare', 'https://images.pokemontcg.io/pl2/18_hires.png', 'psychic'),
    (19, 'Flareon', 'rare', 'https://images.pokemontcg.io/pl2/19_hires.png', 'fire'),
    (20, 'Gallade E4', 'rare', 'https://images.pokemontcg.io/pl2/20_hires.png', 'psychic'),
    (21, 'Gastrodon East Sea', 'rare', 'https://images.pokemontcg.io/pl2/21_hires.png', 'water'),
    (22, 'Gastrodon West Sea', 'rare', 'https://images.pokemontcg.io/pl2/22_hires.png', 'fighting'),
    (23, 'Golem E4', 'rare', 'https://images.pokemontcg.io/pl2/23_hires.png', 'fighting'),
    (24, 'Heracross E4', 'rare', 'https://images.pokemontcg.io/pl2/24_hires.png', 'grass'),
    (25, 'Hippowdon', 'rare', 'https://images.pokemontcg.io/pl2/25_hires.png', 'fighting'),
    (26, 'Jolteon', 'rare', 'https://images.pokemontcg.io/pl2/26_hires.png', 'lightning'),
    (27, 'Mamoswine GL', 'rare', 'https://images.pokemontcg.io/pl2/27_hires.png', 'water'),
    (28, 'Mr. Mime E4', 'rare', 'https://images.pokemontcg.io/pl2/28_hires.png', 'psychic'),
    (29, 'Nidoking', 'rare', 'https://images.pokemontcg.io/pl2/29_hires.png', 'fighting'),
    (30, 'Nidoqueen', 'rare', 'https://images.pokemontcg.io/pl2/30_hires.png', 'psychic'),
    (31, 'Raichu GL', 'rare', 'https://images.pokemontcg.io/pl2/31_hires.png', 'lightning'),
    (32, 'Rhyperior E4', 'rare', 'https://images.pokemontcg.io/pl2/32_hires.png', 'fighting'),
    (33, 'Snorlax', 'rare', 'https://images.pokemontcg.io/pl2/33_hires.png', 'colorless'),
    (34, 'Vaporeon', 'rare', 'https://images.pokemontcg.io/pl2/34_hires.png', 'water'),
    (35, 'Vespiquen E4', 'rare', 'https://images.pokemontcg.io/pl2/35_hires.png', 'grass'),
    (36, 'Walrein', 'rare', 'https://images.pokemontcg.io/pl2/36_hires.png', 'water'),
    (37, 'Yanmega E4', 'rare', 'https://images.pokemontcg.io/pl2/37_hires.png', 'grass'),
    (38, 'Alakazam E4', 'common', 'https://images.pokemontcg.io/pl2/38_hires.png', 'psychic'),
    (39, 'Electrode G', 'common', 'https://images.pokemontcg.io/pl2/39_hires.png', 'lightning'),
    (40, 'Gengar GL', 'common', 'https://images.pokemontcg.io/pl2/40_hires.png', 'psychic'),
    (41, 'Glaceon', 'common', 'https://images.pokemontcg.io/pl2/41_hires.png', 'water'),
    (42, 'Hippowdon E4', 'common', 'https://images.pokemontcg.io/pl2/42_hires.png', 'fighting'),
    (43, 'Infernape E4', 'common', 'https://images.pokemontcg.io/pl2/43_hires.png', 'fire'),
    (44, 'Lairon', 'common', 'https://images.pokemontcg.io/pl2/44_hires.png', 'metal'),
    (45, 'Leafeon', 'common', 'https://images.pokemontcg.io/pl2/45_hires.png', 'grass'),
    (46, 'Machamp GL', 'common', 'https://images.pokemontcg.io/pl2/46_hires.png', 'fighting'),
    (47, 'Rapidash E4', 'common', 'https://images.pokemontcg.io/pl2/47_hires.png', 'fire'),
    (48, 'Scizor E4', 'common', 'https://images.pokemontcg.io/pl2/48_hires.png', 'grass'),
    (49, 'Sharpedo', 'common', 'https://images.pokemontcg.io/pl2/49_hires.png', 'darkness'),
    (50, 'Starmie', 'common', 'https://images.pokemontcg.io/pl2/50_hires.png', 'water'),
    (51, 'Steelix GL', 'common', 'https://images.pokemontcg.io/pl2/51_hires.png', 'metal'),
    (52, 'Tropius', 'common', 'https://images.pokemontcg.io/pl2/52_hires.png', 'grass'),
    (53, 'Vibrava', 'common', 'https://images.pokemontcg.io/pl2/53_hires.png', 'colorless'),
    (54, 'Whiscash E4', 'common', 'https://images.pokemontcg.io/pl2/54_hires.png', 'fighting'),
    (55, 'Aerodactyl GL', 'common', 'https://images.pokemontcg.io/pl2/55_hires.png', 'fighting'),
    (56, 'Ambipom G', 'common', 'https://images.pokemontcg.io/pl2/56_hires.png', 'colorless'),
    (57, 'Aron', 'common', 'https://images.pokemontcg.io/pl2/57_hires.png', 'metal'),
    (58, 'Carvanha', 'common', 'https://images.pokemontcg.io/pl2/58_hires.png', 'darkness'),
    (59, 'Eevee', 'common', 'https://images.pokemontcg.io/pl2/59_hires.png', 'colorless'),
    (60, 'Flareon E4', 'common', 'https://images.pokemontcg.io/pl2/60_hires.png', 'fire'),
    (61, 'Forretress G', 'common', 'https://images.pokemontcg.io/pl2/61_hires.png', 'metal'),
    (62, 'Gliscor E4', 'common', 'https://images.pokemontcg.io/pl2/62_hires.png', 'fighting'),
    (63, 'Growlithe', 'common', 'https://images.pokemontcg.io/pl2/63_hires.png', 'fire'),
    (64, 'Hippopotas', 'common', 'https://images.pokemontcg.io/pl2/64_hires.png', 'fighting'),
    (65, 'Houndoom E4', 'common', 'https://images.pokemontcg.io/pl2/65_hires.png', 'darkness'),
    (66, 'Kakuna', 'common', 'https://images.pokemontcg.io/pl2/66_hires.png', 'grass'),
    (67, 'Kecleon', 'common', 'https://images.pokemontcg.io/pl2/67_hires.png', 'colorless'),
    (68, 'Koffing', 'common', 'https://images.pokemontcg.io/pl2/68_hires.png', 'psychic'),
    (69, 'Munchlax', 'common', 'https://images.pokemontcg.io/pl2/69_hires.png', 'colorless'),
    (70, 'Munchlax', 'common', 'https://images.pokemontcg.io/pl2/70_hires.png', 'colorless'),
    (71, 'Nidoran ♀', 'common', 'https://images.pokemontcg.io/pl2/71_hires.png', 'psychic'),
    (72, 'Nidoran ♂', 'common', 'https://images.pokemontcg.io/pl2/72_hires.png', 'psychic'),
    (73, 'Nidorina', 'common', 'https://images.pokemontcg.io/pl2/73_hires.png', 'psychic'),
    (74, 'Nidorino', 'common', 'https://images.pokemontcg.io/pl2/74_hires.png', 'psychic'),
    (75, 'Nuzleaf', 'common', 'https://images.pokemontcg.io/pl2/75_hires.png', 'darkness'),
    (76, 'Quagsire GL', 'common', 'https://images.pokemontcg.io/pl2/76_hires.png', 'water'),
    (77, 'Sealeo', 'common', 'https://images.pokemontcg.io/pl2/77_hires.png', 'water'),
    (78, 'Seedot', 'common', 'https://images.pokemontcg.io/pl2/78_hires.png', 'grass'),
    (79, 'Shellos East Sea', 'common', 'https://images.pokemontcg.io/pl2/79_hires.png', 'water'),
    (80, 'Shellos West Sea', 'common', 'https://images.pokemontcg.io/pl2/80_hires.png', 'water'),
    (81, 'Snorlax', 'common', 'https://images.pokemontcg.io/pl2/81_hires.png', 'colorless'),
    (82, 'Spheal', 'common', 'https://images.pokemontcg.io/pl2/82_hires.png', 'water'),
    (83, 'Staryu', 'common', 'https://images.pokemontcg.io/pl2/83_hires.png', 'water'),
    (84, 'Trapinch', 'common', 'https://images.pokemontcg.io/pl2/84_hires.png', 'fighting'),
    (85, 'Turtwig GL', 'common', 'https://images.pokemontcg.io/pl2/85_hires.png', 'grass'),
    (86, 'Weedle', 'common', 'https://images.pokemontcg.io/pl2/86_hires.png', 'grass'),
    (87, 'Weezing', 'common', 'https://images.pokemontcg.io/pl2/87_hires.png', 'psychic'),
    (88, 'Aaron''s Collection', 'common', 'https://images.pokemontcg.io/pl2/88_hires.png', NULL),
    (89, 'Bebe''s Search', 'common', 'https://images.pokemontcg.io/pl2/89_hires.png', NULL),
    (90, 'Bertha''s Warmth', 'common', 'https://images.pokemontcg.io/pl2/90_hires.png', NULL),
    (91, 'Flint''s Willpower', 'common', 'https://images.pokemontcg.io/pl2/91_hires.png', NULL),
    (92, 'Lucian''s Assignment', 'common', 'https://images.pokemontcg.io/pl2/92_hires.png', NULL),
    (93, 'Pokémon Contest Hall', 'common', 'https://images.pokemontcg.io/pl2/93_hires.png', NULL),
    (94, 'Sunyshore City Gym', 'common', 'https://images.pokemontcg.io/pl2/94_hires.png', NULL),
    (95, 'Team Galactic''s Invention G-107 Technical Machine G', 'common', 'https://images.pokemontcg.io/pl2/95_hires.png', NULL),
    (96, 'Team Galactic''s Invention G-109 SP Radar', 'common', 'https://images.pokemontcg.io/pl2/96_hires.png', NULL),
    (97, 'Underground Expedition', 'common', 'https://images.pokemontcg.io/pl2/97_hires.png', NULL),
    (98, 'Volkner''s Philosophy', 'common', 'https://images.pokemontcg.io/pl2/98_hires.png', NULL),
    (99, 'Darkness Energy', 'common', 'https://images.pokemontcg.io/pl2/99_hires.png', NULL),
    (100, 'Metal Energy', 'common', 'https://images.pokemontcg.io/pl2/100_hires.png', NULL),
    (101, 'SP Energy', 'common', 'https://images.pokemontcg.io/pl2/101_hires.png', NULL),
    (102, 'Upper Energy', 'common', 'https://images.pokemontcg.io/pl2/102_hires.png', NULL),
    (103, 'Alakazam E4 LV.X', 'ultra_rare', 'https://images.pokemontcg.io/pl2/103_hires.png', 'psychic'),
    (104, 'Floatzel GL LV.X', 'ultra_rare', 'https://images.pokemontcg.io/pl2/104_hires.png', 'water'),
    (105, 'Flygon LV.X', 'ultra_rare', 'https://images.pokemontcg.io/pl2/105_hires.png', 'colorless'),
    (106, 'Gallade E4 LV.X', 'ultra_rare', 'https://images.pokemontcg.io/pl2/106_hires.png', 'psychic'),
    (107, 'Hippowdon LV.X', 'ultra_rare', 'https://images.pokemontcg.io/pl2/107_hires.png', 'fighting'),
    (108, 'Infernape E4 LV.X', 'ultra_rare', 'https://images.pokemontcg.io/pl2/108_hires.png', 'fire'),
    (109, 'Luxray GL LV.X', 'ultra_rare', 'https://images.pokemontcg.io/pl2/109_hires.png', 'lightning'),
    (110, 'Mismagius GL LV.X', 'ultra_rare', 'https://images.pokemontcg.io/pl2/110_hires.png', 'psychic'),
    (111, 'Snorlax LV.X', 'ultra_rare', 'https://images.pokemontcg.io/pl2/111_hires.png', 'colorless'),
    (112, 'Pikachu', 'mega_hyper_rare', 'https://images.pokemontcg.io/pl2/112_hires.png', 'lightning'),
    (113, 'Flying Pikachu', 'mega_hyper_rare', 'https://images.pokemontcg.io/pl2/113_hires.png', 'lightning'),
    (114, 'Surfing Pikachu', 'mega_hyper_rare', 'https://images.pokemontcg.io/pl2/114_hires.png', 'lightning'),
    (501001, 'Fan Rotom', 'rare', 'https://images.pokemontcg.io/pl2/RT1_hires.png', 'lightning'),
    (501002, 'Frost Rotom', 'rare', 'https://images.pokemontcg.io/pl2/RT2_hires.png', 'lightning'),
    (501003, 'Heat Rotom', 'rare', 'https://images.pokemontcg.io/pl2/RT3_hires.png', 'lightning'),
    (501004, 'Mow Rotom', 'rare', 'https://images.pokemontcg.io/pl2/RT4_hires.png', 'lightning'),
    (501005, 'Wash Rotom', 'rare', 'https://images.pokemontcg.io/pl2/RT5_hires.png', 'lightning'),
    (501006, 'Charon''s Choice', 'rare', 'https://images.pokemontcg.io/pl2/RT6_hires.png', NULL)
  ) as v(number, name, rarity, image_url, pokemon_type)
  on conflict (set_id, number) do nothing
  returning id, rarity
)
insert into card_variants (card_id, variant, price_sek, stock)
select ic.id, x.variant, 0, 0
from inserted_cards ic
cross join lateral (
  select case when ic.rarity = 'rare' then 'holo' else 'normal' end as variant
  union all
  select 'reverse_holo' where ic.rarity in ('common','rare')
) as x(variant)
on conflict (card_id, variant) do nothing;

-- Set: Supreme Victors (pl3) -- 2009/08/19
insert into sets (category_slug, category_name, slug, name, is_visible)
  values ('platinum', 'Platinum', 'supreme-victors', 'Supreme Victors', false)
  on conflict (slug) do nothing;

with s as (select id from sets where slug = 'supreme-victors'),
inserted_cards as (
  insert into cards (set_id, number, name, rarity, image_url, pokemon_type)
  select s.id, v.number, v.name, v.rarity, v.image_url, v.pokemon_type
  from s, (values
    (1, 'Absol G', 'rare', 'https://images.pokemontcg.io/pl3/1_hires.png', 'darkness'),
    (2, 'Blaziken FB', 'rare', 'https://images.pokemontcg.io/pl3/2_hires.png', 'fire'),
    (3, 'Drifblim FB', 'rare', 'https://images.pokemontcg.io/pl3/3_hires.png', 'psychic'),
    (4, 'Electivire FB', 'rare', 'https://images.pokemontcg.io/pl3/4_hires.png', 'lightning'),
    (5, 'Garchomp', 'rare', 'https://images.pokemontcg.io/pl3/5_hires.png', 'colorless'),
    (6, 'Magmortar', 'rare', 'https://images.pokemontcg.io/pl3/6_hires.png', 'fire'),
    (7, 'Metagross', 'rare', 'https://images.pokemontcg.io/pl3/7_hires.png', 'metal'),
    (8, 'Rayquaza C', 'rare', 'https://images.pokemontcg.io/pl3/8_hires.png', 'colorless'),
    (9, 'Regigigas FB', 'rare', 'https://images.pokemontcg.io/pl3/9_hires.png', 'colorless'),
    (10, 'Rhyperior', 'rare', 'https://images.pokemontcg.io/pl3/10_hires.png', 'fighting'),
    (11, 'Staraptor FB', 'rare', 'https://images.pokemontcg.io/pl3/11_hires.png', 'colorless'),
    (12, 'Swampert', 'rare', 'https://images.pokemontcg.io/pl3/12_hires.png', 'water'),
    (13, 'Venusaur', 'rare', 'https://images.pokemontcg.io/pl3/13_hires.png', 'grass'),
    (14, 'Yanmega', 'rare', 'https://images.pokemontcg.io/pl3/14_hires.png', 'grass'),
    (15, 'Arcanine G', 'rare', 'https://images.pokemontcg.io/pl3/15_hires.png', 'fire'),
    (16, 'Articuno', 'rare', 'https://images.pokemontcg.io/pl3/16_hires.png', 'water'),
    (17, 'Butterfree FB', 'rare', 'https://images.pokemontcg.io/pl3/17_hires.png', 'grass'),
    (18, 'Camerupt', 'rare', 'https://images.pokemontcg.io/pl3/18_hires.png', 'fire'),
    (19, 'Camerupt G', 'rare', 'https://images.pokemontcg.io/pl3/19_hires.png', 'fire'),
    (20, 'Charizard G', 'rare', 'https://images.pokemontcg.io/pl3/20_hires.png', 'fire'),
    (21, 'Chimecho', 'rare', 'https://images.pokemontcg.io/pl3/21_hires.png', 'psychic'),
    (22, 'Claydol', 'rare', 'https://images.pokemontcg.io/pl3/22_hires.png', 'psychic'),
    (23, 'Crawdaunt G', 'rare', 'https://images.pokemontcg.io/pl3/23_hires.png', 'darkness'),
    (24, 'Dewgong', 'rare', 'https://images.pokemontcg.io/pl3/24_hires.png', 'water'),
    (25, 'Dodrio', 'rare', 'https://images.pokemontcg.io/pl3/25_hires.png', 'colorless'),
    (26, 'Dusknoir FB', 'rare', 'https://images.pokemontcg.io/pl3/26_hires.png', 'psychic'),
    (27, 'Empoleon FB', 'rare', 'https://images.pokemontcg.io/pl3/27_hires.png', 'water'),
    (28, 'Exploud', 'rare', 'https://images.pokemontcg.io/pl3/28_hires.png', 'colorless'),
    (29, 'Honchkrow', 'rare', 'https://images.pokemontcg.io/pl3/29_hires.png', 'darkness'),
    (30, 'Lickilicky C', 'rare', 'https://images.pokemontcg.io/pl3/30_hires.png', 'colorless'),
    (31, 'Lucario C', 'rare', 'https://images.pokemontcg.io/pl3/31_hires.png', 'fighting'),
    (32, 'Lunatone', 'rare', 'https://images.pokemontcg.io/pl3/32_hires.png', 'psychic'),
    (33, 'Mawile', 'rare', 'https://images.pokemontcg.io/pl3/33_hires.png', 'metal'),
    (34, 'Medicham', 'rare', 'https://images.pokemontcg.io/pl3/34_hires.png', 'psychic'),
    (35, 'Milotic C', 'rare', 'https://images.pokemontcg.io/pl3/35_hires.png', 'water'),
    (36, 'Moltres', 'rare', 'https://images.pokemontcg.io/pl3/36_hires.png', 'fire'),
    (37, 'Mr. Mime', 'rare', 'https://images.pokemontcg.io/pl3/37_hires.png', 'psychic'),
    (38, 'Parasect', 'rare', 'https://images.pokemontcg.io/pl3/38_hires.png', 'grass'),
    (39, 'Primeape', 'rare', 'https://images.pokemontcg.io/pl3/39_hires.png', 'fighting'),
    (40, 'Roserade C', 'rare', 'https://images.pokemontcg.io/pl3/40_hires.png', 'psychic'),
    (41, 'Sableye G', 'rare', 'https://images.pokemontcg.io/pl3/41_hires.png', 'darkness'),
    (42, 'Sandslash', 'rare', 'https://images.pokemontcg.io/pl3/42_hires.png', 'fighting'),
    (43, 'Seaking', 'rare', 'https://images.pokemontcg.io/pl3/43_hires.png', 'water'),
    (44, 'Shedinja', 'rare', 'https://images.pokemontcg.io/pl3/44_hires.png', 'grass'),
    (45, 'Solrock', 'rare', 'https://images.pokemontcg.io/pl3/45_hires.png', 'psychic'),
    (46, 'Spinda', 'rare', 'https://images.pokemontcg.io/pl3/46_hires.png', 'colorless'),
    (47, 'Wailord', 'rare', 'https://images.pokemontcg.io/pl3/47_hires.png', 'water'),
    (48, 'Zapdos', 'rare', 'https://images.pokemontcg.io/pl3/48_hires.png', 'lightning'),
    (49, 'Altaria C', 'common', 'https://images.pokemontcg.io/pl3/49_hires.png', 'colorless'),
    (50, 'Arcanine', 'common', 'https://images.pokemontcg.io/pl3/50_hires.png', 'fire'),
    (51, 'Bibarel', 'common', 'https://images.pokemontcg.io/pl3/51_hires.png', 'colorless'),
    (52, 'Breloom', 'common', 'https://images.pokemontcg.io/pl3/52_hires.png', 'fighting'),
    (53, 'Carnivine', 'common', 'https://images.pokemontcg.io/pl3/53_hires.png', 'grass'),
    (54, 'Chatot G', 'common', 'https://images.pokemontcg.io/pl3/54_hires.png', 'colorless'),
    (55, 'Cherrim', 'common', 'https://images.pokemontcg.io/pl3/55_hires.png', 'grass'),
    (56, 'Dragonite FB', 'common', 'https://images.pokemontcg.io/pl3/56_hires.png', 'colorless'),
    (57, 'Drifblim', 'common', 'https://images.pokemontcg.io/pl3/57_hires.png', 'psychic'),
    (58, 'Floatzel', 'common', 'https://images.pokemontcg.io/pl3/58_hires.png', 'water'),
    (59, 'Gabite', 'common', 'https://images.pokemontcg.io/pl3/59_hires.png', 'colorless'),
    (60, 'Garchomp C', 'common', 'https://images.pokemontcg.io/pl3/60_hires.png', 'colorless'),
    (61, 'Hippopotas', 'common', 'https://images.pokemontcg.io/pl3/61_hires.png', 'fighting'),
    (62, 'Ivysaur', 'common', 'https://images.pokemontcg.io/pl3/62_hires.png', 'grass'),
    (63, 'Lopunny', 'common', 'https://images.pokemontcg.io/pl3/63_hires.png', 'colorless'),
    (64, 'Loudred', 'common', 'https://images.pokemontcg.io/pl3/64_hires.png', 'colorless'),
    (65, 'Magmar', 'common', 'https://images.pokemontcg.io/pl3/65_hires.png', 'fire'),
    (66, 'Manectric G', 'common', 'https://images.pokemontcg.io/pl3/66_hires.png', 'lightning'),
    (67, 'Marshtomp', 'common', 'https://images.pokemontcg.io/pl3/67_hires.png', 'water'),
    (68, 'Masquerain', 'common', 'https://images.pokemontcg.io/pl3/68_hires.png', 'grass'),
    (69, 'Metang', 'common', 'https://images.pokemontcg.io/pl3/69_hires.png', 'metal'),
    (70, 'Milotic', 'common', 'https://images.pokemontcg.io/pl3/70_hires.png', 'water'),
    (71, 'Minun', 'common', 'https://images.pokemontcg.io/pl3/71_hires.png', 'lightning'),
    (72, 'Murkrow', 'common', 'https://images.pokemontcg.io/pl3/72_hires.png', 'darkness'),
    (73, 'Ninjask', 'common', 'https://images.pokemontcg.io/pl3/73_hires.png', 'grass'),
    (74, 'Numel', 'common', 'https://images.pokemontcg.io/pl3/74_hires.png', 'fire'),
    (75, 'Pinsir', 'common', 'https://images.pokemontcg.io/pl3/75_hires.png', 'grass'),
    (76, 'Plusle', 'common', 'https://images.pokemontcg.io/pl3/76_hires.png', 'lightning'),
    (77, 'Raichu', 'common', 'https://images.pokemontcg.io/pl3/77_hires.png', 'lightning'),
    (78, 'Raticate G', 'common', 'https://images.pokemontcg.io/pl3/78_hires.png', 'colorless'),
    (79, 'Relicanth', 'common', 'https://images.pokemontcg.io/pl3/79_hires.png', 'fighting'),
    (80, 'Rhydon', 'common', 'https://images.pokemontcg.io/pl3/80_hires.png', 'fighting'),
    (81, 'Roserade', 'common', 'https://images.pokemontcg.io/pl3/81_hires.png', 'grass'),
    (82, 'Rotom', 'common', 'https://images.pokemontcg.io/pl3/82_hires.png', 'lightning'),
    (83, 'Skarmory FB', 'common', 'https://images.pokemontcg.io/pl3/83_hires.png', 'metal'),
    (84, 'Spiritomb C', 'common', 'https://images.pokemontcg.io/pl3/84_hires.png', 'psychic'),
    (85, 'Staravia', 'common', 'https://images.pokemontcg.io/pl3/85_hires.png', 'colorless'),
    (86, 'Togekiss C', 'common', 'https://images.pokemontcg.io/pl3/86_hires.png', 'colorless'),
    (87, 'Wailmer', 'common', 'https://images.pokemontcg.io/pl3/87_hires.png', 'water'),
    (88, 'Yanma', 'common', 'https://images.pokemontcg.io/pl3/88_hires.png', 'grass'),
    (89, 'Baltoy', 'common', 'https://images.pokemontcg.io/pl3/89_hires.png', 'psychic'),
    (90, 'Beldum', 'common', 'https://images.pokemontcg.io/pl3/90_hires.png', 'metal'),
    (91, 'Bidoof', 'common', 'https://images.pokemontcg.io/pl3/91_hires.png', 'colorless'),
    (92, 'Buizel', 'common', 'https://images.pokemontcg.io/pl3/92_hires.png', 'water'),
    (93, 'Bulbasaur', 'common', 'https://images.pokemontcg.io/pl3/93_hires.png', 'grass'),
    (94, 'Buneary', 'common', 'https://images.pokemontcg.io/pl3/94_hires.png', 'colorless'),
    (95, 'Chatot', 'common', 'https://images.pokemontcg.io/pl3/95_hires.png', 'colorless'),
    (96, 'Cherubi', 'common', 'https://images.pokemontcg.io/pl3/96_hires.png', 'grass'),
    (97, 'Chimchar', 'common', 'https://images.pokemontcg.io/pl3/97_hires.png', 'fire'),
    (98, 'Chingling', 'common', 'https://images.pokemontcg.io/pl3/98_hires.png', 'psychic'),
    (99, 'Combee', 'common', 'https://images.pokemontcg.io/pl3/99_hires.png', 'grass'),
    (100, 'Corphish', 'common', 'https://images.pokemontcg.io/pl3/100_hires.png', 'water'),
    (101, 'Croagunk', 'common', 'https://images.pokemontcg.io/pl3/101_hires.png', 'psychic'),
    (102, 'Doduo', 'common', 'https://images.pokemontcg.io/pl3/102_hires.png', 'colorless'),
    (103, 'Drifloon', 'common', 'https://images.pokemontcg.io/pl3/103_hires.png', 'psychic'),
    (104, 'Feebas', 'common', 'https://images.pokemontcg.io/pl3/104_hires.png', 'water'),
    (105, 'Geodude', 'common', 'https://images.pokemontcg.io/pl3/105_hires.png', 'fighting'),
    (106, 'Gible', 'common', 'https://images.pokemontcg.io/pl3/106_hires.png', 'colorless'),
    (107, 'Goldeen', 'common', 'https://images.pokemontcg.io/pl3/107_hires.png', 'water'),
    (108, 'Growlithe', 'common', 'https://images.pokemontcg.io/pl3/108_hires.png', 'fire'),
    (109, 'Kricketot', 'common', 'https://images.pokemontcg.io/pl3/109_hires.png', 'grass'),
    (110, 'Magikarp', 'common', 'https://images.pokemontcg.io/pl3/110_hires.png', 'water'),
    (111, 'Magnemite', 'common', 'https://images.pokemontcg.io/pl3/111_hires.png', 'lightning'),
    (112, 'Mankey', 'common', 'https://images.pokemontcg.io/pl3/112_hires.png', 'fighting'),
    (113, 'Meditite', 'common', 'https://images.pokemontcg.io/pl3/113_hires.png', 'psychic'),
    (114, 'Meowth', 'common', 'https://images.pokemontcg.io/pl3/114_hires.png', 'colorless'),
    (115, 'Mime Jr.', 'common', 'https://images.pokemontcg.io/pl3/115_hires.png', 'psychic'),
    (116, 'Mudkip', 'common', 'https://images.pokemontcg.io/pl3/116_hires.png', 'water'),
    (117, 'Nincada', 'common', 'https://images.pokemontcg.io/pl3/117_hires.png', 'grass'),
    (118, 'Pachirisu', 'common', 'https://images.pokemontcg.io/pl3/118_hires.png', 'lightning'),
    (119, 'Paras', 'common', 'https://images.pokemontcg.io/pl3/119_hires.png', 'grass'),
    (120, 'Pikachu', 'common', 'https://images.pokemontcg.io/pl3/120_hires.png', 'lightning'),
    (121, 'Piplup', 'common', 'https://images.pokemontcg.io/pl3/121_hires.png', 'water'),
    (122, 'Rhyhorn', 'common', 'https://images.pokemontcg.io/pl3/122_hires.png', 'fighting'),
    (123, 'Roselia', 'common', 'https://images.pokemontcg.io/pl3/123_hires.png', 'grass'),
    (124, 'Sandshrew', 'common', 'https://images.pokemontcg.io/pl3/124_hires.png', 'fighting'),
    (125, 'Seel', 'common', 'https://images.pokemontcg.io/pl3/125_hires.png', 'water'),
    (126, 'Shinx', 'common', 'https://images.pokemontcg.io/pl3/126_hires.png', 'lightning'),
    (127, 'Shroomish', 'common', 'https://images.pokemontcg.io/pl3/127_hires.png', 'grass'),
    (128, 'Skorupi', 'common', 'https://images.pokemontcg.io/pl3/128_hires.png', 'psychic'),
    (129, 'Starly', 'common', 'https://images.pokemontcg.io/pl3/129_hires.png', 'colorless'),
    (130, 'Surskit', 'common', 'https://images.pokemontcg.io/pl3/130_hires.png', 'grass'),
    (131, 'Turtwig', 'common', 'https://images.pokemontcg.io/pl3/131_hires.png', 'grass'),
    (132, 'Whismur', 'common', 'https://images.pokemontcg.io/pl3/132_hires.png', 'colorless'),
    (133, 'Zubat', 'common', 'https://images.pokemontcg.io/pl3/133_hires.png', 'psychic'),
    (134, 'Battle Tower', 'common', 'https://images.pokemontcg.io/pl3/134_hires.png', NULL),
    (135, 'Champion''s Room', 'common', 'https://images.pokemontcg.io/pl3/135_hires.png', NULL),
    (136, 'Cynthia''s Guidance', 'common', 'https://images.pokemontcg.io/pl3/136_hires.png', NULL),
    (137, 'Cyrus''s Initiative', 'common', 'https://images.pokemontcg.io/pl3/137_hires.png', NULL),
    (138, 'Night Teleporter', 'common', 'https://images.pokemontcg.io/pl3/138_hires.png', NULL),
    (139, 'Palmer''s Contribution', 'common', 'https://images.pokemontcg.io/pl3/139_hires.png', NULL),
    (140, 'VS Seeker', 'common', 'https://images.pokemontcg.io/pl3/140_hires.png', NULL),
    (141, 'Absol G LV.X', 'ultra_rare', 'https://images.pokemontcg.io/pl3/141_hires.png', 'darkness'),
    (142, 'Blaziken FB LV.X', 'ultra_rare', 'https://images.pokemontcg.io/pl3/142_hires.png', 'fire'),
    (143, 'Charizard G LV.X', 'ultra_rare', 'https://images.pokemontcg.io/pl3/143_hires.png', 'fire'),
    (144, 'Electivire FB LV.X', 'ultra_rare', 'https://images.pokemontcg.io/pl3/144_hires.png', 'lightning'),
    (145, 'Garchomp C LV.X', 'ultra_rare', 'https://images.pokemontcg.io/pl3/145_hires.png', 'colorless'),
    (146, 'Rayquaza C LV.X', 'ultra_rare', 'https://images.pokemontcg.io/pl3/146_hires.png', 'colorless'),
    (147, 'Staraptor FB LV.X', 'ultra_rare', 'https://images.pokemontcg.io/pl3/147_hires.png', 'colorless'),
    (148, 'Articuno', 'mega_hyper_rare', 'https://images.pokemontcg.io/pl3/148_hires.png', 'water'),
    (149, 'Moltres', 'mega_hyper_rare', 'https://images.pokemontcg.io/pl3/149_hires.png', 'fire'),
    (150, 'Zapdos', 'mega_hyper_rare', 'https://images.pokemontcg.io/pl3/150_hires.png', 'lightning'),
    (501007, 'Milotic', 'rare', 'https://images.pokemontcg.io/pl3/SH7_hires.png', 'water'),
    (501008, 'Relicanth', 'rare', 'https://images.pokemontcg.io/pl3/SH8_hires.png', 'fighting'),
    (501009, 'Yanma', 'rare', 'https://images.pokemontcg.io/pl3/SH9_hires.png', 'grass')
  ) as v(number, name, rarity, image_url, pokemon_type)
  on conflict (set_id, number) do nothing
  returning id, rarity
)
insert into card_variants (card_id, variant, price_sek, stock)
select ic.id, x.variant, 0, 0
from inserted_cards ic
cross join lateral (
  select case when ic.rarity = 'rare' then 'holo' else 'normal' end as variant
  union all
  select 'reverse_holo' where ic.rarity in ('common','rare')
) as x(variant)
on conflict (card_id, variant) do nothing;

-- Set: Arceus (pl4) -- 2009/11/04
insert into sets (category_slug, category_name, slug, name, is_visible)
  values ('platinum', 'Platinum', 'arceus', 'Arceus', false)
  on conflict (slug) do nothing;

with s as (select id from sets where slug = 'arceus'),
inserted_cards as (
  insert into cards (set_id, number, name, rarity, image_url, pokemon_type)
  select s.id, v.number, v.name, v.rarity, v.image_url, v.pokemon_type
  from s, (values
    (1, 'Charizard', 'rare', 'https://images.pokemontcg.io/pl4/1_hires.png', 'fire'),
    (2, 'Froslass', 'rare', 'https://images.pokemontcg.io/pl4/2_hires.png', 'water'),
    (3, 'Heatran', 'rare', 'https://images.pokemontcg.io/pl4/3_hires.png', 'fire'),
    (4, 'Kabutops', 'rare', 'https://images.pokemontcg.io/pl4/4_hires.png', 'fighting'),
    (5, 'Luxray', 'rare', 'https://images.pokemontcg.io/pl4/5_hires.png', 'lightning'),
    (6, 'Mothim', 'rare', 'https://images.pokemontcg.io/pl4/6_hires.png', 'grass'),
    (7, 'Probopass', 'rare', 'https://images.pokemontcg.io/pl4/7_hires.png', 'metal'),
    (8, 'Salamence', 'rare', 'https://images.pokemontcg.io/pl4/8_hires.png', 'colorless'),
    (9, 'Swalot', 'rare', 'https://images.pokemontcg.io/pl4/9_hires.png', 'psychic'),
    (10, 'Tangrowth', 'rare', 'https://images.pokemontcg.io/pl4/10_hires.png', 'grass'),
    (11, 'Toxicroak', 'rare', 'https://images.pokemontcg.io/pl4/11_hires.png', 'fighting'),
    (12, 'Zapdos G', 'rare', 'https://images.pokemontcg.io/pl4/12_hires.png', 'lightning'),
    (13, 'Aerodactyl', 'rare', 'https://images.pokemontcg.io/pl4/13_hires.png', 'fighting'),
    (14, 'Bronzong', 'rare', 'https://images.pokemontcg.io/pl4/14_hires.png', 'metal'),
    (15, 'Cherrim', 'rare', 'https://images.pokemontcg.io/pl4/15_hires.png', 'grass'),
    (16, 'Gengar', 'rare', 'https://images.pokemontcg.io/pl4/16_hires.png', 'psychic'),
    (17, 'Gengar', 'rare', 'https://images.pokemontcg.io/pl4/17_hires.png', 'psychic'),
    (18, 'Glalie', 'rare', 'https://images.pokemontcg.io/pl4/18_hires.png', 'water'),
    (19, 'Golem', 'rare', 'https://images.pokemontcg.io/pl4/19_hires.png', 'fighting'),
    (20, 'Hariyama', 'rare', 'https://images.pokemontcg.io/pl4/20_hires.png', 'fighting'),
    (21, 'Lopunny', 'rare', 'https://images.pokemontcg.io/pl4/21_hires.png', 'colorless'),
    (22, 'Manectric', 'rare', 'https://images.pokemontcg.io/pl4/22_hires.png', 'lightning'),
    (23, 'Omastar', 'rare', 'https://images.pokemontcg.io/pl4/23_hires.png', 'water'),
    (24, 'Pelipper', 'rare', 'https://images.pokemontcg.io/pl4/24_hires.png', 'water'),
    (25, 'Pichu', 'rare', 'https://images.pokemontcg.io/pl4/25_hires.png', 'lightning'),
    (26, 'Porygon-Z G', 'rare', 'https://images.pokemontcg.io/pl4/26_hires.png', 'colorless'),
    (27, 'Raichu', 'rare', 'https://images.pokemontcg.io/pl4/27_hires.png', 'lightning'),
    (28, 'Rapidash', 'rare', 'https://images.pokemontcg.io/pl4/28_hires.png', 'fire'),
    (29, 'Raticate', 'rare', 'https://images.pokemontcg.io/pl4/29_hires.png', 'colorless'),
    (30, 'Sceptile', 'rare', 'https://images.pokemontcg.io/pl4/30_hires.png', 'grass'),
    (31, 'Sceptile', 'rare', 'https://images.pokemontcg.io/pl4/31_hires.png', 'grass'),
    (32, 'Spiritomb', 'rare', 'https://images.pokemontcg.io/pl4/32_hires.png', 'darkness'),
    (33, 'Bronzong', 'common', 'https://images.pokemontcg.io/pl4/33_hires.png', 'metal'),
    (34, 'Bronzor', 'common', 'https://images.pokemontcg.io/pl4/34_hires.png', 'metal'),
    (35, 'Charmeleon', 'common', 'https://images.pokemontcg.io/pl4/35_hires.png', 'fire'),
    (36, 'Gastly', 'common', 'https://images.pokemontcg.io/pl4/36_hires.png', 'psychic'),
    (37, 'Graveler', 'common', 'https://images.pokemontcg.io/pl4/37_hires.png', 'fighting'),
    (38, 'Grovyle', 'common', 'https://images.pokemontcg.io/pl4/38_hires.png', 'grass'),
    (39, 'Grovyle', 'common', 'https://images.pokemontcg.io/pl4/39_hires.png', 'grass'),
    (40, 'Gulpin', 'common', 'https://images.pokemontcg.io/pl4/40_hires.png', 'psychic'),
    (41, 'Haunter', 'common', 'https://images.pokemontcg.io/pl4/41_hires.png', 'psychic'),
    (42, 'Haunter', 'common', 'https://images.pokemontcg.io/pl4/42_hires.png', 'psychic'),
    (43, 'Luxio', 'common', 'https://images.pokemontcg.io/pl4/43_hires.png', 'lightning'),
    (44, 'Manectric', 'common', 'https://images.pokemontcg.io/pl4/44_hires.png', 'lightning'),
    (45, 'Pelipper', 'common', 'https://images.pokemontcg.io/pl4/45_hires.png', 'water'),
    (46, 'Ponyta', 'common', 'https://images.pokemontcg.io/pl4/46_hires.png', 'fire'),
    (47, 'Rapidash', 'common', 'https://images.pokemontcg.io/pl4/47_hires.png', 'fire'),
    (48, 'Shelgon', 'common', 'https://images.pokemontcg.io/pl4/48_hires.png', 'colorless'),
    (49, 'Wormadam Plant Cloak', 'common', 'https://images.pokemontcg.io/pl4/49_hires.png', 'grass'),
    (50, 'Wormadam Sandy Cloak', 'common', 'https://images.pokemontcg.io/pl4/50_hires.png', 'fighting'),
    (51, 'Wormadam Trash Cloak', 'common', 'https://images.pokemontcg.io/pl4/51_hires.png', 'metal'),
    (52, 'Bagon', 'common', 'https://images.pokemontcg.io/pl4/52_hires.png', 'colorless'),
    (53, 'Beedrill G', 'common', 'https://images.pokemontcg.io/pl4/53_hires.png', 'grass'),
    (54, 'Bronzor', 'common', 'https://images.pokemontcg.io/pl4/54_hires.png', 'metal'),
    (55, 'Buneary', 'common', 'https://images.pokemontcg.io/pl4/55_hires.png', 'colorless'),
    (56, 'Burmy Plant Cloak', 'common', 'https://images.pokemontcg.io/pl4/56_hires.png', 'grass'),
    (57, 'Burmy Sandy Cloak', 'common', 'https://images.pokemontcg.io/pl4/57_hires.png', 'grass'),
    (58, 'Burmy Trash Cloak', 'common', 'https://images.pokemontcg.io/pl4/58_hires.png', 'grass'),
    (59, 'Charmander', 'common', 'https://images.pokemontcg.io/pl4/59_hires.png', 'fire'),
    (60, 'Cherubi', 'common', 'https://images.pokemontcg.io/pl4/60_hires.png', 'grass'),
    (61, 'Croagunk', 'common', 'https://images.pokemontcg.io/pl4/61_hires.png', 'fighting'),
    (62, 'Electrike', 'common', 'https://images.pokemontcg.io/pl4/62_hires.png', 'lightning'),
    (63, 'Electrike', 'common', 'https://images.pokemontcg.io/pl4/63_hires.png', 'lightning'),
    (64, 'Gastly', 'common', 'https://images.pokemontcg.io/pl4/64_hires.png', 'psychic'),
    (65, 'Geodude', 'common', 'https://images.pokemontcg.io/pl4/65_hires.png', 'fighting'),
    (66, 'Gulpin', 'common', 'https://images.pokemontcg.io/pl4/66_hires.png', 'psychic'),
    (67, 'Kabuto', 'common', 'https://images.pokemontcg.io/pl4/67_hires.png', 'fighting'),
    (68, 'Makuhita', 'common', 'https://images.pokemontcg.io/pl4/68_hires.png', 'fighting'),
    (69, 'Nosepass', 'common', 'https://images.pokemontcg.io/pl4/69_hires.png', 'fighting'),
    (70, 'Omanyte', 'common', 'https://images.pokemontcg.io/pl4/70_hires.png', 'water'),
    (71, 'Pikachu', 'common', 'https://images.pokemontcg.io/pl4/71_hires.png', 'lightning'),
    (72, 'Ponyta', 'common', 'https://images.pokemontcg.io/pl4/72_hires.png', 'fire'),
    (73, 'Rattata', 'common', 'https://images.pokemontcg.io/pl4/73_hires.png', 'colorless'),
    (74, 'Shinx', 'common', 'https://images.pokemontcg.io/pl4/74_hires.png', 'lightning'),
    (75, 'Snorunt', 'common', 'https://images.pokemontcg.io/pl4/75_hires.png', 'water'),
    (76, 'Tangela', 'common', 'https://images.pokemontcg.io/pl4/76_hires.png', 'grass'),
    (77, 'Tangela', 'common', 'https://images.pokemontcg.io/pl4/77_hires.png', 'grass'),
    (78, 'Treecko', 'common', 'https://images.pokemontcg.io/pl4/78_hires.png', 'grass'),
    (79, 'Treecko', 'common', 'https://images.pokemontcg.io/pl4/79_hires.png', 'grass'),
    (80, 'Wingull', 'common', 'https://images.pokemontcg.io/pl4/80_hires.png', 'water'),
    (81, 'Wingull', 'common', 'https://images.pokemontcg.io/pl4/81_hires.png', 'water'),
    (82, 'Beginning Door', 'common', 'https://images.pokemontcg.io/pl4/82_hires.png', NULL),
    (83, 'Bench Shield', 'common', 'https://images.pokemontcg.io/pl4/83_hires.png', NULL),
    (84, 'Buffer Piece', 'common', 'https://images.pokemontcg.io/pl4/84_hires.png', NULL),
    (85, 'Department Store Girl', 'common', 'https://images.pokemontcg.io/pl4/85_hires.png', NULL),
    (86, 'Energy Restore', 'common', 'https://images.pokemontcg.io/pl4/86_hires.png', NULL),
    (87, 'Expert Belt', 'common', 'https://images.pokemontcg.io/pl4/87_hires.png', NULL),
    (88, 'Lucky Egg', 'common', 'https://images.pokemontcg.io/pl4/88_hires.png', NULL),
    (89, 'Old Amber', 'common', 'https://images.pokemontcg.io/pl4/89_hires.png', NULL),
    (90, 'Professor Oak''s Visit', 'common', 'https://images.pokemontcg.io/pl4/90_hires.png', NULL),
    (91, 'Ultimate Zone', 'common', 'https://images.pokemontcg.io/pl4/91_hires.png', NULL),
    (92, 'Dome Fossil', 'common', 'https://images.pokemontcg.io/pl4/92_hires.png', NULL),
    (93, 'Helix Fossil', 'common', 'https://images.pokemontcg.io/pl4/93_hires.png', NULL),
    (94, 'Arceus LV.X', 'ultra_rare', 'https://images.pokemontcg.io/pl4/94_hires.png', 'colorless'),
    (95, 'Arceus LV.X', 'ultra_rare', 'https://images.pokemontcg.io/pl4/95_hires.png', 'colorless'),
    (96, 'Arceus LV.X', 'ultra_rare', 'https://images.pokemontcg.io/pl4/96_hires.png', 'colorless'),
    (97, 'Gengar LV.X', 'ultra_rare', 'https://images.pokemontcg.io/pl4/97_hires.png', 'psychic'),
    (98, 'Salamence LV.X', 'ultra_rare', 'https://images.pokemontcg.io/pl4/98_hires.png', 'colorless'),
    (99, 'Tangrowth LV.X', 'ultra_rare', 'https://images.pokemontcg.io/pl4/99_hires.png', 'grass'),
    (501010, 'Bagon', 'rare', 'https://images.pokemontcg.io/pl4/SH10_hires.png', 'colorless'),
    (501011, 'Ponyta', 'rare', 'https://images.pokemontcg.io/pl4/SH11_hires.png', 'fire'),
    (501012, 'Shinx', 'rare', 'https://images.pokemontcg.io/pl4/SH12_hires.png', 'lightning'),
    (502001, 'Arceus', 'rare', 'https://images.pokemontcg.io/pl4/AR1_hires.png', 'darkness'),
    (502002, 'Arceus', 'rare', 'https://images.pokemontcg.io/pl4/AR2_hires.png', 'grass'),
    (502003, 'Arceus', 'rare', 'https://images.pokemontcg.io/pl4/AR3_hires.png', 'fire'),
    (502004, 'Arceus', 'rare', 'https://images.pokemontcg.io/pl4/AR4_hires.png', 'water'),
    (502005, 'Arceus', 'rare', 'https://images.pokemontcg.io/pl4/AR5_hires.png', 'colorless'),
    (502006, 'Arceus', 'rare', 'https://images.pokemontcg.io/pl4/AR6_hires.png', 'lightning'),
    (502007, 'Arceus', 'rare', 'https://images.pokemontcg.io/pl4/AR7_hires.png', 'psychic'),
    (502008, 'Arceus', 'rare', 'https://images.pokemontcg.io/pl4/AR8_hires.png', 'fighting'),
    (502009, 'Arceus', 'rare', 'https://images.pokemontcg.io/pl4/AR9_hires.png', 'metal')
  ) as v(number, name, rarity, image_url, pokemon_type)
  on conflict (set_id, number) do nothing
  returning id, rarity
)
insert into card_variants (card_id, variant, price_sek, stock)
select ic.id, x.variant, 0, 0
from inserted_cards ic
cross join lateral (
  select case when ic.rarity = 'rare' then 'holo' else 'normal' end as variant
  union all
  select 'reverse_holo' where ic.rarity in ('common','rare')
) as x(variant)
on conflict (card_id, variant) do nothing;
