-- Seed data for Topps Premier League 2026/27 > Grundset (Base + Future Stars), 300 cards.
-- Run this once in the Supabase SQL editor after schema.sql AND
-- set_visibility.sql AND topps_rarity.sql.
-- Stock defaults to 0 -- cards stay greyed out (and the set stays hidden)
-- until you set real stock in /admin. Price defaults to a flat placeholder
-- -- edit per card once you know actual values.
-- Only a 'normal' variant is created (no holo) since Topps football cards
-- don't use that concept -- parallels/autos would need their own card rows
-- if you want to sell those separately later.

with s as (
  insert into sets (category_slug, category_name, slug, name, is_visible)
  values ('topps-premier-league', 'Topps Premier League 2026/27', 'grundset', 'Grundset (Base + Future Stars)', false)
  returning id
),
inserted_cards as (
  insert into cards (set_id, number, name, rarity)
  select s.id, v.number, v.name, v.rarity
  from s, (values
  (1, 'Max Dowman (Arsenal FS)', 'base'),
  (2, 'Jamaldeen Jimoh-Aloba (Aston Villa FS)', 'base'),
  (3, 'Veljko Milosavljević (AFC Bournemouth FS)', 'base'),
  (4, 'Junior Kroupi (AFC Bournemouth FS)', 'base'),
  (5, 'Yasin Ayari (Brighton FS)', 'base'),
  (6, 'Stefanos Tzimas (Brighton FS)', 'base'),
  (7, 'Reggie Walsh (Chelsea FS)', 'base'),
  (8, 'Estêvão Willian (Chelsea FS)', 'base'),
  (9, 'Dastan Satpayev (Chelsea FS)', 'base'),
  (10, 'Romain Esse (Crystal Palace FS)', 'base'),
  (11, 'Joél Drakes-Thomas (Crystal Palace FS)', 'base'),
  (12, 'Josh King (Fulham FS)', 'base'),
  (13, 'Harry Gray (Leeds United FS)', 'base'),
  (14, 'Giovanni Leoni (Liverpool FC FS)', 'base'),
  (15, 'Rio Ngumoha (Liverpool FC FS)', 'base'),
  (16, 'Divine Mukasa (Manchester City FS)', 'base'),
  (17, 'Jack Fletcher (Manchester United FS)', 'base'),
  (18, 'Shea Lacey (Manchester United FS)', 'base'),
  (19, 'Igor Jesus (Nottingham Forest FS)', 'base'),
  (20, 'Chris Rigg (Sunderland FS)', 'base'),
  (21, 'William Saliba (Arsenal)', 'base'),
  (22, 'Gabriel Magalhães (Arsenal)', 'base'),
  (23, 'Jaden Dixon (Arsenal RC)', 'base'),
  (24, 'Jurriën Timber (Arsenal)', 'base'),
  (25, 'Myles Lewis-Skelly (Arsenal)', 'base'),
  (26, 'Martín Zubimendi (Arsenal)', 'base'),
  (27, 'Ife Ibrahim (Arsenal RC)', 'base'),
  (28, 'Declan Rice (Arsenal)', 'base'),
  (29, 'Martin Ødegaard (Arsenal)', 'base'),
  (30, 'Eberechi Eze (Arsenal)', 'base'),
  (31, 'Gabriel Martinelli (Arsenal)', 'base'),
  (32, 'Bukayo Saka (Arsenal)', 'base'),
  (33, 'Viktor Gyökeres (Arsenal)', 'base'),
  (34, 'Brando Bailey-Joseph (Arsenal RC)', 'base'),
  (35, 'Pau Torres (Aston Villa)', 'base'),
  (36, 'Ezri Konsa (Aston Villa)', 'base'),
  (37, 'Matty Cash (Aston Villa)', 'base'),
  (38, 'Lamare Bogarde (Aston Villa)', 'base'),
  (39, 'Ian Maatsen (Aston Villa)', 'base'),
  (40, 'Boubacar Kamara (Aston Villa)', 'base'),
  (41, 'Amadou Onana (Aston Villa)', 'base'),
  (42, 'Youri Tielemans (Aston Villa)', 'base'),
  (43, 'John McGinn (Aston Villa)', 'base'),
  (44, 'Morgan Rogers (Aston Villa)', 'base'),
  (45, 'Alysson (Aston Villa RC)', 'base'),
  (46, 'Brian Madjo (Aston Villa RC)', 'base'),
  (47, 'Tammy Abraham (Aston Villa)', 'base'),
  (48, 'Ollie Watkins (Aston Villa)', 'base'),
  (49, 'Bafodé Diakité (AFC Bournemouth)', 'base'),
  (50, 'Julio Soler (AFC Bournemouth)', 'base'),
  (51, 'Adrien Truffert (AFC Bournemouth)', 'base'),
  (52, 'Tyler Adams (AFC Bournemouth)', 'base'),
  (53, 'Marcus Tavernier (AFC Bournemouth)', 'base'),
  (54, 'Alex Scott (AFC Bournemouth)', 'base'),
  (55, 'David Brooks (AFC Bournemouth)', 'base'),
  (56, 'Alex Tóth (AFC Bournemouth RC)', 'base'),
  (57, 'Lewis Cook (AFC Bournemouth)', 'base'),
  (58, 'Amine Adli (AFC Bournemouth)', 'base'),
  (59, 'Ben Gannon-Doak (AFC Bournemouth)', 'base'),
  (60, 'Justin Kluivert (AFC Bournemouth)', 'base'),
  (61, 'Rayan (AFC Bournemouth RC)', 'base'),
  (62, 'Evanilson (AFC Bournemouth)', 'base'),
  (63, 'Nathan Collins (Brentford)', 'base'),
  (64, 'Sepp van den Berg (Brentford)', 'base'),
  (65, 'Michael Kayode (Brentford)', 'base'),
  (66, 'Yunus Konak (Brentford)', 'base'),
  (67, 'Antoni Milambo (Brentford)', 'base'),
  (68, 'Mathias Jensen (Brentford)', 'base'),
  (69, 'Jordan Henderson (Brentford)', 'base'),
  (70, 'Mikkel Damsgaard (Brentford)', 'base'),
  (71, 'Yehor Yarmolyuk (Brentford)', 'base'),
  (72, 'Kaye Furo (Brentford RC)', 'base'),
  (73, 'Kevin Schade (Brentford)', 'base'),
  (74, 'Keane Lewis-Potter (Brentford)', 'base'),
  (75, 'Igor Thiago (Brentford)', 'base'),
  (76, 'Dango Ouattara (Brentford)', 'base'),
  (77, 'Jan Paul van Hecke (Brighton)', 'base'),
  (78, 'Ferdi Kadıoğlu (Brighton)', 'base'),
  (79, 'Lewis Dunk (Brighton)', 'base'),
  (80, 'Diego Coppola (Brighton)', 'base'),
  (81, 'Jack Hinshelwood (Brighton)', 'base'),
  (82, 'Carlos Baleba (Brighton)', 'base'),
  (83, 'Diego Gómez (Brighton)', 'base'),
  (84, 'Mats Wieffer (Brighton)', 'base'),
  (85, 'Pascal Groß (Brighton)', 'base'),
  (86, 'Kaoru Mitoma (Brighton)', 'base'),
  (87, 'Charalampos Kostoulas (Brighton)', 'base'),
  (88, 'Danny Welbeck (Brighton)', 'base'),
  (89, 'Georginio Rutter (Brighton)', 'base'),
  (90, 'Yankuba Minteh (Brighton)', 'base'),
  (91, 'Jorrel Hato (Chelsea)', 'base'),
  (92, 'Reece James (Chelsea)', 'base'),
  (93, 'Marc Cucurella (Chelsea)', 'base'),
  (94, 'Malo Gusto (Chelsea)', 'base'),
  (95, 'Moisés Caicedo (Chelsea)', 'base'),
  (96, 'Enzo Fernández (Chelsea)', 'base'),
  (97, 'Landon Emenalo (Chelsea RC)', 'base'),
  (98, 'Andrey Santos (Chelsea)', 'base'),
  (99, 'Jesse Derry (Chelsea RC)', 'base'),
  (100, 'Pedro Neto (Chelsea)', 'base'),
  (101, 'Alejandro Garnacho (Chelsea)', 'base'),
  (102, 'Ryan Kavuma-McQueen (Chelsea RC)', 'base'),
  (103, 'João Pedro (Chelsea)', 'base'),
  (104, 'Cole Palmer (Chelsea)', 'base'),
  (105, 'Tyrick Mitchell (Crystal Palace)', 'base'),
  (106, 'Maxence Lacroix (Crystal Palace)', 'base'),
  (107, 'Chadi Riad (Crystal Palace)', 'base'),
  (108, 'Dean Benamar (Crystal Palace RC)', 'base'),
  (109, 'Chris Richards (Crystal Palace)', 'base'),
  (110, 'Daniel Muñoz (Crystal Palace)', 'base'),
  (111, 'Justin Devenny (Crystal Palace)', 'base'),
  (112, 'Adam Wharton (Crystal Palace)', 'base'),
  (113, 'Yéremy Pino (Crystal Palace)', 'base'),
  (114, 'Brennan Johnson (Crystal Palace)', 'base'),
  (115, 'Ismaïla Sarr (Crystal Palace)', 'base'),
  (116, 'Eddie Nketiah (Crystal Palace)', 'base'),
  (117, 'Jørgen Strand Larsen (Crystal Palace)', 'base'),
  (118, 'Jean-Philippe Mateta (Crystal Palace)', 'base'),
  (119, 'James Tarkowski (Everton)', 'base'),
  (120, 'Jarrad Branthwaite (Everton)', 'base'),
  (121, 'Adam Aznou (Everton)', 'base'),
  (122, 'Jake O''Brien (Everton)', 'base'),
  (123, 'Vitalii Mykolenko (Everton)', 'base'),
  (124, 'Charly Alcaraz (Everton)', 'base'),
  (125, 'Tim Iroegbunam (Everton)', 'base'),
  (126, 'Kiernan Dewsbury-Hall (Everton)', 'base'),
  (127, 'James Garner (Everton)', 'base'),
  (128, 'Tyler Dibling (Everton)', 'base'),
  (129, 'Dwight McNeil (Everton)', 'base'),
  (130, 'Iliman Ndiaye (Everton)', 'base'),
  (131, 'Beto (Everton)', 'base'),
  (132, 'Thierno Barry (Everton)', 'base'),
  (133, 'Calvin Bassey (Fulham)', 'base'),
  (134, 'Joachim Andersen (Fulham)', 'base'),
  (135, 'Antonee Robinson (Fulham)', 'base'),
  (136, 'Kenny Tete (Fulham)', 'base'),
  (137, 'Timothy Castagne (Fulham)', 'base'),
  (138, 'Saša Lukić (Fulham)', 'base'),
  (139, 'Sander Berge (Fulham)', 'base'),
  (140, 'Alex Iwobi (Fulham)', 'base'),
  (141, 'Seth Ridgeon (Fulham RC)', 'base'),
  (142, 'Emile Smith Rowe (Fulham)', 'base'),
  (143, 'Oscar Bobb (Fulham)', 'base'),
  (144, 'Aaron Loupalo-Bi (Fulham RC)', 'base'),
  (145, 'Kevin (Fulham)', 'base'),
  (146, 'Rodrigo Muniz (Fulham)', 'base'),
  (147, 'Joe Rodon (Leeds United)', 'base'),
  (148, 'Pascal Struijk (Leeds United)', 'base'),
  (149, 'Jayden Bogle (Leeds United)', 'base'),
  (150, 'Ethan Ampadu (Leeds United)', 'base'),
  (151, 'Gabriel Gudmundsson (Leeds United)', 'base'),
  (152, 'Sean Longstaff (Leeds United)', 'base'),
  (153, 'Ao Tanaka (Leeds United)', 'base'),
  (154, 'Brenden Aaronson (Leeds United)', 'base'),
  (155, 'Anton Stach (Leeds United)', 'base'),
  (156, 'Lukas Nmecha (Leeds United)', 'base'),
  (157, 'Wilfried Gnonto (Leeds United)', 'base'),
  (158, 'Daniel James (Leeds United)', 'base'),
  (159, 'Noah Okafor (Leeds United)', 'base'),
  (160, 'Dominic Calvert-Lewin (Leeds United)', 'base'),
  (161, 'Jérémy Jacquet (Liverpool FC RC)', 'base'),
  (162, 'Virgil van Dijk (Liverpool FC)', 'base'),
  (163, 'Milos Kerkez (Liverpool FC)', 'base'),
  (164, 'Jeremie Frimpong (Liverpool FC)', 'base'),
  (165, 'Conor Bradley (Liverpool FC)', 'base'),
  (166, 'Ryan Gravenberch (Liverpool FC)', 'base'),
  (167, 'Alexis Mac Allister (Liverpool FC)', 'base'),
  (168, 'Dominik Szoboszlai (Liverpool FC)', 'base'),
  (169, 'Curtis Jones (Liverpool FC)', 'base'),
  (170, 'Florian Wirtz (Liverpool FC)', 'base'),
  (171, 'Keyrol Figueroa (Liverpool FC RC)', 'base'),
  (172, 'Cody Gakpo (Liverpool FC)', 'base'),
  (173, 'Hugo Ekitike (Liverpool FC)', 'base'),
  (174, 'Alexander Isak (Liverpool FC)', 'base'),
  (175, 'Marc Guéhi (Manchester City)', 'base'),
  (176, 'Rúben Dias (Manchester City)', 'base'),
  (177, 'Joško Gvardiol (Manchester City)', 'base'),
  (178, 'Nico O''Reilly (Manchester City)', 'base'),
  (179, 'Floyd Samba (Manchester City RC)', 'base'),
  (180, 'Tijjani Reijnders (Manchester City)', 'base'),
  (181, 'Rodri (Manchester City)', 'base'),
  (182, 'Jérémy Doku (Manchester City)', 'base'),
  (183, 'Phil Foden (Manchester City)', 'base'),
  (184, 'Rayan Cherki (Manchester City)', 'base'),
  (185, 'Antoine Semenyo (Manchester City)', 'base'),
  (186, 'Ryan McAidoo (Manchester City RC)', 'base'),
  (187, 'Omar Marmoush (Manchester City)', 'base'),
  (188, 'Erling Haaland (Manchester City)', 'base'),
  (189, 'Tyler Fredricson (Manchester United RC)', 'base'),
  (190, 'Leny Yoro (Manchester United)', 'base'),
  (191, 'Lisandro Martínez (Manchester United)', 'base'),
  (192, 'Ayden Heaven (Manchester United)', 'base'),
  (193, 'Patrick Dorgu (Manchester United)', 'base'),
  (194, 'Godwill Kukonki (Manchester United RC)', 'base'),
  (195, 'Kobbie Mainoo (Manchester United)', 'base'),
  (196, 'Bruno Fernandes (Manchester United)', 'base'),
  (197, 'Tyler Fletcher (Manchester United RC)', 'base'),
  (198, 'JJ Gabriel (Manchester United RC)', 'base'),
  (199, 'Matheus Cunha (Manchester United)', 'base'),
  (200, 'Amad (Manchester United)', 'base'),
  (201, 'Bryan Mbeumo (Manchester United)', 'base'),
  (202, 'Benjamin Šeško (Manchester United)', 'base'),
  (203, 'Sven Botman (Newcastle United)', 'base'),
  (204, 'Malick Thiaw (Newcastle United)', 'base'),
  (205, 'Tino Livramento (Newcastle United)', 'base'),
  (206, 'Lewis Hall (Newcastle United)', 'base'),
  (207, 'Dan Burn (Newcastle United)', 'base'),
  (208, 'Jacob Ramsey (Newcastle United)', 'base'),
  (209, 'Sandro Tonali (Newcastle United)', 'base'),
  (210, 'Joelinton (Newcastle United)', 'base'),
  (211, 'Bruno Guimarães (Newcastle United)', 'base'),
  (212, 'Sean Neave (Newcastle United RC)', 'base'),
  (213, 'Harvey Barnes (Newcastle United)', 'base'),
  (214, 'Yoane Wissa (Newcastle United)', 'base'),
  (215, 'Nick Woltemade (Newcastle United)', 'base'),
  (216, 'Anthony Elanga (Newcastle United)', 'base'),
  (217, 'Nikola Milenković (Nottingham Forest)', 'base'),
  (218, 'Nicolò Savona (Nottingham Forest)', 'base'),
  (219, 'Murillo (Nottingham Forest)', 'base'),
  (220, 'Luca Netz (Nottingham Forest)', 'base'),
  (221, 'Neco Williams (Nottingham Forest)', 'base'),
  (222, 'Ola Aina (Nottingham Forest)', 'base'),
  (223, 'James McAtee (Nottingham Forest)', 'base'),
  (224, 'Elliot Anderson (Nottingham Forest)', 'base'),
  (225, 'Morgan Gibbs-White (Nottingham Forest)', 'base'),
  (226, 'Ryan Yates (Nottingham Forest)', 'base'),
  (227, 'Omari Hutchinson (Nottingham Forest)', 'base'),
  (228, 'Callum Hudson-Odoi (Nottingham Forest)', 'base'),
  (229, 'Dan Ndoye (Nottingham Forest)', 'base'),
  (230, 'Chris Wood (Nottingham Forest)', 'base'),
  (231, 'Trai Hume (Sunderland)', 'base'),
  (232, 'Reinildo Mandava (Sunderland)', 'base'),
  (233, 'Omar Alderete (Sunderland)', 'base'),
  (234, 'Nordi Mukiele (Sunderland)', 'base'),
  (235, 'Habib Diarra (Sunderland)', 'base'),
  (236, 'Granit Xhaka (Sunderland)', 'base'),
  (237, 'Noah Sadiki (Sunderland)', 'base'),
  (238, 'Enzo Le Fée (Sunderland)', 'base'),
  (239, 'Nilson Angulo (Sunderland)', 'base'),
  (240, 'Timur Tutierov (Sunderland RC)', 'base'),
  (241, 'Brian Brobbey (Sunderland)', 'base'),
  (242, 'Chemsdine Talbi (Sunderland)', 'base'),
  (243, 'Eliezer Mayenda (Sunderland)', 'base'),
  (244, 'Wilson Isidor (Sunderland)', 'base'),
  (245, 'Pedro Porro (Tottenham)', 'base'),
  (246, 'Micky van de Ven (Tottenham)', 'base'),
  (247, 'Cristian Romero (Tottenham)', 'base'),
  (248, 'Souza (Tottenham RC)', 'base'),
  (249, 'Djed Spence (Tottenham)', 'base'),
  (250, 'Archie Gray (Tottenham)', 'base'),
  (251, 'Conor Gallagher (Tottenham)', 'base'),
  (252, 'Dejan Kulusevski (Tottenham)', 'base'),
  (253, 'Lucas Bergvall (Tottenham)', 'base'),
  (254, 'Xavi Simons (Tottenham)', 'base'),
  (255, 'Lucá Williams-Barnett (Tottenham RC)', 'base'),
  (256, 'James Maddison (Tottenham)', 'base'),
  (257, 'Mohammed Kudus (Tottenham)', 'base'),
  (258, 'Dominic Solanke (Tottenham)', 'base'),
  (259, 'Milan van Ewijk (Coventry City)', 'base'),
  (260, 'Jay Dasilva (Coventry City)', 'base'),
  (261, 'Liam Kitching (Coventry City RC)', 'base'),
  (262, 'Bobby Thomas (Coventry City RC)', 'base'),
  (263, 'Joel Latibeaudiere (Coventry City RC)', 'base'),
  (264, 'Matt Grimes (Coventry City)', 'base'),
  (265, 'Victor Torp (Coventry City)', 'base'),
  (266, 'Jack Rudoni (Coventry City)', 'base'),
  (267, 'Josh Eccles (Coventry City RC)', 'base'),
  (268, 'Ellis Simms (Coventry City)', 'base'),
  (269, 'Brandon Thomas-Asante (Coventry City)', 'base'),
  (270, 'Tatsuhiro Sakamoto (Coventry City)', 'base'),
  (271, 'Ephron Mason-Clark (Coventry City RC)', 'base'),
  (272, 'Haji Wright (Coventry City)', 'base'),
  (273, 'Dara O''Shea (Ipswich Town)', 'base'),
  (274, 'Darnell Furlong (Ipswich Town)', 'base'),
  (275, 'Leif Davis (Ipswich Town)', 'base'),
  (276, 'Cédric Kipré (Ipswich Town)', 'base'),
  (277, 'Jacob Greaves (Ipswich Town)', 'base'),
  (278, 'Ben Johnson (Ipswich Town)', 'base'),
  (279, 'Azor Matusiwa (Ipswich Town)', 'base'),
  (280, 'Jack Taylor (Ipswich Town RC)', 'base'),
  (281, 'Marcelino Núñez (Ipswich Town)', 'base'),
  (282, 'Kasey McAteer (Ipswich Town)', 'base'),
  (283, 'Sindre Walle Egeli (Ipswich Town)', 'base'),
  (284, 'Jaden Philogene (Ipswich Town)', 'base'),
  (285, 'George Hirst (Ipswich Town)', 'base'),
  (286, 'Jack Clarke (Ipswich Town)', 'base'),
  (287, 'John Egan (Hull City)', 'base'),
  (288, 'Charlie Hughes (Hull City)', 'base'),
  (289, 'Lewie Coyle (Hull City)', 'base'),
  (290, 'Ryan Giles (Hull City)', 'base'),
  (291, 'Semi Ajayi (Hull City)', 'base'),
  (292, 'Cody Drameh (Hull City)', 'base'),
  (293, 'Darko Gyabi (Hull City RC)', 'base'),
  (294, 'Regan Slater (Hull City RC)', 'base'),
  (295, 'Matt Crooks (Hull City)', 'base'),
  (296, 'David Akintola (Hull City RC)', 'base'),
  (297, 'Liam Millar (Hull City)', 'base'),
  (298, 'Mohamed Belloumi (Hull City RC)', 'base'),
  (299, 'Kyle Joseph (Hull City RC)', 'base'),
  (300, 'Oli McBurnie (Hull City)', 'base')
  ) as v(number, name, rarity)
  returning id
)
insert into card_variants (card_id, variant, price_sek, stock)
select ic.id, 'normal', 3, 0
from inserted_cards ic;
